var gvjs_cZ='Failed geocoding "',gvjs_dZ="Requested map does not exist.",gvjs_eZ="The visualization is not ready yet.",gvjs_fZ="bottom_left",gvjs_gZ="feature",gvjs_hZ="featureClick",gvjs_iZ="featureHover",gvjs_jZ="featureMove",gvjs_kZ="google.visualization.GeoChart.mapExists",gvjs_lZ="google.visualization.GeoChart.setMapsSource",gvjs_mZ="kavrayskiy-vii",gvjs_nZ="magnifyingGlassBorder",gvjs_oZ="magnifyingGlassTriangle",gvjs_pZ="marker",gvjs_qZ="markerClick",gvjs_rZ="markerHover",gvjs_sZ="mercator",
gvjs_tZ="natural",gvjs_uZ="top_left";gvjs_$I.prototype.BW=gvjs_V(68,function(){var a=this,b=gvjs_v(this.lines,function(c){var d=a.anchor?a.anchor:{x:0,y:0},e=gvjs_RA(c.x+d.x,c.length,a.ld);c=gvjs_RA(c.y+d.y,a.ja.fontSize,a.Pc);return e.start==e.end||c.start==c.end?null:new gvjs_B(c.start,e.end,c.end,e.start)});b=gvjs_De(b,function(c){return null!=c});return gvjs_6B(b)});gvjs_TA.prototype.cw=gvjs_V(36,function(){return!1});gvjs_PB.prototype.cw=gvjs_V(35,function(){return!0});
function gvjs_vZ(a){return Math.min(a.width,a.height)}
var gvjs_nla={hBa:gvjs_yd,JAa:gvjs_bd,TEXT:gvjs_m,YF:gvjs_ub},gvjs_ola={IM:gvjs_S,OM:gvjs_U},gvjs_pla=["AD","AE","AF","AG","AL","AM","AO","AR","AT","AU","AZ","BA","BB","BD","BE","BF","BG","BH","BI","BJ","BN","BO","BR","BS","BT","BW","BY","BZ","CA","CD","CF","CG","CH","CI","CL","CM","CN","CO","CR","CS","CU","CV","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","ER","ES","ET","FI","FJ","FM","FR","GA","GB","GD","GE","GH","GM","GN","GQ","GR","GT","GW","GY","HN","HR","HT","HU","ID","IE","IL","IN",
"IQ","IR","IS","IT","JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KZ","LA","LB","LI","LK","LR","LS","LT","LU","LV","LY","MA","MD","ME","MG","MH","MK","ML","MM","MN","MR","MT","MU","MV","MW","MX","MY","MZ","NA","NE","NG","NI","NL","NO","NP","NR","NZ","OM","PA","PE","PG","PH","PK","PL","PT","PW","PY","QA","RO","RS","RU","RW","SA","SB","SC","SD","SE","SG","SH","SI","SK","SL","SM","SN","SO","SR","ST","SV","SY","SZ",gvjs_ps,"TG","TH","TJ","TL","TM","TN","TO",gvjs_qs,"TT","TV","TW","TZ",
"UA","UG","UM","US","UY","UZ","VC","VE","VN","VU","WS","YE","YU","ZA","ZM","ZW"],gvjs_qla=["ad","ae","af","ag","al","am","ao","ar","as","at","au","ax","az","ba","bb","bd","be","bf","bg","bh","bi","bj","bm","bn","bo","bq","br","bs","bt","bw","by","bz","ca","cd","cf","cg","ch","ci","cl","cm","co","cr","cu","cv","cw","cy","cz","de","dj","dk","dm","do","dz","ec","ee","eg","eh","er","es","et","fi","fj","fm","fo","fr","ga","gb","gd","ge","gf","gg","gh","gl","gm","gn","gp","gq","gr","gt","gw","gy","hk",
"hn","hr","ht","hu",gvjs_5c,"ie","il",gvjs_Cp,"iq","ir","is","it","je","jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt","lu","lv","ly","ma","md","me","mf","mg","mh","mk","ml","mm","mn","mp","mq","mr","ms","mu","mv","mw","mx","my","mz","na","nc","ne","ng","ni","nl","no","np","nr","nu","nz","om","pa","pe","pf","pg","ph","pk","pl","pm","pr","ps","pt","pw","py","qa","re","ro","rs","ru","rw","sa","sb","sc","sd","se","sh","si","sj","sk","sl","sm",
"sn","so","sr","ss","st","sv","sx","sy","sz","tc","td","tg","th","tj","tk","tl","tm","tn","to","tr","tt","tv","tw","tz","ua","ug","us","uy","uz","vc","ve","vg","vi","vn","vu","wf","ws","xk","ye","yt","za","zm","zw"];function gvjs_rla(a){var b=gvjs_pla;"1"===gvjs_MT&&(b=gvjs_qla,a=a.toLowerCase());return 0<=gvjs_Ey(b,a)};function gvjs_wZ(a){this.selection=new gvjs_7n;this.iw=this.Nj=this.iI=this.ff=null;if(null!=a){this.selection.setSelection(a.selection);var b=new gvjs_yj([a]);this.ff=b.cb("focusedFeature");this.iI=b.cb("focusedMarker");if(null!=b.pb("elaborated")){a=b.Aa("elaborated.rowId");var c=b.Dq("elaborated.isDisputed"),d=b.Aa("elaborated.origin.x");b=b.Aa("elaborated.origin.y");null!=a&&null!=d&&null!=b&&null!=c&&(this.Nj={oj:a,gJ:c,origin:{x:d,y:b}})}}}
gvjs_wZ.prototype.clone=function(){var a=new gvjs_wZ;a.selection=this.selection.clone();a.ff=gvjs_0e(this.ff);a.Nj=gvjs_0e(this.Nj);a.iw=gvjs_0e(this.iw);return a};gvjs_wZ.prototype.equals=function(a){return gvjs_Bi(this)==gvjs_Bi(a)};var gvjs_xZ={Yza:"continents",EBa:"subcontinents",Zza:gvjs_mT,fBa:gvjs_sT,PAa:"metros"};function gvjs_yZ(a){this.m=a||{}}gvjs_yZ.prototype.project=function(){return[]};gvjs_yZ.prototype.fZ=function(){return 1.618};gvjs_yZ.prototype.set=function(a,b){this.m[a]=b};gvjs_yZ.prototype.Zc=function(){return gvjs_0e(this.m)};function gvjs_zZ(a){var b=0,c=0;if(a.boundingBox){var d=a.boundingBox.lo;c=a.boundingBox.hi;b=(c[0]-d[0])/2+d[0];c=(c[1]-d[1])/2+d[1]}d=[29.5,45.5];b={parallels:d,origin:{lat:b,lng:c}};c=b.origin;a.origin&&Object.assign(c,a.origin);Object.assign(b,a);b.origin=c;b.parallels&&0!==b.parallels.length?2>b.parallels.length&&(b.parallels[1]=Math.abs(b.parallels[0]-d[0])>Math.abs(b.parallels[0]-d[1])?d[0]:d[1]):b.parallels=d;this.m=a||{};this.Z1=b.origin.lat/(180/Math.PI);this.cS=b.origin.lng/(180/Math.PI);
this.bp=gvjs_v(b.parallels,function(e){return e/(180/Math.PI)})}gvjs_o(gvjs_zZ,gvjs_yZ);gvjs_zZ.prototype.project=function(a){var b=this;return gvjs_v(arguments,function(c){var d=c[0]/(180/Math.PI),e=.5*(Math.sin(b.bp[0])+Math.sin(b.bp[1]));c=e*(c[1]/(180/Math.PI)-b.cS);var f=Math.cos(b.bp[0]);f=f*f+2*e*Math.sin(b.bp[0]);d=Math.sqrt(f-2*e*Math.sin(d))/e;return{x:180/Math.PI*Math.sin(c)*d,y:180/Math.PI*(Math.sqrt(f-2*e*Math.sin(b.Z1))/e-d*Math.cos(c))}})};function gvjs_AZ(a){this.m=a||{}}gvjs_o(gvjs_AZ,gvjs_yZ);gvjs_AZ.prototype.fZ=function(){return 2.2};gvjs_AZ.prototype.project=function(a){return gvjs_v(arguments,function(b){var c=b[0]/(180/Math.PI);return{x:b[1]/(180/Math.PI)*3/(2*Math.PI)*Math.sqrt(Math.PI*Math.PI/3-c*c)*(180/Math.PI),y:c}})};function gvjs_BZ(a){var b=0,c=0;if(a.boundingBox){var d=a.boundingBox.lo;c=a.boundingBox.hi;b=(c[0]-d[0])/2+d[0];c=(c[1]-d[1])/2+d[1]}d=[20,50];b={parallels:d,origin:{lat:b,lng:c}};c=b.origin;a.origin&&Object.assign(c,a.origin);Object.assign(b,a);b.origin=c;b.parallels&&0!==b.parallels.length?2>b.parallels.length&&(b.parallels[1]=Math.abs(b.parallels[0]-d[0])>Math.abs(b.parallels[0]-d[1])?d[0]:d[1]):b.parallels=d;this.m=a||{};this.Z1=b.origin.lat/(180/Math.PI);this.cS=b.origin.lng/(180/Math.PI);this.bp=
gvjs_v(b.parallels,function(e){return e/(180/Math.PI)})}gvjs_o(gvjs_BZ,gvjs_yZ);
gvjs_BZ.prototype.project=function(a){var b=this;return gvjs_v(arguments,function(c){var d=c[1]/(180/Math.PI),e=Math.log(1/Math.cos(b.bp[1])*Math.cos(b.bp[0]))/Math.log(1/Math.tan(.25*Math.PI+.5*b.bp[0])*Math.tan(.25*Math.PI+.5*b.bp[1])),f=Math.cos(b.bp[0])*Math.pow(Math.tan(.25*Math.PI+.5*b.bp[0]),e)/e;c=f*Math.pow(1/Math.tan(.25*Math.PI+c[0]/(180/Math.PI)*.5),e);return{x:180/Math.PI*Math.sin(e*(d-b.cS))*c,y:f*Math.pow(1/Math.tan(.25*Math.PI+.5*b.Z1),e)-180/Math.PI*Math.cos(e*(d-b.cS))*c}})};function gvjs_CZ(a){return 180/Math.PI*(Math.atan(Math.exp(a/(180/Math.PI)))-Math.PI/4)*2}function gvjs_DZ(){this.Ir={}}gvjs_DZ.prototype.track=function(a){var b=this;gvjs_u(arguments,function(c){for(var d in c)if(c.hasOwnProperty(d)){d in b.Ir||(b.Ir[d]={min:Infinity,max:-Infinity});if(!b.Ir[d].min||c[d]<b.Ir[d].min)b.Ir[d].min=c[d];if(!b.Ir[d].max||c[d]>b.Ir[d].max)b.Ir[d].max=c[d]}})};gvjs_DZ.prototype.getBounds=function(a){return{min:this.Ir[a].min,max:this.Ir[a].max}};function gvjs_EZ(a){this.m=a||{}}gvjs_o(gvjs_EZ,gvjs_yZ);gvjs_EZ.prototype.project=function(a){return gvjs_v(arguments,function(b){return{x:b[1],y:180/Math.PI*Math.log(Math.tan(b[0]/180*.5*Math.PI+Math.PI/4))}})};var gvjs_sla={uza:"albers",AAa:gvjs_mZ,DAa:"lambert",OAa:gvjs_sZ},gvjs_FZ={};gvjs_FZ.mercator=gvjs_EZ;gvjs_FZ[gvjs_mZ]=gvjs_AZ;gvjs_FZ.albers=gvjs_zZ;gvjs_FZ.lambert=gvjs_BZ;var gvjs_tla={NONE:gvjs_f,TOP_LEFT:gvjs_uZ,TOP_RIGHT:"top_right",BOTTOM_LEFT:gvjs_fZ,BOTTOM_RIGHT:"bottom_right"},gvjs_ula={NONE:gvjs_f,gBa:gvjs_tT,Iza:"bounds",HM:gvjs_qt};function gvjs_vla(a){return gvjs_iy(a,"projection",{name:gvjs_sZ},function(b){b=typeof b===gvjs_l?b:(gvjs_jj(b)||{}).name;b=gvjs_Fj(b,gvjs_sla);if(!b)throw Error('The projection you specified, "'+b+'", is not valid.');return{name:b}})}
var gvjs_GZ={region:gvjs_yT,resolution:gvjs_mT,domain:"COM",displayMode:gvjs_ub,showGeocodeWarnings:!1,backgroundColor:{fill:gvjs_Kx,stroke:"#666",strokeWidth:0},datalessRegionColor:"F5F5F5",defaultColor:"267114",markerOpacity:1,selectionMode:gvjs_Sw,fontName:gvjs__r,geocodingContext:gvjs_tT,tooltip:{isHtml:!1,textStyle:{fontName:gvjs__r,fontSize:13,color:gvjs_nt},trigger:gvjs_tu,showDisputedText:!1,showTitle:!0},colorAxis:{minValue:null,maxValue:null,values:null},sizeAxis:{minValue:null,maxValue:null,
minSize:3,maxSize:12},legend:{position:gvjs_fZ,orientation:gvjs_S,textStyle:{color:gvjs_nt,auraColor:gvjs_Kx}},marker:{style:{stroke:{color:gvjs_vr,width:1}}},projection:gvjs_sZ,keepAspectRatio:!0,magnifyingGlass:{enable:!0,zoomFactor:5}};function gvjs_HZ(a){gvjs_F.call(this);this.Sd=a;this.aF=null;this.Zfa=!0;this.nI=null;this.er=new gvjs_HT;this.ksa=/^([a-zA-Z][a-zA-Z]|[a-zA-Z][a-zA-Z]\-[a-zA-Z0-9](|[a-zA-Z0-9](|[a-zA-Z0-9]))|\d\d\d)$/;this.rsa=/^\d\d\d$/}gvjs_o(gvjs_HZ,gvjs_F);gvjs_=gvjs_HZ.prototype;gvjs_.Y3=function(a){this.aF=a;null!=this.$sa&&this.$sa(a)};
function gvjs_wla(a,b,c,d,e,f){a.Zfa=e;if(0===b.ca())gvjs_ml(function(){f([],[],!0)});else switch(c.NV){case gvjs_9c:a.uX(b,c,f);break;case gvjs_xd:gvjs_xla(a,b,c,d,f);break;case "address":a.tX(b,c,d,f)}}gvjs_.uX=function(a,b,c){for(var d=[],e=0;e<a.ca();e++){var f=a.getValue(e,b.sD),g=a.getValue(e,b.yD);d[e]=null==f||null==g?null:{lat:gvjs_gg(f),lng:gvjs_gg(g)}}gvjs_ml(function(){c([],d,!0)})};
function gvjs_xla(a,b,c,d,e){for(var f=[],g=0;g<b.ca();g++)f.push(b.getValue(g,c.KK));"metros"==d.resolution||"continents"==d.resolution||"subcontinents"==d.resolution?a.sX(d,f,e):a.vX(d,f,e)}gvjs_.sX=function(a,b,c){a=gvjs_hf(a.region,"US")&&"metros"==a.resolution;for(var d=[],e=0;e<b.length;e++){var f=gvjs_gg(b[e]);a&&this.rsa.test(f)&&(f="US-"+f);d.push(f.toUpperCase())}gvjs_ml(function(){c(d,[],!0)})};
gvjs_.vX=function(a,b,c){var d=this,e=a.region;var f=a.resolution==gvjs_sT&&gvjs_rla(e)?e:"countries_en";if(a.resolution==gvjs_sT&&"US"==e)for(a=0;a<b.length;++a){var g=b[a];2==g.length&&(b[a]="US-"+g)}gvjs_NT(f,function(h){h=d.$W(b,h);for(var k=[],l=0;l<b.length;l++)if(null==h[l]){var m=b[l];k.push({address:m,Lea:l,Gca:null});h[l]=m}0==k.length?c(h,[],!0):(c(h,[],!1),gvjs_IZ(d,k,e,c,h))})};
gvjs_.$W=function(a,b){for(var c=[],d=0;d<a.length;++d){var e=gvjs_kf(gvjs_gg(a[d])).toLowerCase(),f=b&&gvjs_PT(b,e);e=f?f:this.ksa.test(e)?e.toUpperCase():null;c.push(e)}return c};function gvjs_JZ(a,b){a.Zfa&&a.Sd&&gvjs_4x(a.Sd,b)}
gvjs_.tX=function(a,b,c,d){var e=[];c=c.region;2==c.length&&(c=c.toUpperCase(),c=c.replace(/GB/,"UK"),c=c.replace(/RU/,"SU"),c=c.replace(/TP/,"TL"));for(var f=0;f<a.ca();f++){var g=gvjs_gg(a.getValue(f,b.fG));gvjs_KZ(this,c)&&(g+=" "+c);e.push({address:g,Gca:f,Lea:null})}gvjs_IZ(this,e,c,d,[])};function gvjs_KZ(a,b){return b==gvjs_yT||gvjs_Uy(b)?!1:a.nI===gvjs_tT||a.nI===gvjs_qt}
function gvjs_yla(a){var b=Infinity,c=Infinity,d=-Infinity,e=-Infinity;if(null!=a.aF&&0!==a.aF.views.length)return gvjs_u(a.aF.views,function(f){f=f.Ju;b=Math.min(b,f.kh[0]);c=Math.min(b,f.kh[1]);d=Math.max(d,f.xi[0]);e=Math.max(d,f.xi[1])}),{lo:{lat:b,lng:c},hi:{lat:d,lng:e}}}
function gvjs_IZ(a,b,c,d,e){for(var f=[],g=[],h=0;h<b.length;h++){var k={address:b[h].address};gvjs_KZ(a,c)&&(k.region=c);"bounds"!==a.nI&&a.nI!==gvjs_qt||(k.bounds=gvjs_yla(a));g.push(k)}var l=gvjs_Le(b);a.er.create(g,function(m){return a.a_(l,d,e,f,m)},1)}
gvjs_.a_=function(a,b,c,d,e){for(var f=e.length,g=0;g<f;g++){var h=a[g],k=h.address,l=h.Lea;h=h.Gca;if(e[g]&&e[g][0]){var m=e[g][0];null!=l&&(c[l]=gvjs_zla(m),c[l]||(gvjs_JZ(this,gvjs_cZ+k+'"'),c[l]=k));null!=h&&(d[h]={lat:m.geometry.location.lat(),lng:m.geometry.location.lng()})}else null!=l&&(c[l]=null),null!=h&&(d[h]=null),gvjs_JZ(this,gvjs_cZ+k+'"')}gvjs_Ne(a,0,f);(a=0==a.length)&&gvjs_Ge(c,function(n){return null===n})&&gvjs_Ge(d,function(n){return null===n})&&gvjs_JZ(this,gvjs_kT);b(c,d,a)};
function gvjs_zla(a){var b=gvjs_Ux(a.address_components,function(c){return 0<=gvjs_Be(c.types,"country")});if(!b)return null;b=b.short_name;"US"==b&&(a=gvjs_Ux(a.address_components,function(c){return 0<=gvjs_Be(c.types,"administrative_area_level_1")}))&&(b="US-"+a.short_name);return b}gvjs_.M=function(){this.er.cancel();gvjs_F.prototype.M.call(this)};function gvjs_LZ(a,b,c){gvjs_F.call(this);var d=this;this.F=b;this.me=function(e,f){return d.F.me(e,f)};this.Hi=a;this.VA=[];this.gb=c;this.Fd={};this.nc=new gvjs_H;this.B0=this.jw=this.Xu=this.Xv=this.Vs=this.mw=this.pD=null}gvjs_o(gvjs_LZ,gvjs_F);gvjs_LZ.prototype.o=function(a,b){gvjs_G(this.nc,a,b)};
function gvjs_MZ(a,b){var c=a.F;c.clear();var d=c.Lm(b.width,b.height);a.Fd={};var e=c.Sa();gvjs_NZ(a,e,b,new gvjs_5(0,0,b.width,b.height),!1);var f=c.Sa(),g=a.F,h=g.Sa();a.Vs=g.Sa();for(var k=0;k<b.views.length;++k)gvjs_OZ(a,h,b,b.views[k],!1),gvjs_PZ(a,b,b.views[k]);a.mw=g.Sa();gvjs_QZ(a,a.mw,b.FD,!1,b.Hj);g.appendChild(f,h);a.Vs&&g.appendChild(f,a.Vs);g.appendChild(f,a.mw);g=b.bta;f=c.ZG(f,a.cw()?new gvjs_5(g.left,g.top,g.width-1,g.height-1):g);a.Xu=c.Sa();gvjs_RZ(a,b);a.jw=c.Sa();gvjs_SZ(a,b);
a.Xv=c.Sa();gvjs_TZ(a,b);c.appendChild(d,e);c.appendChild(e,f);c.appendChild(e,a.Xu);c.appendChild(e,a.jw);c.appendChild(e,a.Xv);a.pD=b;gvjs_Ala(a,d)}function gvjs_UZ(a,b,c){c=void 0===c?!1:c;a.Xv&&a.F.qc(a.Xv);gvjs_TZ(a,b);if(c||!gvjs_Qz(a.pD.NC,b.NC))for(a.Vs&&a.F.qc(a.Vs),c=0;c<b.views.length;++c)gvjs_PZ(a,b,b.views[c]);gvjs_Bla(a,b);a.Xu&&a.F.qc(a.Xu);gvjs_RZ(a,b);a.B0!=(b.HJ?b.HJ.Xo:null)&&a.jw&&(a.F.qc(a.jw),gvjs_SZ(a,b));a.pD=b}
function gvjs_PZ(a,b,c){var d=a.F.Sa();c=gvjs_De(c.features,function(f){return gvjs_He(b.NC,f.id)});for(var e=0;e<c.length;++e)gvjs_Cla(a,d,b,c[e]);a.F.appendChild(a.Vs,d)}function gvjs_VZ(a,b){var c=a.F;gvjs_u(gvjs_lh(a.mw.j()),function(d){gvjs_u(gvjs_lh(d),function(e){c.Re(e)},this)},a);gvjs_QZ(a,a.mw,b.FD,!1,b.Hj)}function gvjs_Cla(a,b,c,d){a.cw()||(c=c.qC[d.id].Rb,gvjs_WZ(a,b,d,!1,!1,[gvjs_XZ,gvjs_Dla,c.fill]),0!=d.Rm.length&&(gvjs_WZ(a,b,d,!0,!1,[c.Rm]),gvjs_WZ(a,b,d,!1,!1,[c.border])))}
function gvjs_SZ(a,b){var c=b.HJ;if(c){var d=a.jw,e=a.F,f=c.view.XD,g=f.left+f.width/2,h=f.top+f.height/2,k=f.width/2,l=f.height/2,m=c.Hca.x,n=c.Hca.y,p=new gvjs_3({fill:"808080",fillOpacity:.25}),q=new gvjs_OA;q.move(m,n);q.va(m,n+(h>n?l:-l));q.va(m+(g>m?k:-k),n);q.close();m=e.Ia(q,p,d);gvjs_YZ(a,m,gvjs_oZ,!0);m=new gvjs_3({fill:gvjs_Kx});m=e.Gl(g,h,k,l,m,d);gvjs_YZ(a,m,gvjs_nZ,!0);m=new gvjs_3({stroke:"bfbfbf",strokeWidth:1.5});m=e.Gl(g,h,k,l,m,d);gvjs_YZ(a,m,gvjs_nZ,!0);m=e.Sa();f=e.ZG(m,new gvjs_5(f.left+
3.5,f.top+3.5,f.width-7,f.height-7),!0);e.appendChild(d,f);f=new gvjs_3({stroke:"cccccc",strokeWidth:1.5});d=e.Gl(g,h,k-3.5,l-3.5,f,d);gvjs_YZ(a,d,gvjs_nZ,!0);d=c.view;gvjs_NZ(a,m,b,d.XD,!0);gvjs_OZ(a,m,b,d,!0);gvjs_QZ(a,m,c.FD,!0,b.Hj);a.B0=c.Xo}else a.B0=null}function gvjs_TZ(a,b){0<a.VA.length&&(gvjs_u(a.VA,function(c){this.F.Re(c)},a),a.VA=[]);a.VA=0<b.qu.length?gvjs_v(b.qu,function(c){return c.html?gvjs_EG(c,this.Hi.getContainer()):gvjs_FG(c,this.F,this.Xv).j()},a):[]}
function gvjs_ZZ(a,b){gvjs_w(b.qC,function(c,d){c=c.Rb;gvjs__Z(this,d,gvjs_gZ,c.fill);gvjs__Z(this,d,"disputed",c.Rm);gvjs__Z(this,d,"border",c.border)},a)}function gvjs__Z(a,b,c,d){b=[c,b].join(".");b=a.Fd[b];if(null!=b)for(c=0;c<b.length;++c)a.F.rj(b[c],d)}
function gvjs_Ala(a,b){function c(e){var f=gvjs_Ela(a,e.target);if(f&&f.TO){var g=gvjs_Fla(e.type,f.type),h=f.elementType;f=gvjs_x(f.data);e.type==gvjs_kd?f.Ro=!1:e.type==gvjs_ld&&(f.Ro=!0);f.xb=gvjs_mB(e);a.nc.dispatchEvent({type:g,elementType:h,data:f})}}var d=a.F;d.ic(b,gvjs_jd,c);d.ic(b,gvjs_kd,c);d.ic(b,gvjs_ld,c);d.ic(b,gvjs_St,c)}
function gvjs_Fla(a,b){switch(b){case gvjs_gZ:switch(a){case gvjs_St:return gvjs_hZ;case gvjs_jd:return gvjs_jZ;case gvjs_kd:case gvjs_ld:return gvjs_iZ}case gvjs_pZ:switch(a){case gvjs_St:return gvjs_qZ;case gvjs_jd:return"markerMove";case gvjs_kd:case gvjs_ld:return gvjs_rZ}}return null}function gvjs_YZ(a,b,c,d){gvjs_0Z(a,b,["F",c,"1",d?"1":"0","","0"])}function gvjs_0Z(a,b,c){c=c.join("#");a.F.kp(b,c)}
function gvjs_Ela(a,b){a=a.F.xv(b);if(!a||a==gvjs_xs)return null;a=a.split("#");b=a[1];var c="1"==a[2]?!0:!1,d="1"==a[3]?!0:!1;switch(a[0]){case "F":return{type:gvjs_gZ,elementType:b,TO:c,data:{iJ:d,featureId:a[4]?a[4]:null,gJ:"1"==a[5]?!0:!1}};case "M":return{type:gvjs_pZ,elementType:b,TO:c,data:{iJ:d,Xo:a[4],oj:gvjs_jg(a[5]),hD:"1"==a[6]?!0:!1}};default:return null}}function gvjs_NZ(a,b,c,d,e){b=a.F.yb(d.left,d.top,d.width,d.height,c.xG,b);gvjs_YZ(a,b,"ocean",e)}
function gvjs_OZ(a,b,c,d,e){for(var f=a.F.Sa(),g=0;g<d.features.length;++g){var h=a,k=d.features[g],l=e,m=c.qC[k.id].Rb;gvjs_WZ(h,f,k,!1,l,[m.fill],gvjs_gZ);0!=k.Rm.length&&(gvjs_WZ(h,f,k,!0,l,[m.Rm],"disputed"),gvjs_WZ(h,f,k,!1,l,[m.border],"border"))}a.F.appendChild(b,f)}
function gvjs_WZ(a,b,c,d,e,f,g){var h=d?c.Rm:c.polygons,k=c.id;(g=null!=g?[g,k].join("."):null)&&(a.Fd[g]=a.Fd[g]||[]);for(k=0;k<h.length;++k){var l=h[k],m=new gvjs_OA;gvjs_1Z(m,l.pL,gvjs_tZ);for(var n=0;n<l.SI.length;n++)gvjs_1Z(m,l.SI[n],"reverse");l=m;if(0<l.vc.length)for(m=0;m<f.length;++m)if(n=a.F.Ia(l,f[m],b))gvjs_0Z(a,n,["F",gvjs_gZ,c.TO?"1":"0",e?"1":"0",c.id,d?"1":"0"]),g&&a.Fd[g].push(n)}}
function gvjs_1Z(a,b,c){b=b.points;var d=b.length;if(!(1>=d)){var e=c==gvjs_tZ?0:d-1;d=c==gvjs_tZ?d:-1;c=c==gvjs_tZ?1:-1;for(var f=e;f!=d;f+=c){var g=b[f][0],h=b[f][1];f==e?a.move(g,h):a.va(g,h)}a.close()}}
function gvjs_QZ(a,b,c,d,e){var f=a.F;c=gvjs_Le(c);gvjs_Qe(c,function(m,n){return n.size-m.size});for(var g=0;g<c.length;++g){var h=c[g],k=f.Sa();gvjs_0Z(a,k,["M",gvjs_pZ,"1",d?"1":"0",h.Xo,h.oj,h.hD?"1":"0"]);f.appendChild(b,k);if(a.gb.cY===gvjs_m){var l=new gvjs_hy({bb:e,fontSize:h.size,color:h.brush.fill,opacity:h.brush.fillOpacity,Lb:"",bold:!1,Ue:!1,Nc:!1});f.ce(h.label,h.x,h.y,20,gvjs_0,gvjs_0,l,k)}else f.Ke(h.x,h.y,h.size,h.brush,k);h=[gvjs_pZ,h.Xo].join(".");a.Fd[h]=k.j()}}
function gvjs_Bla(a,b){var c=a.F,d=a.pD.OC;gvjs_u(d,function(e){if(!gvjs_He(b.OC,e)){e=[gvjs_pZ,e].join(".");e=gvjs_lh(this.Fd[e]);for(var f=1;f<e.length;++f)c.Re(e[f])}},a);gvjs_u(b.OC,function(e){if(!gvjs_He(d,e)){e=[gvjs_pZ,e].join(".");e=this.Fd[e];var f=gvjs_mh(e).cloneNode(!0);c.rj(f,gvjs_XZ);e.appendChild(f)}},a)}function gvjs_RZ(a,b){if(b.Vi){b=b.Vi;var c=a.F;a=a.Xu;gvjs_AG(b.aX,c,a);gvjs_BG(b.K0,c,a);gvjs_CG(b.Z4,c,a)}}
gvjs_LZ.prototype.M=function(){gvjs_li(this.nc);0<this.VA.length&&(gvjs_u(this.VA,function(a){this.F.Re(a)},this),this.VA=[]);this.F.clear();gvjs_E(this.pD);this.pD=null;this.mw&&this.F.Re(this.mw.j());this.mw=null;this.Vs&&this.F.Re(this.Vs.j());this.Vs=null;this.Xv&&this.F.Re(this.Xv.j());this.Xv=null;this.Xu&&this.F.Re(this.Xu.j());this.Xu=null;this.jw&&this.F.Re(this.jw.j());this.jw=null;gvjs_F.prototype.M.call(this)};gvjs_LZ.prototype.cw=function(){return this.F.cw()};
var gvjs_XZ=new gvjs_3({strokeWidth:"3",stroke:gvjs_nt,strokeOpacity:"0.2"}),gvjs_Dla=new gvjs_3({strokeWidth:"1",stroke:gvjs_nt,strokeOpacity:"0.1"});function gvjs_2Z(a,b){var c=new gvjs_B(-5,-5,-5,-5);this.af=b.clone().expand(c);a=2*gvjs_vZ(a)/5;this.baa=new gvjs_A(a,a)}function gvjs_Gla(a,b){var c=a.af;a=a.baa;var d=b.x;d+a.width>c.right&&(d=b.x-a.width);var e=b.y-a.height;e<c.top&&(e=b.y);return new gvjs_5(d,e,a.width,a.height)}
gvjs_2Z.prototype.BW=function(a,b,c){var d=b.H0,e=b.XD.Tb();b=parseFloat(a.lat);a=parseFloat(a.lng);a<d.kh[1]?a+=360:a>d.xi[1]&&(a-=360);c=gvjs_vZ(this.baa)/2/c/(e.height/(d.xi[0]-d.kh[0]));return{xi:[b+c,a+c],kh:[b-c,a-c]}};function gvjs_Hla(a,b){var c=gvjs_Ux(a.FD,function(d){return d.oj==b});if(!c)return!1;a=a.view.XD;c=gvjs_9y(new gvjs_z(c.x,c.y),new gvjs_z(a.left+a.width/2,a.top+a.height/2));a=gvjs_vZ(a.Tb())/2;return c<.9*a};function gvjs_3Z(a,b,c,d){this.kg=!a.cw()&&gvjs_K(b,"magnifyingGlass.enable");this.K=c;this.zb=d;this.SB=this.mK=null}gvjs_3Z.prototype.handleEvent=function(a,b){if(!this.kg)return!1;if(gvjs_Ila(this,a)||this.b_(a,b))return!0;b=a.elementType==gvjs_gZ;return a.data.iJ&&b?!0:!1};
gvjs_3Z.prototype.b_=function(a,b){var c=this;if(a.type!=gvjs_rZ)return!1;if(a.data.Ro){if(!a.data.hD)return!1;if(b&&gvjs_Hla(b,a.data.oj))return!0;gvjs_4Z(this);this.mK=setTimeout(function(){c.mK=null;c.K.iw={Xo:a.data.Xo,oj:a.data.oj};gvjs_HK(c.zb,0)},300);return!0}gvjs_4Z(this);return!1};
function gvjs_Ila(a,b){if(!a.K.iw)return!1;switch(b.type){case gvjs_qZ:case gvjs_hZ:return b.data.iJ?a=!1:(gvjs_5Z(a),a=!0),a;case gvjs_rZ:case gvjs_iZ:if(b.data.Ro){var c=b.elementType==gvjs_pZ,d=b.elementType==gvjs_oZ;b.data.iJ&&!d?gvjs_6Z(a):c&&(b.data.hD?gvjs_6Z(a):gvjs_5Z(a))}else null===a.SB&&(c=b.elementType==gvjs_pZ,(b.data.iJ||c)&&gvjs_7Z(a));return!1;case gvjs_jZ:return b.elementType==gvjs_oZ?(gvjs_7Z(a),a=!0):a=!1,a;default:return!1}}
function gvjs_7Z(a){gvjs_6Z(a);a.SB=setTimeout(function(){a.SB=null;gvjs_5Z(a)},500)}function gvjs_5Z(a){a.K.iw=null;gvjs_HK(a.zb,0)}function gvjs_4Z(a){var b=gvjs_Oh().Vj();null!==a.mK&&(b.clearTimeout(a.mK),a.mK=null)}function gvjs_6Z(a){var b=gvjs_Oh().Vj();null!==a.SB&&(b.clearTimeout(a.SB),a.SB=null)};function gvjs_8Z(a){this.m=a||{}}gvjs_o(gvjs_8Z,gvjs_yZ);gvjs_8Z.prototype.fZ=function(){return 1};gvjs_8Z.prototype.project=function(a){return gvjs_v(arguments,function(b){return{x:b[1],y:b[0]}})};function gvjs_Jla(a,b,c,d,e,f){this.m=a;var g=gvjs_vla(a);this.M2=new gvjs_FZ[g.name](g);this.ga=b;this.Pa=c;var h=gvjs_by(gvjs_my(a,gvjs_dt));g=b-h;h=c-h;this.ms=new gvjs_5(Math.round((b-g)/2),Math.round((c-h)/2),g,h);g=this.ms;if(a.Dq("keepAspectRatio")){h=g.width;var k=g.height,l=this.M2.fZ(),m=Math.min(h,Math.round(k*l));l=Math.min(k,Math.round(h/l));g=new gvjs_5(Math.round((h-m)/2)+g.left,Math.round((k-l)/2)+g.top,m,l)}else g=g.clone();this.lw=g;this.Zd=d;this.Z=e;this.gb=f;this.t9=gvjs_Mj(a,
gvjs_wp,Math.round(Math.pow(2*(this.ms.width+this.ms.height),1/3)));this.dta=gvjs_ky(a,["marker.style.stroke.color","marker.style.stroke"],gvjs_vr);this.eta=gvjs_Mj(a,"marker.style.stroke.width",1);this.UX=gvjs_J(a,gvjs_vp);this.rs=gvjs_9Z(this);this.tL=gvjs_$Z(this);d=a.fa(gvjs_nv);this.mra=gvjs_me(d)==gvjs_h;this.$Q=gvjs_J(a,gvjs_qv,gvjs_fZ,gvjs_tla);this.lca=gvjs_jy(a,"legend.bar.length",1/3);this.YQ=gvjs_J(a,"legend.orientation",gvjs_S,gvjs_ola);this.oca=gvjs_ny(a,gvjs_rv,{bb:this.UX,fontSize:this.t9});
this.L1=a.cb("legend.numberFormat");this.Ama=gvjs_ky(a,gvjs_nT,"");this.vO=gvjs_ky(a,gvjs_oT,"");this.C8=gvjs_Kla(this);this.sxa=gvjs_Lla(this);d=gvjs_ny(a,gvjs_lx);e=gvjs_ny(a,gvjs_lx,{bold:!0});this.tF=gvjs_J(a,gvjs_mx,gvjs_tu,gvjs_iC);this.wz=this.tF!=gvjs_f;this.pu={Hd:d,bold:e};d=gvjs_K(a,"tooltip.showDisputedText");this.sya=gvjs_K(a,"tooltip.showTitle");this.qya=d?"%s's administration (under dispute)":"%s";this.U_=gvjs_K(a,gvjs_jx);this.Fma=10;this.V2=this.Nq=this.FF=null;this.U7=gvjs_vr;this.BK=
null;this.cta=gvjs_jy(a,"markerOpacity");this.Zsa=new gvjs_2Z(this.lw.Tb(),new gvjs_B(0,b,c,0))}function gvjs_Mla(a,b){for(var c=0,d=a.FF.length;c<d;c++)for(var e=a.FF[c].RX.features,f=0,g=e.length;f<g;f++){var h=e[f];if(h.id==b)return h}return null}function gvjs_Nla(a,b){var c=gvjs_a_(a,a.Ama),d={};gvjs_u(b.views,function(e){gvjs_u(e.features,function(f){d[f.id]={Rb:c}},this)},a);return d}
function gvjs_b_(a,b){for(var c=new gvjs_DZ,d=1;10>d;d++){var e=(a.xi[1]-a.kh[1])/10*d+a.kh[1],f=(a.xi[0]-a.kh[0])/10*d+a.kh[0];e=b.project([f,a.kh[1]],[f,a.xi[1]],[a.kh[0],e],[a.xi[0],e]);c.track.apply(c,e)}a=c.getBounds("x");c=c.getBounds("y");return{xi:[c.max,a.max],kh:[c.min,a.min]}}
function gvjs_Ola(a,b,c){var d=new gvjs_5(b.jza*a.lw.width+a.lw.left,b.rza*a.lw.height+a.lw.top,b.scale*a.lw.width,b.scale*a.lw.height),e=a.BK[c],f=gvjs_b_(b.Ju,e);return{id:String(c),Ju:f,H0:b.Ju,XD:d,features:gvjs_v(b.features,function(g){return gvjs_c_(a,f,d,e,g)})}}
function gvjs_c_(a,b,c,d,e){for(a=gvjs_Pla(a,gvjs_Nz(gvjs_Kz(e.polygons),gvjs_Kz(e.Rm)));a[1]>b.xi[1];)a[1]-=360;for(;a[1]<b.kh[1];)a[1]+=360;return{id:e.id,center:gvjs_d_(b,c,d,a),polygons:gvjs_v(e.polygons,function(f){return gvjs_e_(b,c,d,f)}),Rm:gvjs_v(e.Rm,function(f){return gvjs_e_(b,c,d,f)}),TO:"__DISPUTED__All"!=e.id}}function gvjs_Pla(a,b){var c=0,d=0,e=0;gvjs_Lz(b,function(f){gvjs_u(f.pL,function(g){c+=g[0];d+=gvjs__y(g[1],360);e++},this)},a);return[c/e,d/e]}
function gvjs_e_(a,b,c,d){return{pL:gvjs_f_(a,b,c,d.pL),SI:gvjs_v(d.SI,function(e){return gvjs_f_(a,b,c,e)})}}function gvjs_f_(a,b,c,d){return{points:gvjs_v(d,function(e){return gvjs_d_(a,b,c,e)})}}function gvjs_d_(a,b,c,d){var e=a.kh;a=a.xi;var f=b.width,g=b.height,h=b.left;b=b.top;c=c.project(d)[0];return[h+f*(c.x-e[1])/(a[1]-e[1]),b+g*(1-(c.y-e[0])/(a[0]-e[0]))]}
function gvjs_Qla(a,b){var c=[];a.Nq=[];for(var d=gvjs_v(a.FF,function(l){return l.RX}),e=0;e<b.length;++e){var f=b[e],g={location:f,XX:{}};if(null!=f){f=gvjs_g_(a,e,f,d);gvjs_Me(c,f);for(var h=0;h<f.length;h++){var k=f[h];g.XX[k.Xo]=k}}a.Nq.push(g)}gvjs_Rla(c);return c}function gvjs_Rla(a){for(var b=0;b<a.length;b++){for(var c=a[b],d=new gvjs_z(c.x,c.y),e=0,f=0;f<a.length;f++)if(b!=f){var g=a[f],h=gvjs_9y(d,new gvjs_z(g.x,g.y));h<c.size+g.size&&(e+=c.size+g.size-h)}c.hD=e>c.size}}
function gvjs_g_(a,b,c,d){var e=a.sxa(b),f=a.C8(b);if(null==f)return[];f=new gvjs_3({stroke:a.dta,strokeWidth:a.eta,fill:f,fillOpacity:a.cta});var g=parseFloat(c.lat),h=[];c=parseFloat(c.lng);c=[c,c+360,c-360];for(var k=0;k<d.length;++k){var l=d[k],m=a.BK[k],n=l.H0;if(!(g<n.kh[0]||g>n.xi[0])){for(var p=0;p<c.length;++p){var q=c[p];if(!(q<n.kh[1]||q>n.xi[1])){q=gvjs_d_(l.Ju,l.XD,m,[g,q]);var r=String(b+"-"+l.id+"-"+p),t=gvjs_pZ;if(null!=a.gb.FJ&&0<=a.gb.FJ)t=a.Z.Ha(b,a.gb.FJ);else if(null!=a.gb.fG&&
0<=a.gb.fG)t=a.Z.Ha(b,a.gb.fG);else if(null!=a.gb.KK&&0<=a.gb.KK)t=a.Z.Ha(b,a.gb.KK);else if(null!=a.gb.sD&&null!=a.gb.yD&&0<=a.gb.sD&&0<=a.gb.yD){t=a.Z.getValue(b,a.gb.sD);var u=a.Z.getValue(b,a.gb.yD);t=gvjs_h_(t,"S","N")+" "+gvjs_h_(u,"W","E")}h.push({Xo:r,label:t,oj:b,x:q[0],y:q[1],size:e,brush:f,hD:!1})}}if(0<h.length)break}}return h}
function gvjs_Sla(a,b,c){var d=a.Nq,e=d[c],f=e.XX[b];if(!f.hD)return null;var g=Number(b.split("-")[1]),h=a.FF[g],k=a.BK[g],l=gvjs_L(a.m,"magnifyingGlass.zoomFactor"),m=a.Zsa,n=m.BW(e.location,h.RX,l);e=new gvjs_z(f.x,f.y);var p=gvjs_Gla(m,e);k=gvjs_b_(n,k);var q=new gvjs_8Z;c={id:g+"-"+c+"-mag",Ju:k,H0:n,XD:p,features:gvjs_v(h.features,function(r){return gvjs_c_(a,n,p,q,r)})};g=[];for(h=0;h<d.length;h++)k=d[h].location,null!=k&&gvjs_Me(g,gvjs_g_(a,h,k,[c]));return{Xo:b,Hca:e,view:c,FD:g}}
function gvjs_i_(a,b){if(!a.mra||null==a.rs||!a.rs.pl)return null;var c=a.oca.fontSize,d=a.ms.width,e=a.ms.height,f={top:0,left:0,width:a.YQ==gvjs_S?d*a.lca:e*a.lca,height:1.5*c,orientation:a.YQ,ja:a.oca,Fca:gvjs_nt,numberFormat:a.L1};f.top=a.$Q===gvjs_uZ||"top_right"===a.$Q?3*c:a.YQ===gvjs_U?e-c-f.width:e-c-f.height;f.left=a.$Q===gvjs_uZ||a.$Q===gvjs_fZ?.5*c:a.YQ==gvjs_U?d-c-f.height:d-c-f.width;f.left+=a.ms.left;f.top+=a.ms.top;return gvjs_XH(a.rs,f,b,a.Zd)}
function gvjs_j_(a,b){for(var c=null,d=0;d<a.Z.ca();++d){var e=a.Z.getValue(d,b);c=gvjs_4B(c,e)}return c}function gvjs_Kla(a){var b=a.gb.Yu;return null!=b?function(c){c=a.Z.getValue(c,b);return null!=c?gvjs_TH(a.rs,c):a.vO}:function(){return a.vO}}function gvjs_Lla(a){var b=a.gb.XE;return null!=b?function(c){c=a.Z.getValue(c,b);return gvjs_II(a.tL,c)}:function(){return a.Fma}}function gvjs_9Z(a){var b=a.gb.Yu;if(null==b)return null;b=gvjs_j_(a,b);return gvjs_WH(a.m,b)}
function gvjs_$Z(a){var b=a.gb.XE;b=null!=b?gvjs_j_(a,b):null;return gvjs_JI(a.m,b)}
function gvjs_Tla(a,b){var c={NC:[],OC:[]};null!=b.ff&&(c.NC=[b.ff]);null!=b.iI&&(c.OC=[b.iI]);c.qu=[];var d=a.wz&&(a.tF===gvjs_qt||a.tF===gvjs_Fw);gvjs_u(gvjs_9n(b.selection),function(h){var k=gvjs_k_(this,h,!1),l=this.Zd,m=this.pu.Hd.fontSize,n=new gvjs_B(0,this.ga-1,this.Pa-1,0),p=this.Nq[h];h=(h=this.V2[h])&&gvjs_Mla(this,h);var q=null,r=null;h?(c.NC.push(h.id),d&&(q=r=new gvjs_z(h.center[0],h.center[1]),c.qu.push(gvjs_gG(k,l,!1,r,n,q,void 0,this.U_)))):p&&gvjs_w(p.XX,function(t,u){c.OC.push(u);
d&&c.qu.push(gvjs_gG(k,l,!1,new gvjs_z(t.x-m,t.y-m),n,new gvjs_z(t.x,t.y),void 0,this.U_))},this)},a);if(null!=b.Nj){if(a.wz&&(a.tF===gvjs_qt||a.tF===gvjs_tu)){var e=gvjs_k_(a,b.Nj.oj,b.Nj.gJ),f=a.pu.Hd.fontSize,g=new gvjs_z(b.Nj.origin.x,b.Nj.origin.y);c.qu.push(gvjs_gG(e,a.Zd,!1,new gvjs_z(g.x-f,g.y-f),new gvjs_B(0,a.ga-1,a.Pa-1,0),g,void 0,a.U_))}null!=a.gb.Yu&&(e={value:a.Z.getValue(b.Nj.oj,a.gb.Yu)},c.Vi=gvjs_i_(a,[e]))}null!=b.iw&&(c.HJ=gvjs_Sla(a,b.iw.Xo,b.iw.oj));return c}
function gvjs_h_(a,b,c){b=0<=a?c:b;a=Math.abs(a);c=Math.floor(a);a=60*(a-c);var d=Math.floor(a);return c+"\u00b0"+d+"'"+Math.round(60*(a-d))+'"'+b}
function gvjs_k_(a,b,c){var d=a.gb,e=a.Z,f={entries:[]};if(null!=d.FJ)var g=e.Ha(b,d.FJ);else switch(d.NV){case gvjs_9c:c=e.getValue(b,d.sD);g=e.getValue(b,d.yD);g=gvjs_h_(c,"S","N")+" "+gvjs_h_(g,"W","E");break;case gvjs_xd:g=e.Ha(b,d.KK);c&&(g=gvjs_JB(a.qya,g));break;case "address":g=e.Ha(b,d.fG);break;default:g=""}a.sya&&(c=gvjs_dG(g,a.pu.bold),f.entries.push(c));c=null!=d.q5?e.getStringValue(b,d.q5):null;if(null!=c)if(d=d.q5,e.Bd(d,gvjs_7u)||e.getProperty(b,d,gvjs_7u))f.entries.push(gvjs_dG(c,
a.pu.Hd,void 0,void 0,void 0,void 0,void 0,!0));else for(b=c.split("\n"),e=0;e<b.length;e++)d=gvjs_dG(b[e],a.pu.Hd),f.entries.push(d);else null!=d.Yu&&(c=e.Ga(d.Yu),g=e.Ha(b,d.Yu),c=gvjs_dG(g,a.pu.bold,c,a.pu.Hd),f.entries.push(c)),null!=d.XE&&d.XE!=d.Yu&&(c=e.Ga(d.XE),b=e.Ha(b,d.XE),a=gvjs_dG(b,a.pu.bold,c,a.pu.Hd),f.entries.push(a));return f}
function gvjs_a_(a,b){var c=b===gvjs_f?[255,255,255]:gvjs_tj(b);c=gvjs_sj(gvjs_Yz(c,.1));return{fill:new gvjs_3({stroke:c,fill:b}),Rm:new gvjs_3({stroke:gvjs_f,pattern:new gvjs_6x(gvjs_nw,b,b==a.U7?gvjs_yr:a.U7)}),border:new gvjs_3({stroke:c})}};function gvjs_l_(a,b,c,d,e,f,g,h,k){gvjs_F.call(this);var l=this;this.cm=a;this.m=b;this.ga=c;this.Pa=d;this.gb=f;this.K=g;this.Vm=null;this.S2=!1;this.wva=h;this.Xm=k;this.P4=!1;this.ZX=null;this.d7=!1;this.zb=new gvjs_GK(function(){return l.Qt()});this.CD=new gvjs_5F(3);this.xO=[!1,!1,!1];this.BD=new gvjs_Jla(this.m,this.ga,this.Pa,this.cm.me,e,this.gb);this.vca=new gvjs_3Z(a,b,g,this.zb);this.W9=gvjs_K(b,"enableRegionInteractivity",f.cY==gvjs_yd);this.S9=gvjs_K(b,"enableMarkerInteractivity",f.cY==
gvjs_bd);this.W2()}gvjs_o(gvjs_l_,gvjs_F);gvjs_=gvjs_l_.prototype;
gvjs_.Y3=function(a,b){var c=this.BD,d=c.m;c.FF=[];c.BK=[];for(var e=[],f=0,g=a.views.length;f<g;f++){var h=a.views[f],k=c.M2.Zc();k.boundingBox={lo:h.Ju.kh,hi:h.Ju.xi};k=new c.M2.constructor(k);c.BK.push(k);k=gvjs_Ola(c,h,f);e.push(k);c.FF.push({features:h.features,RX:k})}a={width:c.ga,height:c.Pa,bta:c.lw,FE:gvjs_J(d,gvjs_Gw,gvjs_Sw,gvjs_hC),CEa:c.tF,xG:gvjs_my(d,gvjs_dt),haa:d.mz(gvjs_Mu),title:{text:gvjs_J(d,gvjs_bx),ja:gvjs_ny(d,gvjs_ex,{bb:c.UX,fontSize:c.t9}),lines:[],align:gvjs_2,tooltip:""},
views:e,qC:gvjs_Nla(c,a),NC:[],OC:[],FD:[],Vi:null,HJ:null,Hj:c.UX};this.nL(0,a);this.P4=!0;this.Xm("mapLoaded",b);null!=this.ZX?this.ZX():this.Qt()};
function gvjs_Ula(a,b,c,d,e,f){function g(){a.d7=d;if(null!=e){a.Vm=null;var h=a.BD;h.Z=e;h.rs=gvjs_9Z(h);h.tL=gvjs_$Z(h)}null!=f&&(a.K=f,a.vca.K=f);h=a.BD;h.V2=[];for(var k={},l=0;l<h.Z.ca();++l){var m=b[l];h.V2.push(m);if(null!=m){var n=h.C8(l);null!=n&&(k[m]={oj:l,Rb:gvjs_a_(h,n)})}}h={qC:k,FD:gvjs_Qla(h,c),Vi:gvjs_i_(h,[])};a.nL(1,h);a.Qt()}a.S2=!1;a.P4?g():a.ZX=g}gvjs_.setSelection=function(a){this.K.selection.setSelection(a);gvjs_HK(this.zb,1)};gvjs_.getSelection=function(){return this.K.selection.getSelection()};
gvjs_.Qt=function(){if(this.P4){if(null==this.Vm||!this.Vm.equals(this.K)){var a=gvjs_Tla(this.BD,this.K);this.nL(2,a)}a=this.CD.compact();if(this.xO[0])gvjs_MZ(this.cm,a);else if(this.xO[1]){var b=this.cm;gvjs_ZZ(b,a);gvjs_VZ(b,a);gvjs_UZ(b,a,!0)}else gvjs_UZ(this.cm,a);this.xO=[!1,!1,!1];this.Vm=this.K.clone();!this.S2&&this.d7&&(this.wva(),this.S2=!0)}};function gvjs_m_(a,b){null!=a.K.Nj&&b.data.xb&&(a.K.Nj.origin={x:b.data.xb.x,y:b.data.xb.y},gvjs_HK(a.zb,3))}
gvjs_.et=function(a,b){a=this.CD.compact().FE==gvjs_Sw;null!=b?(gvjs_py(this.K.selection,b,a),this.Xm(gvjs_k,{})):(b=0<this.K.selection.getSelection().length,this.K.selection.clear(),b&&this.Xm(gvjs_k,{}));this.zb&&gvjs_HK(this.zb,50)};function gvjs_n_(a,b){var c=a.CD.compact();return a.vca.handleEvent(b,c?c.HJ:null)}
gvjs_.W2=function(){var a=this;this.cm.o(gvjs_hZ,function(b){if(!gvjs_n_(a,b)&&a.W9){var c=b.data.featureId;null!==c&&a.Xm("regionClick",{region:c});c=gvjs_o_(a,c);a.et(b,c)}});this.cm.o(gvjs_iZ,function(b){if(!gvjs_n_(a,b)&&a.W9){var c=b.data.featureId;null!==c&&(b.data.Ro?(a.K.ff=c,c=gvjs_o_(a,c),a.K.Nj=null!=c?{oj:c,gJ:b.data.gJ,origin:{x:b.data.xb.x,y:b.data.xb.y}}:null):(a.K.ff=null,a.K.Nj=null),gvjs_HK(a.zb,50))}});this.cm.o(gvjs_jZ,function(b){gvjs_n_(a,b)||gvjs_m_(a,b)});this.cm.o(gvjs_qZ,
function(b){gvjs_n_(a,b)||a.S9&&a.et(b,b.data.oj)});this.cm.o(gvjs_rZ,function(b){!gvjs_n_(a,b)&&a.S9&&(b.data.Ro?(a.K.iI=b.data.Xo,a.K.Nj={oj:b.data.oj,gJ:!1,origin:{x:b.data.xb.x,y:b.data.xb.y}}):(a.K.iI=null,a.K.Nj=null),gvjs_HK(a.zb,50))});this.cm.o("markerMove",function(b){gvjs_m_(a,b)})};function gvjs_o_(a,b){if(null===b)return null;a=a.CD.compact();return a.qC[b]?a.qC[b].oj:null}gvjs_.nL=function(a,b){gvjs_6F(this.CD,a,b);this.xO[a]=!0};
gvjs_.M=function(){gvjs_E(this.zb);this.zb=null;gvjs_E(this.cm);this.cm=null;gvjs_E(this.BD);this.BD=null;gvjs_F.prototype.M.call(this)};var gvjs_p_={},gvjs_q_={},gvjs_r_=null,gvjs_s_=null;function gvjs_Vla(a,b,c){""!==a&&(gvjs_s_=a=a.replace(/\/$/,""));gvjs_t_("info","mapList",function(d){gvjs_u_=d;b()},c)}function gvjs_v_(a){gvjs_s_="https://www.gstatic.com/charts/geochart/"+a}gvjs_v_("10");function gvjs_t_(a,b,c,d){gvjs_cn(gvjs_s_+"/"+a+"/"+(b+".js")).then(function(e){e=e.replace(/^[\s\S]*google_visualization_geochart_[^=]*\s*=\s*/g,"");e=e.replace(/;[\s]*$/g,"");e=JSON.parse(e);c&&c(e);return e},function(e){d&&d(e)})}
function gvjs_Wla(a,b){if(null==b)throw Error("Callback is null or undefined");var c=gvjs_w_(a),d=gvjs_Xla(a);if(void 0!==gvjs_q_[d])setTimeout(function(){return b(gvjs_q_[d])},0);else if(void 0!==gvjs_p_[d])gvjs_p_[d].push(b);else{gvjs_p_[d]=[b];var e=function(f){for(;gvjs_p_[d]&&0<gvjs_p_[d].length;)gvjs_p_[d].shift()(f)};gvjs_t_("mapfiles",c,function(f){f={views:gvjs_v(f.views,gvjs_Yla)};gvjs_q_[d]=f;e(f)},function(){e(null)})}}
function gvjs_Zla(a){var b=null[gvjs_s_];null!=b?a(b):gvjs_t_("info","boundingBoxes",function(c){b=gvjs_v(c,gvjs__la);a(b)},function(){a(null)})}function gvjs_w_(a){var b="";"COM"!=a.domain&&(b=a.domain+"_");return""+b+a.region+"_"+gvjs_x_(a.resolution)}function gvjs_Xla(a){a=gvjs_w_(a);return gvjs_s_+":"+a}function gvjs_x_(a){null==gvjs_r_&&(gvjs_r_={continents:"REGIONS",subcontinents:"SUBREGIONS",countries:gvjs_iT,provinces:"PROVINCES",metros:"METROS"});return gvjs_r_[a]}var gvjs_u_=null;
function gvjs_y_(a){if(!gvjs_u_)return!1;var b=a.domain,c=a.region;a=gvjs_x_(a.resolution);if(b=gvjs_u_[b])if(b=b[a])return 0<=gvjs_Ey(b,c);return!1}
function gvjs_Yla(a){for(var b=gvjs_v(a.features,gvjs_0la),c={},d=[],e=0;e<b.length;e++){var f=b[e],g=f.id;gvjs_hf(g,"__DISPUTED__")?c[g]=f:d.push(f)}for(b=0;b<d.length;b++)e=d[b],f=c["__DISPUTED__"+e.id],e.Rm=f?f.polygons:[];if(c=c.__DISPUTED__All)c.Rm=c.polygons,d.push(c);return{features:d,Ju:gvjs_z_(a.boundingBox),jza:a.xoffset,rza:a.yoffset,scale:a.scale}}function gvjs_0la(a){return{id:a.id,polygons:gvjs_v(a.polygons,gvjs_1la),Rm:[]}}
function gvjs_1la(a){return gvjs_ne(a)?{pL:gvjs_A_(a),SI:[]}:{pL:gvjs_A_(a.shell),SI:gvjs_v(a.holes,gvjs_A_)}}function gvjs_A_(a){return gvjs_v(a,function(b){return[gvjs_CZ(b[0]),parseFloat(b[1])]})}function gvjs_z_(a){return{xi:[gvjs_CZ(a.hi[0]),parseFloat(a.hi[1])],kh:[gvjs_CZ(a.lo[0]),parseFloat(a.lo[1])]}}function gvjs__la(a){return{region:a.region,resolution:a.resolution,domain:a.domain,Wka:gvjs_v(a.boundingBoxes,gvjs_z_)}};function gvjs_B_(a,b,c,d){var e=gvjs_J(c,gvjs_tT);if(e!=gvjs_ub)d(gvjs_C_(e,c));else if(b.NV!=gvjs_9c)d(gvjs_C_(gvjs_yT,c));else{var f=c.cb(gvjs_uT,gvjs_xZ),g=c.cb(gvjs_iu),h=[];for(e=0;e<a.ca();++e)h.push({lat:a.getValue(e,b.sD),lng:a.getValue(e,b.yD)});gvjs_Zla(function(k){if(k){a:{for(var l=0;l<k.length;++l){var m=k[l];if(null==f||m.resolution==f)if(null==g||m.domain==g){for(var n=!0,p=0;p<h.length;++p){for(var q=h[p],r=!1,t=m.Wka,u=0;u<t.length;++u)if(gvjs_2la(q,t[u])){r=!0;break}if(!r){n=!1;
break}}if(n){k={region:m.region,resolution:m.resolution,domain:m.domain};break a}}}k=null}null!=k?d(k):d(gvjs_C_(gvjs_yT,c))}else d(null)})}}function gvjs_C_(a,b){var c=gvjs_J(b,gvjs_uT,gvjs_mT,gvjs_xZ);b=gvjs_J(b,gvjs_iu);a={region:a,resolution:c,domain:b};return gvjs_y_(a)||"COM"!=a.domain&&(a.domain="COM",gvjs_y_(a))?a:null}function gvjs_2la(a,b){return a.lat>b.kh[0]&&a.lat<b.xi[0]&&gvjs_Fe([-360,0,360],function(c){return a.lng+c>b.kh[1]&&a.lng+c<b.xi[1]})};var gvjs_3la=gvjs_D.removeAll;function gvjs_D_(a){gvjs_Nn.call(this,a);this.Ak=this.ab=null;this.Hz=new gvjs_HZ(this.Hg);this.j0="";this.eb=this.Bk=null}gvjs_o(gvjs_D_,gvjs_Nn);function gvjs_4la(a){null==a&&(a={});a=new gvjs_yj([a,gvjs_GZ]);var b=gvjs_J(a,gvjs_tT);return null!=gvjs_C_(b,a)}function gvjs_E_(a,b,c){a=a||"";var d=gvjs_F_&&a===gvjs_G_;gvjs_G_=a;b?d?b():gvjs_Vla(a,function(){gvjs_F_=!0;b()},c):gvjs_F_=!1}gvjs_=gvjs_D_.prototype;
gvjs_.Rd=function(a,b,c,d){var e=this;c=void 0===c?{}:c;gvjs_3la(this.container);this.Bk=a;gvjs_E(this.Hz);this.Hz=new gvjs_HZ(this.Hg);c=gvjs_Li(gvjs_Ii(c));a=[c];var f=c.theme||[];Array.isArray(f)||(f=[f]);for(var g=0;g<f.length;++g){var h=void 0;if(typeof f[g]===gvjs_l)h=gvjs_0F(f[g]);else if(gvjs_r(f[g]))h=f[g];else throw Error("Theme should be a theme name or an options object.");a.push(h)}a.push(gvjs_GZ);var k=gvjs_3K(),l=[];gvjs_u(a,function(t){l.push.apply(l,gvjs_Rz(t,k))});var m=new gvjs_yj(a),
n=new gvjs_wZ(d);this.eb=this.Bv(this.container,m);d=gvjs_J(m,"displayMode",gvjs_ub,gvjs_nla);var p=(new gvjs_Ql).Ac(b,d,this.Hg);if(null!=p){var q=gvjs_Bi({options:c,format:p,size:this.eb}),r=this.Bk(function(t){if(null==t)throw Error(gvjs_dZ);gvjs_5la(this,b,p,m,q,n,t)},this);c=gvjs_G_;c=gvjs_J(m,"mapsSource",c);""===c&&(d=gvjs_J(m,"geochartVersion","10"),gvjs_v_(d));d=gvjs_J(m,"regioncoderVersion","0");gvjs_LT(d);gvjs_E_(c,function(){l.length&&e.Lh?(e.Lh.promise.then(function(){gvjs_B_(b,p,m,r)},
null,e),gvjs_oy(e,function(){gvjs_B_(b,p,m,r)}),new gvjs_2K(l,e.Lh)):gvjs_B_(b,p,m,r)})}};gvjs_.ah=function(){if(!this.Ak)throw Error("Must draw chart before calling getImageURI.");var a=gvjs_3g(this.container).createElement(gvjs_Ob),b=gvjs_YB(a,this.eb),c=new gvjs_IB(a),d=new gvjs_nB(a,b);b=this.Ak;c=new gvjs_LZ(c,d,b.cm.gb);b=b.CD.compact();gvjs_MZ(c,b);gvjs_ZZ(c,b);gvjs_VZ(c,b);gvjs_UZ(c,b,!0);gvjs_UZ(c,b);return a.childNodes[0].toDataURL(gvjs_8u)};
gvjs_.Bv=function(a,b){a=this.La(b,-1);b=this.getHeight(b,-1);-1==a&&-1==b?(a=556,b=347):-1==a?a=Math.round(556*b/347):-1==b&&(b=Math.round(347*a/556));return new gvjs_A(a,b)};function gvjs_5la(a,b,c,d,e,f,g){var h=gvjs_K(d,"showGeocodeWarnings");if(a.j0==e)gvjs_6la(a,!1,d,b,c,g,h,f,e);else{if(null!=a.ab)a.ab.update(a.eb,a.Bk);else{var k=gvjs_K(d,gvjs_Au);a.ab=new gvjs__B(a.container,a.eb,a.Bk,k)}a.ab.rl(function(){var l=a.ab.Oa(),m=a.ab.yq();gvjs_7la(a,b,c,d,e,f,g,h,m,l)},a.Bk)}}
function gvjs_7la(a,b,c,d,e,f,g,h,k,l){k=new gvjs_LZ(k,l,c);null!=a.Ak&&gvjs_E(a.Ak);l=a.eb;gvjs_E(a.Ak);a.Ak=new gvjs_l_(k,d,l.width,l.height,b,c,f,function(){gvjs_I(a,gvjs_i,{})},function(m,n){gvjs_I(a,m,n)});gvjs_6la(a,!0,d,b,c,g,h,f,e)}
function gvjs_6la(a,b,c,d,e,f,g,h,k){function l(){gvjs_wla(a.Hz,d,e,f,g,n)}c=gvjs_J(c,"geocodingContext",gvjs_tT,gvjs_ula);var m="bounds"===c||c===gvjs_qt,n=a.Bk(function(p,q,r){gvjs_Ula(a.Ak,p,q,r,d,h)});a.Hz.nI=c;b&&(a.Hz.aF=null,gvjs_Wla(f,a.Bk(function(p){null!=p?(a.Ak.Y3(p,f),m&&(a.Hz.Y3(p),l()),a.j0=k):a.Hg.Sc(gvjs_dZ)})));m||(a.Hz.aF=null,l())}gvjs_.setSelection=function(a){null!=this.Ak?this.Ak.setSelection(a):this.Hg.Sc(gvjs_eZ)};
gvjs_.getSelection=function(){if(null!=this.Ak)return this.Ak.getSelection();this.Hg.Sc(gvjs_eZ);return[]};gvjs_.He=function(){this.j0="";gvjs_E(this.Ak);this.Ak=null;gvjs_E(this.ab);this.ab=null};var gvjs_G_="",gvjs_F_=!1;gvjs_q(gvjs_nc,gvjs_D_,void 0);gvjs_D_.prototype.draw=gvjs_D_.prototype.draw;gvjs_D_.prototype.getImageURI=gvjs_D_.prototype.ah;gvjs_D_.prototype.setSelection=gvjs_D_.prototype.setSelection;gvjs_D_.prototype.getSelection=gvjs_D_.prototype.getSelection;
gvjs_D_.prototype.clearChart=gvjs_D_.prototype.Jb;gvjs_q(gvjs_kZ,gvjs_4la,void 0);gvjs_q(gvjs_lZ,gvjs_E_,void 0);gvjs_q(gvjs_nc,gvjs_D_,void 0);gvjs_D_.prototype.draw=gvjs_D_.prototype.draw;gvjs_D_.prototype.getImageURI=gvjs_D_.prototype.ah;gvjs_D_.prototype.setSelection=gvjs_D_.prototype.setSelection;gvjs_D_.prototype.getSelection=gvjs_D_.prototype.getSelection;gvjs_D_.prototype.clearChart=gvjs_D_.prototype.Jb;gvjs_q(gvjs_kZ,gvjs_4la,void 0);gvjs_q(gvjs_lZ,gvjs_E_,void 0);
