var gvjs_iT="COUNTRIES",gvjs_jT="Data has no columns.",gvjs_kT="Geocoding failed for all data points",gvjs_lT="The columns type does not match the supported data format. See documentation for supported formats.",gvjs_mT="countries",gvjs_nT="datalessRegionColor",gvjs_oT="defaultColor",gvjs_pT="enableScrollWheel",gvjs_qT="hybrid",gvjs_rT="mapType",gvjs_sT="provinces",gvjs_tT="region",gvjs_uT="resolution",gvjs_vT="showLine",gvjs_wT="useLargeControl",gvjs_xT="useMapTypeControl",gvjs_yT="world";
function gvjs_zT(a,b,c){if(gvjs_r(b)&&(b=gvjs_0e(b),b.bounds)){var d=b.bounds;b.bounds=new google.maps.LatLngBounds(new google.maps.LatLng(d.lo.lat,d.lo.lng),new google.maps.LatLng(d.hi.lat,d.hi.lng))}a.yC.geocode(b,c)}function gvjs_AT(a,b,c){var d=gvjs_Hi(b),e=a.Fw.get(d);null!=e&&gvjs_u(e,function(f){f.MG||f.finish(b,c)});a.yx.delete(d);a.Fw.delete(d)}
gvjs_xl.prototype.FI=gvjs_V(23,function(a,b,c){var d=0;if(c===google.maps.GeocoderStatus.OVER_QUERY_LIMIT)d=520;else if(c===google.maps.GeocoderStatus.OK){var e=gvjs_Hi(a);if(!b||!c)throw Error("There must be a response and status here.");b={response:b,status:c};this.cache[e]=b;gvjs_AT(this,a,b)}else gvjs_AT(this,a,{response:null,status:c});gvjs_ml(this.eZ.bind(this),d,this)});
gvjs_xl.prototype.eZ=gvjs_V(22,function(){if(0!==this.cE.Cd()||0!==this.yx.size){var a=0<this.yx.size?gvjs_Gi(this.yx.values().next().value):this.cE.peek(),b=gvjs_Hi(a);if(b in this.cache){this.Fw.get(b);var c=this.cache[b];gvjs_Qx(this.cE);this.FI(a,c.response,c.status);this.Fw.delete(b)}else 0===this.yx.size&&0<this.cE.Cd()?(gvjs_Qx(this.cE),c=this.Fw.get(b),gvjs_Ge(c,function(d){return d.MG})?this.FI(a,null,null):(this.yx.add(b),gvjs_zT(this,a,this.FI.bind(this,a)))):0<this.yx.size&&gvjs_zT(this,
a,this.FI.bind(this,a))}});gvjs_ol.prototype.BN=gvjs_V(21,function(a){this.Wp();gvjs_ql(this,!0,a)});function gvjs_cja(a,b){gvjs_u(b.St,function(c){var d=gvjs_Hi(c);d in a.cache?b.finish(c,a.cache[d]):(a.Fw.has(d)||(a.cE.enqueue(c),a.Fw.set(d,[])),a.Fw.get(d).push(b))});a.eZ()}function gvjs_dja(a){var b=gvjs_8f(gvjs_Ed,a.ownerDocument&&a.ownerDocument.defaultView);b&&a.setAttribute(gvjs_qd,b)}
function gvjs_eja(a){var b=(a||document).getElementsByTagName("HEAD");return b&&0!==b.length?b[0]:a.documentElement}function gvjs_BT(a,b,c){null!=c&&gvjs_p.clearTimeout(c);a.onload=gvjs_ke;a.onerror=gvjs_ke;a.onreadystatechange=gvjs_ke;b&&window.setTimeout(function(){gvjs_kh(a)},0)}function gvjs_qba(){if(this&&this.pfa){var a=this.pfa;a&&"SCRIPT"==a.tagName&&gvjs_BT(a,!0,this.zg)}}function gvjs_CT(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);gvjs_ve.call(this,c);this.code=a}
gvjs_t(gvjs_CT,gvjs_ve);
function gvjs_fja(a){var b={timeout:3E4,attributes:{async:!1,defer:!1}},c=b.document||document,d=gvjs_ef(a),e=(new gvjs_4g(c)).createElement("SCRIPT"),f={pfa:e,zg:void 0},g=new gvjs_ol(f),h=null,k=null!=b.timeout?b.timeout:5E3;0<k&&(h=window.setTimeout(function(){gvjs_BT(e,!0);var l=new gvjs_CT(1,"Timeout reached for loading script "+d);g.Wp();gvjs_ql(g,!1,l)},k),f.zg=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&e.readyState!=gvjs_Hb||(gvjs_BT(e,b.tCa||!1,h),g.BN(null))};
e.onerror=function(){gvjs_BT(e,!0,h);var l=new gvjs_CT(0,"Error while loading script "+d);g.Wp();gvjs_ql(g,!1,l)};f=b.attributes||{};gvjs_2e(f,{type:"text/javascript",charset:"UTF-8"});gvjs_8g(e,f);e.src=gvjs_ff(a);gvjs_dja(e);gvjs_eja(c).appendChild(e);return g}function gvjs_gja(a){var b=b||{};a=gvjs_Ry(gvjs_rba,a,b);var c=gvjs_fja(a);return new Promise(function(d){gvjs_tl(c,d,null,void 0)})}var gvjs_DT=[];function gvjs_ET(){return!!gvjs_je("google.maps.DirectionsService")}
function gvjs_FT(a,b){function c(){if(gvjs_ET()){var d=gvjs_DT;gvjs_DT=[];gvjs_u(d,function(e){e()})}else throw Error("Error: cannot load Maps API.");}gvjs_ET()?a():(gvjs_DT.push(a),1===gvjs_DT.length&&(b=b||gvjs_je("google.visualization.mapsApiKey"),""===b?a({Uma:!0}):gvjs_gja({key:typeof b===gvjs_l?b:""}).then(c)))}function gvjs_GT(a,b,c){this.BN=b;this.TK=0;this.MG=!1;this.St=a||[];this.MS=new Map;this.Oka=c||this.St.length}gvjs_GT.prototype.cancel=function(){this.MG=!0};
gvjs_GT.prototype.finish=function(a,b){a=gvjs_Hi(a);this.MS.has(a)||this.MS.set(a,b);b=[];if(!this.MG){a=this.St.length;for(var c=this.TK;c<a;c++){var d=gvjs_Hi(this.St[c]);if(!this.MS.has(d))break;d=this.MS.get(d);null!=d&&(d=d.response);b.push(d)}b.length<this.Oka&&this.TK+b.length<a||(this.TK+=b.length,this.BN(b),this.TK>=this.St.length&&this.cancel())}};function gvjs_HT(){this.St=[];this.yC=null}gvjs_HT.prototype.add=function(a){this.St.push(a)};
gvjs_HT.prototype.create=function(a,b,c,d){var e=this;null!=this.yC?(d=new gvjs_GT(a,b,c),this.add(d),gvjs_cja(this.yC,d)):gvjs_FT(function(f){f=void 0===f?{}:f;f&&f.Uma||(null==e.yC&&(e.yC=gvjs_xl.Lc()),e.create(a,b,c))},d)};gvjs_HT.prototype.cancel=function(){gvjs_u(this.St,function(a){a.cancel()});this.St=[]};var gvjs_IT={},gvjs_JT="https://www.gstatic.com/charts/regioncoder/0/";function gvjs_KT(a){this.Rma=a}
function gvjs_LT(a){gvjs_MT=a;gvjs_JT="https://www.gstatic.com/charts/regioncoder/"+a+"/"}function gvjs_NT(a,b){a=gvjs_kf(a.toLowerCase());a=encodeURIComponent(String(a));var c=gvjs_IT[a];null==c?(c=[b],gvjs_IT[a]=c,gvjs_hja(a,function(d){gvjs_OT(a,d)},function(){gvjs_OT(a,null)})):Array.isArray(c)?gvjs_Cy(c,b):gvjs_ml(gvjs_re(b,c),0)}
function gvjs_hja(a,b,c){gvjs_cn(gvjs_JT+"/geocodes/"+(a+".js")).then(function(d){d=d.replace(/^[\s\S]*var results\s*=\s*/g,"");d=d.replace(/;\s*gviz\.util\.RegionCoder\.dictionaryReady[\s\S]*$/g,"");d=JSON.parse(d);b&&b(d);return d},function(d){c&&c(d)})}function gvjs_OT(a,b){var c=gvjs_IT[a];if(b){if(b=new gvjs_KT(b),Array.isArray(c))for(gvjs_IT[a]=b,a=0;a<c.length;a++)c[a](b)}else if(Array.isArray(c))for(gvjs_IT[a]=null,a=0;a<c.length;a++)c[a](null)}
function gvjs_PT(a,b){b=gvjs_kf(b.toLowerCase());return a.Rma[b]}gvjs_KT.dictionaryReady=gvjs_OT;var gvjs_MT="0";gvjs_LT(gvjs_MT);gvjs_q("gviz.util.RegionCoder.dictionaryReady",gvjs_OT,void 0);
