var gvjs_kT="COUNTRIES",gvjs_lT="Data has no columns.",gvjs_mT="Geocoding failed for all data points",gvjs_nT="The columns type does not match the supported data format. See documentation for supported formats.",gvjs_oT="countries",gvjs_pT="datalessRegionColor",gvjs_qT="defaultColor",gvjs_rT="enableScrollWheel",gvjs_sT="hybrid",gvjs_tT="mapType",gvjs_uT="provinces",gvjs_vT="region",gvjs_wT="resolution",gvjs_xT="showLine",gvjs_yT="useLargeControl",gvjs_zT="useMapTypeControl",gvjs_AT="world";
function gvjs_BT(a,b,c){if(gvjs_r(b)&&(b=gvjs_2e(b),b.bounds)){var d=b.bounds;b.bounds=new google.maps.LatLngBounds(new google.maps.LatLng(d.lo.lat,d.lo.lng),new google.maps.LatLng(d.hi.lat,d.hi.lng))}a.yC.geocode(b,c)}function gvjs_CT(a,b,c){var d=gvjs_Ji(b),e=a.Fw.get(d);null!=e&&gvjs_u(e,function(f){f.MG||f.finish(b,c)});a.yx.delete(d);a.Fw.delete(d)}
gvjs_zl.prototype.FI=gvjs_V(23,function(a,b,c){var d=0;if(c===google.maps.GeocoderStatus.OVER_QUERY_LIMIT)d=520;else if(c===google.maps.GeocoderStatus.OK){var e=gvjs_Ji(a);if(!b||!c)throw Error("There must be a response and status here.");b={response:b,status:c};this.cache[e]=b;gvjs_CT(this,a,b)}else gvjs_CT(this,a,{response:null,status:c});gvjs_ol(this.eZ.bind(this),d,this)});
gvjs_zl.prototype.eZ=gvjs_V(22,function(){if(0!==this.cE.Cd()||0!==this.yx.size){var a=0<this.yx.size?gvjs_Ii(this.yx.values().next().value):this.cE.peek(),b=gvjs_Ji(a);if(b in this.cache){this.Fw.get(b);var c=this.cache[b];gvjs_Sx(this.cE);this.FI(a,c.response,c.status);this.Fw.delete(b)}else 0===this.yx.size&&0<this.cE.Cd()?(gvjs_Sx(this.cE),c=this.Fw.get(b),gvjs_Ie(c,function(d){return d.MG})?this.FI(a,null,null):(this.yx.add(b),gvjs_BT(this,a,this.FI.bind(this,a)))):0<this.yx.size&&gvjs_BT(this,
a,this.FI.bind(this,a))}});gvjs_ql.prototype.BN=gvjs_V(21,function(a){this.Wp();gvjs_sl(this,!0,a)});function gvjs_cja(a,b){gvjs_u(b.St,function(c){var d=gvjs_Ji(c);d in a.cache?b.finish(c,a.cache[d]):(a.Fw.has(d)||(a.cE.enqueue(c),a.Fw.set(d,[])),a.Fw.get(d).push(b))});a.eZ()}function gvjs_dja(a){var b=gvjs_$f(gvjs_Fd,a.ownerDocument&&a.ownerDocument.defaultView);b&&a.setAttribute(gvjs_rd,b)}
function gvjs_eja(a){var b=(a||document).getElementsByTagName("HEAD");return b&&0!==b.length?b[0]:a.documentElement}function gvjs_DT(a,b,c){null!=c&&gvjs_p.clearTimeout(c);a.onload=gvjs_me;a.onerror=gvjs_me;a.onreadystatechange=gvjs_me;b&&window.setTimeout(function(){gvjs_mh(a)},0)}function gvjs_qba(){if(this&&this.pfa){var a=this.pfa;a&&"SCRIPT"==a.tagName&&gvjs_DT(a,!0,this.zg)}}function gvjs_ET(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);gvjs_xe.call(this,c);this.code=a}
gvjs_t(gvjs_ET,gvjs_xe);
function gvjs_fja(a){var b={timeout:3E4,attributes:{async:!1,defer:!1}},c=b.document||document,d=gvjs_gf(a),e=(new gvjs_6g(c)).createElement("SCRIPT"),f={pfa:e,zg:void 0},g=new gvjs_ql(f),h=null,k=null!=b.timeout?b.timeout:5E3;0<k&&(h=window.setTimeout(function(){gvjs_DT(e,!0);var l=new gvjs_ET(1,"Timeout reached for loading script "+d);g.Wp();gvjs_sl(g,!1,l)},k),f.zg=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&e.readyState!=gvjs_Hb||(gvjs_DT(e,b.tCa||!1,h),g.BN(null))};
e.onerror=function(){gvjs_DT(e,!0,h);var l=new gvjs_ET(0,"Error while loading script "+d);g.Wp();gvjs_sl(g,!1,l)};f=b.attributes||{};gvjs_4e(f,{type:"text/javascript",charset:"UTF-8"});gvjs_$g(e,f);e.src=gvjs_hf(a);gvjs_dja(e);gvjs_eja(c).appendChild(e);return g}function gvjs_gja(a){var b=b||{};a=gvjs_Ty(gvjs_rba,a,b);var c=gvjs_fja(a);return new Promise(function(d){gvjs_vl(c,d,null,void 0)})}var gvjs_FT=[];function gvjs_GT(){return!!gvjs_le("google.maps.DirectionsService")}
function gvjs_HT(a,b){function c(){if(gvjs_GT()){var d=gvjs_FT;gvjs_FT=[];gvjs_u(d,function(e){e()})}else throw Error("Error: cannot load Maps API.");}gvjs_GT()?a():(gvjs_FT.push(a),1===gvjs_FT.length&&(b=b||gvjs_le("google.visualization.mapsApiKey"),""===b?a({Uma:!0}):gvjs_gja({key:typeof b===gvjs_l?b:""}).then(c)))}function gvjs_IT(a,b,c){this.BN=b;this.TK=0;this.MG=!1;this.St=a||[];this.MS=new Map;this.Oka=c||this.St.length}gvjs_IT.prototype.cancel=function(){this.MG=!0};
gvjs_IT.prototype.finish=function(a,b){a=gvjs_Ji(a);this.MS.has(a)||this.MS.set(a,b);b=[];if(!this.MG){a=this.St.length;for(var c=this.TK;c<a;c++){var d=gvjs_Ji(this.St[c]);if(!this.MS.has(d))break;d=this.MS.get(d);null!=d&&(d=d.response);b.push(d)}b.length<this.Oka&&this.TK+b.length<a||(this.TK+=b.length,this.BN(b),this.TK>=this.St.length&&this.cancel())}};function gvjs_JT(){this.St=[];this.yC=null}gvjs_JT.prototype.add=function(a){this.St.push(a)};
gvjs_JT.prototype.create=function(a,b,c,d){var e=this;null!=this.yC?(d=new gvjs_IT(a,b,c),this.add(d),gvjs_cja(this.yC,d)):gvjs_HT(function(f){f=void 0===f?{}:f;f&&f.Uma||(null==e.yC&&(e.yC=gvjs_zl.Lc()),e.create(a,b,c))},d)};gvjs_JT.prototype.cancel=function(){gvjs_u(this.St,function(a){a.cancel()});this.St=[]};var gvjs_KT={},gvjs_LT="https://www.gstatic.com/charts/regioncoder/0/";function gvjs_MT(a){this.Rma=a}
function gvjs_NT(a){gvjs_OT=a;gvjs_LT="https://www.gstatic.com/charts/regioncoder/"+a+"/"}function gvjs_PT(a,b){a=gvjs_mf(a.toLowerCase());a=encodeURIComponent(String(a));var c=gvjs_KT[a];null==c?(c=[b],gvjs_KT[a]=c,gvjs_hja(a,function(d){gvjs_QT(a,d)},function(){gvjs_QT(a,null)})):Array.isArray(c)?gvjs_Ey(c,b):gvjs_ol(gvjs_te(b,c),0)}
function gvjs_hja(a,b,c){gvjs_en(gvjs_LT+"/geocodes/"+(a+".js")).then(function(d){d=d.replace(/^[\s\S]*var results\s*=\s*/g,"");d=d.replace(/;\s*gviz\.util\.RegionCoder\.dictionaryReady[\s\S]*$/g,"");d=JSON.parse(d);b&&b(d);return d},function(d){c&&c(d)})}function gvjs_QT(a,b){var c=gvjs_KT[a];if(b){if(b=new gvjs_MT(b),Array.isArray(c))for(gvjs_KT[a]=b,a=0;a<c.length;a++)c[a](b)}else if(Array.isArray(c))for(gvjs_KT[a]=null,a=0;a<c.length;a++)c[a](null)}
function gvjs_RT(a,b){b=gvjs_mf(b.toLowerCase());return a.Rma[b]}gvjs_MT.dictionaryReady=gvjs_QT;var gvjs_OT="0";gvjs_NT(gvjs_OT);gvjs_q("gviz.util.RegionCoder.dictionaryReady",gvjs_QT,void 0);
