var gvjs_Po=" 0 0 1 ",gvjs_Qo="0%",gvjs_Ro="100%",gvjs_So="BUTTON",gvjs_To="SELECT",gvjs_Uo="TEXTAREA",gvjs_Vo="background",gvjs_Wo="baseline",gvjs_Xo="blur",gvjs_Yo="chartArea.bottom",gvjs_Zo="chartArea.height",gvjs__o="chartArea.left",gvjs_0o="chartArea.right",gvjs_1o="chartArea.top",gvjs_2o="chartArea.width",gvjs_3o="circle",gvjs_4o="clip-path",gvjs_5o="corners.bottomleft.rx",gvjs_6o="corners.bottomleft.ry",gvjs_7o="corners.bottomright.rx",gvjs_8o="corners.bottomright.ry",gvjs_9o="corners.rx",
gvjs_$o="corners.ry",gvjs_ap="corners.topleft.rx",gvjs_bp="corners.topleft.ry",gvjs_cp="corners.topright.rx",gvjs_dp="corners.topright.ry",gvjs_ep="datatable",gvjs_fp="datum",gvjs_gp="defs",gvjs_hp="discrete",gvjs_ip="ellipse",gvjs_R="end",gvjs_jp="feComponentTransfer",gvjs_kp="feGaussianBlur",gvjs_lp="feMergeNode",gvjs_mp="fill",gvjs_np="fill-opacity",gvjs_op="fill.color",gvjs_pp="fill.opacity",gvjs_qp="fillColor",gvjs_rp="fillOpacity",gvjs_sp="filter",gvjs_tp="finishAnimation",gvjs_up="font.family",
gvjs_vp="font.size",gvjs_wp="fontFamily",gvjs_xp="fontName",gvjs_yp="fontSize",gvjs_zp="getcontext",gvjs_Ap="gradient",gvjs_Bp="group",gvjs_Cp="halign",gvjs_S="horizontal",gvjs_Dp="http://www.w3.org/2000/svg",gvjs_Ep="in",gvjs_Fp="italic",gvjs_Gp="linear",gvjs_Hp="linearGradient",gvjs_Ip="offset",gvjs_Jp="opacity",gvjs_Kp="path",gvjs_Lp="playAnimation",gvjs_Mp="point",gvjs_Np="pointShape",gvjs_T="px",gvjs_Op="rabl-use-parent",gvjs_Pp="rect",gvjs_Qp="redraw",gvjs_Rp="rotate",gvjs_Sp="rotate(",gvjs_Tp=
"rtl",gvjs_Up="shadow.opacity",gvjs_Vp="shadow.radius",gvjs_Wp="shadow.xoffset",gvjs_Xp="shadow.yoffset",gvjs_Yp="slice",gvjs_Zp="stop",gvjs__p="stroke",gvjs_0p="stroke-opacity",gvjs_1p="stroke-width",gvjs_2p="stroke.color",gvjs_3p="stroke.opacity",gvjs_4p="stroke.width",gvjs_5p="strokeColor",gvjs_6p="strokeOpacity",gvjs_7p="strokeWidth",gvjs_8p="svg",gvjs_9p="text-anchor",gvjs_$p="transform",gvjs_aq="underline",gvjs_bq='unknown property on ellipse "',gvjs_cq="url(#",gvjs_dq="valign",gvjs_U="vertical";
function gvjs_V(a,b){return gvjs_4d[a]=b}gvjs_B.prototype.La=gvjs_V(10,function(){return this.right-this.left});gvjs_Pn.prototype.La=gvjs_V(9,function(a,b){return a.bD(gvjs_Yd)||gvjs_Ih(this.container).width||b||400});function gvjs_eq(a,b,c){gvjs_Pe(a,c,0,b)}function gvjs_fq(a,b,c){b=gvjs_iaa(b,function(d,e){var f={};return f[e]=d,f},c);gvjs_mj(a,b)}
function gvjs_gq(a,b,c){if(a.oN){var d={};gvjs_fq(d,a.oN[0].split("."),c);c=d}for(var e=d=0;e<b;e++)e===a.AJ.length&&a.AJ.push(0),d+=a.AJ[e];a.AJ[b]++;gvjs_eq(a.Gd,c,d)}function gvjs_hq(a,b){for(var c=gvjs_$d(Object.keys(b)),d=c.next();!d.done;d=c.next()){d=d.value;var e=b[d];null!=e&&e instanceof Object&&!Array.isArray(e)?(a[d]=a[d]||{},gvjs_hq(a[d],e)):null!=e&&(a[d]=e)}}function gvjs_iq(a){var b=void 0===b?{}:b;gvjs_Ee(a.Gd,function(c){gvjs_hq(b,c)});return b}
function gvjs_jq(a,b,c){return gvjs_Fj(a,gvjs_Lj,0,b,c)}function gvjs_kq(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return gvjs_kq.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c}
var gvjs_bda=/<[^>]*>|&[^;]+;/g,gvjs_cda=/[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,gvjs_dda=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0900-\u1fff\u200e\u2c00-\ud801\ud804-\ud839\ud83c-\udbff\uf900-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u08ff\u200f\ud802-\ud803\ud83a-\ud83b\ufb1d-\ufdff\ufe70-\ufefc]/,gvjs_eda=/^http:\/\/.*/,gvjs_fda=/\s+/,gvjs_gda=
/[\d\u06f0-\u06f9]/;function gvjs_lq(a,b){var c=0,d=0,e=!1;a=(b?a.replace(gvjs_bda,""):a).split(gvjs_fda);for(b=0;b<a.length;b++){var f=a[b];gvjs_dda.test(f)?(c++,d++):gvjs_eda.test(f)?e=!0:gvjs_cda.test(f)?d++:gvjs_gda.test(f)&&(e=!0)}return 0==d?e?1:0:.4<c/d?-1:1};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gvjs_hda=function(){if(gvjs_xg){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(gvjs_Tf))?a[1]:"0"}return gvjs_wg?(a=/1[0|1][_.][0-9_.]+/,(a=a.exec(gvjs_Tf))?a[0].replace(/_/g,"."):"10"):gvjs_Eaa?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(gvjs_Tf))?a[1]:""):gvjs_Faa||gvjs_Gaa||gvjs_Haa?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(gvjs_Tf))?a[1].replace(/_/g,"."):""):""}();function gvjs_mq(a){return(a=a.exec(gvjs_Tf))?a[1]:""}
var gvjs_nq=function(){if(gvjs_Laa)return gvjs_mq(/Firefox\/([0-9.]+)/);if(gvjs_y||gvjs_tg||gvjs_sg)return gvjs_Fg;if(gvjs_Mg)return gvjs_og()?gvjs_mq(/CriOS\/([0-9.]+)/):gvjs_mq(/Chrome\/([0-9.]+)/);if(gvjs_Ng&&!gvjs_og())return gvjs_mq(/Version\/([0-9.]+)/);if(gvjs_Kg||gvjs_Lg){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(gvjs_Tf);if(a)return a[1]+"."+a[2]}else if(gvjs_Maa)return(a=gvjs_mq(/Android\s+([0-9.]+)/))?a:gvjs_mq(/Version\/([0-9.]+)/);return""}();var gvjs_oq={};function gvjs_pq(){throw Error("Do not instantiate directly");}gvjs_pq.prototype.WN=null;gvjs_pq.prototype.getContent=function(){return this.content};gvjs_pq.prototype.toString=function(){return this.content};function gvjs_qq(){gvjs_pq.call(this)}gvjs_t(gvjs_qq,gvjs_pq);gvjs_qq.prototype.eq=gvjs_oq;gvjs_y&&gvjs_Gg(8);var gvjs_W=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.WN=d);return c}}(gvjs_qq),gvjs_rq=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=String(c);if(!c)return"";c=new b(c);void 0!==d&&(c.WN=d);return c}}(gvjs_qq);var gvjs_sq={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+gvjs_gg(" ",Number(c)-a.length):gvjs_gg(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;0<=b.indexOf("-",
0)?d=f+d+gvjs_gg(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",d=f+gvjs_gg(b,a)+d);return d},d:function(a,b,c,d,e,f,g,h){return gvjs_sq.f(parseInt(a,10),b,c,d,0,f,g,h)}};gvjs_sq.i=gvjs_sq.d;gvjs_sq.u=gvjs_sq.d;gvjs_kq(["A","AREA",gvjs_So,"HEAD",gvjs_Na,"LINK","MENU","META","OPTGROUP","OPTION","PROGRESS",gvjs_7a,gvjs_To,gvjs_5a,gvjs_Uo,"TITLE","TRACK"]);function gvjs_tq(){}gvjs_tq.prototype.o=function(a,b){gvjs_uq(this,a);this.cI[a].push(b);return this};gvjs_tq.prototype.Ab=function(a,b){gvjs_uq(this,a);a=this.cI[a];for(var c=null,d=0,e=a.length;d<e;d++)if(a[d]===b){c=d;break}return null!=c?(a.splice(c,1),!0):!1};gvjs_tq.prototype.fireEvent=function(a,b){gvjs_uq(this,a);a=this.cI[a];for(var c=[],d=0,e=a.length;d<e;d++)c.push(a[d]);for(d=0;d<e;d++)c[d].apply(this,b);return 0<e};
function gvjs_uq(a,b){if(!a.cI.hasOwnProperty(b))throw'event type "'+b+'" unknown.';};function gvjs_vq(a){this.cI={add:[],click:[],getcontext:[],mousemove:[],mouseenter:[],mouseleave:[],box:[],redraw:[],remove:[],playAnimation:[],finishAnimation:[]};this.Sb=this.ra=null;this.md={};this.Zn=[];this.oS=[];if(null!=a)for(var b in a)this.setStyle(b,a[b]);this.j6=null}gvjs_t(gvjs_vq,gvjs_tq);gvjs_=gvjs_vq.prototype;gvjs_.data=function(a){return void 0!==a?(this.ra=a,this):this.ra};gvjs_.setData=function(a){this.ra=a;return this};
gvjs_.setStyle=function(a,b){b instanceof Object&&null!=b&&(b=b.toString());if(this.md[a]===b)return!1;this.md[a]=b;this.eo=null;return!0};gvjs_.getStyle=function(a){return this.md[a]};function gvjs_wq(a){null==a.j6&&(a.j6=new gvjs_Aj([a.md],void 0,!0));return a.j6}gvjs_.style=function(a,b){return void 0!==b?(this.setStyle(a,b)&&this.fireEvent(gvjs_Qp,[this,a]),this):this.getStyle(a)};gvjs_.styles=function(a){for(var b in a)a.hasOwnProperty(b)&&this.style(b,a[b]);return this};
gvjs_.getContext=function(){this.Sb||this.fireEvent(gvjs_zp,[this]);return this.Sb};gvjs_.Qj=gvjs_n(25);gvjs_.Ou=gvjs_n(27);gvjs_.kEa=function(){for(var a=this;0<this.Zn.length;){var b=this.Zn.shift();a.oS.push(b);b.o(gvjs_tp,function(c,d){c=a.oS.indexOf(d);if(0>c)throw"Animation not found.";a.oS.splice(c,1);0===a.oS.length&&a.fireEvent(gvjs_tp,[a])});if(!this.fireEvent(gvjs_Lp,[this,b]))throw"Cannot play animations for shape not in a scene.";}return this};var gvjs_ida=gvjs_p.requestAnimationFrame||gvjs_p.mozRequestAnimationFrame||gvjs_p.webkitRequestAnimationFrame||gvjs_p.msRequestAnimationFrame||function(a){return gvjs_p.setTimeout(function(){return a.call(this,Date.now())},1E3/60)};function gvjs_xq(a){for(var b=0,c=arguments.length;b<c;b++)if(null!=arguments[b])return arguments[b]}
function gvjs_yq(a,b,c,d){gvjs_zq(a,b,c,d);gvjs_Aq(a,b,c,d);gvjs_Bq(a,b,c,d);gvjs_Cq(a,b,c,d);gvjs_Dq(a,b,c,d);gvjs_Eq(a,b,c,d);gvjs_Fq(a,b,c,d);var e=gvjs_wq(c),f=gvjs_L(e,"clip.width"),g=gvjs_L(e,"clip.height");if(f&&g){var h=gvjs_L(e,"clip.x",0);e=gvjs_L(e,"clip.y",0);var k=["clip",h,e,f,g].join(),l=c.yr;if(c=a.l3(k,l))n=c.getAttribute(gvjs_6c);else{var m=gvjs_Rh();c=m.createElementNS(gvjs_Dp,"clipPath");var n=a.CZ();c.setAttribute(gvjs_6c,n);m=m.createElementNS(gvjs_Dp,gvjs_Pp);m.setAttribute("x",
h);m.setAttribute("y",e);m.setAttribute(gvjs_Yd,f);m.setAttribute(gvjs_5c,g);c.appendChild(m);a.R4(k,c,l);for(a=d;a.nodeName!==gvjs_8p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(c,a.firstChild)}b.setAttribute(gvjs_4o,gvjs_cq+n+")")}else b.hasAttribute(gvjs_4o)&&b.removeAttribute(gvjs_4o)}
function gvjs_Aq(a,b,c,d){gvjs_Gq(a,b,c,d,!1);a=gvjs_xq(c.style(gvjs_op),c.style(gvjs_qp),c.style(gvjs_mp));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_mp,a):null===a&&b.removeAttribute(gvjs_mp)}function gvjs_Bq(a,b,c){a=gvjs_xq(c.style(gvjs_pp),c.style(gvjs_rp),c.style(gvjs_np));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_np,a):null===a&&b.removeAttribute(gvjs_np)}
function gvjs_Cq(a,b,c,d){gvjs_Gq(a,b,c,d,!0);a=gvjs_xq(c.style(gvjs_2p),c.style(gvjs_5p),c.style(gvjs__p));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs__p,a):null===a&&b.removeAttribute(gvjs__p)}function gvjs_Dq(a,b,c){a=gvjs_xq(c.style(gvjs_3p),c.style(gvjs_6p),c.style(gvjs_0p));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_0p,a):null===a&&b.removeAttribute(gvjs_0p)}
function gvjs_Eq(a,b,c){a=gvjs_xq(c.style(gvjs_4p),c.style(gvjs_7p),c.style(gvjs_1p));typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_1p,a):null===a&&b.removeAttribute(gvjs_1p)}function gvjs_zq(a,b,c){a=c.style(gvjs_Jp);typeof a===gvjs_l||typeof a===gvjs_g?b.setAttribute(gvjs_Jp,a):null===a&&b.removeAttribute(gvjs_Jp)}
function gvjs_Gq(a,b,c,d,e){var f=gvjs_wq(c),g=e?gvjs__p:gvjs_mp,h=f.kt(g+".gradient.from"),k=f.kt(g+".gradient.to");e=b.getAttribute(g);if(h&&k){var l=gvjs_jq(f,g+".gradient.x1",gvjs_Qo),m=gvjs_jq(f,g+".gradient.y1",gvjs_Qo),n=gvjs_jq(f,g+".gradient.x2",gvjs_Ro),p=gvjs_jq(f,g+".gradient.y2",gvjs_Qo);f=[gvjs_Ap,h,k,l,m,n,p].join();var q=c.yr;if(c=a.l3(f,q))g=c.getAttribute(gvjs_6c);else{var r=gvjs_Rh();c=r.createElementNS(gvjs_Dp,gvjs_Hp);g=a.CZ();c.setAttribute(gvjs_6c,g);c.setAttribute("x1",l);
c.setAttribute("y1",m);c.setAttribute("x2",n);c.setAttribute("y2",p);l=r.createElementNS(gvjs_Dp,gvjs_Zp);l.setAttribute("stop-color",h);l.setAttribute(gvjs_Ip,gvjs_Qo);h=r.createElementNS(gvjs_Dp,gvjs_Zp);h.setAttribute("stop-color",k);h.setAttribute(gvjs_Ip,gvjs_Ro);c.appendChild(l);c.appendChild(h);a.R4(f,c,q);for(a=d;a.nodeName!==gvjs_8p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(c,a.firstChild)}a=gvjs_cq+g+")";e!==a&&b.setAttribute(gvjs_mp,a)}else e&&e.substr(0,5)===gvjs_cq&&
b.removeAttribute(g)}
function gvjs_Fq(a,b,c,d){var e=gvjs_wq(c),f=gvjs_jq(e,gvjs_Vp,0),g=gvjs_jq(e,gvjs_Up,0);if(f||g){var h=e.kt("shadow.xOffset")||e.kt("shadow.x-offset")||e.kt(gvjs_Wp)||0,k=e.kt("shadow.yOffset")||e.kt("shadow.y-offset")||e.kt(gvjs_Xp)||0;e=[gvjs_Xo,f,g,h,k].join();var l=c.yr,m=a.l3(e,l);if(m)c=m.getAttribute(gvjs_6c);else{var n=gvjs_Rh();m=n.createElementNS(gvjs_Dp,gvjs_sp);m.setAttribute("x","-100%");m.setAttribute("y","-100%");m.setAttribute(gvjs_Yd,"300%");m.setAttribute(gvjs_5c,"300%");c=a.CZ();
m.setAttribute(gvjs_6c,c);var p=n.createElementNS(gvjs_Dp,gvjs_kp);p.setAttribute(gvjs_Ep,"SourceAlpha");p.setAttribute("stdDeviation",f);f=n.createElementNS(gvjs_Dp,"feOffset");f.setAttribute("dx",h);f.setAttribute("dy",k);if(null!=g){var q=n.createElementNS(gvjs_Dp,gvjs_jp);var r=n.createElementNS(gvjs_Dp,"feFuncA");r.setAttribute(gvjs_Td,gvjs_Gp);r.setAttribute("slope",g)}g=n.createElementNS(gvjs_Dp,"feMerge");h=n.createElementNS(gvjs_Dp,gvjs_lp);n=n.createElementNS(gvjs_Dp,gvjs_lp);n.setAttribute(gvjs_Ep,
"SourceGraphic");m.appendChild(p);m.appendChild(f);null!=r&&(q.appendChild(r),m.appendChild(q));g.appendChild(h);g.appendChild(n);m.appendChild(g);a.R4(e,m,l);for(a=d;a.nodeName!==gvjs_8p;)a=a.parentNode;a=a.querySelector(gvjs_gp)||a;a.insertBefore(m,a.firstChild)}a=b.getAttribute(gvjs_sp);d=gvjs_cq+c+")";a!==d&&b.setAttribute(gvjs_sp,d)}else b.hasAttribute(gvjs_sp)&&b.removeAttribute(gvjs_sp)}
var gvjs_jda={"fill.color":gvjs_Aq,fillColor:gvjs_Aq,fill:gvjs_Aq,"fill.gradient.from":gvjs_Aq,"fill.gradient.to":gvjs_Aq,"fill.gradient.x1":gvjs_Aq,"fill.gradient.y1":gvjs_Aq,"fill.gradient.x2":gvjs_Aq,"fill.gradient.y2":gvjs_Aq,"fill.opacity":gvjs_Bq,fillOpacity:gvjs_Bq,"fill-opacity":gvjs_Bq,height:function(a,b,c){a=gvjs_L(gvjs_wq(c),gvjs_5c);b.setAttribute(gvjs_5c,a)},opacity:gvjs_zq,"shadow.radius":gvjs_Fq,"shadow.opacity":gvjs_Fq,"shadow.xOffset":gvjs_Fq,"shadow.x-offset":gvjs_Fq,"shadow.xoffset":gvjs_Fq,
"shadow.yOffset":gvjs_Fq,"shadow.y-offset":gvjs_Fq,"shadow.yoffset":gvjs_Fq,"stroke.color":gvjs_Cq,strokeColor:gvjs_Cq,stroke:gvjs_Cq,"stroke.gradient.from":gvjs_Cq,"stroke.gradient.to":gvjs_Cq,"stroke.gradient.x1":gvjs_Cq,"stroke.gradient.y1":gvjs_Cq,"stroke.gradient.x2":gvjs_Cq,"stroke.gradient.y2":gvjs_Cq,"stroke.opacity":gvjs_Dq,strokeOpacity:gvjs_Dq,"stroke-opacity":gvjs_Dq,"stroke.width":gvjs_Eq,strokeWidth:gvjs_Eq,"stroke-width":gvjs_Eq,width:function(a,b,c){a=gvjs_L(gvjs_wq(c),gvjs_Yd);b.setAttribute(gvjs_Yd,
a)},x:function(a,b,c){a=gvjs_L(gvjs_wq(c),"x");b.setAttribute("x",a)},y:function(a,b,c){a=gvjs_L(gvjs_wq(c),"y");b.setAttribute("y",a)}};function gvjs_Hq(a,b,c,d,e,f){f=f||{};return(c=f[c]||gvjs_jda[c])?(c(a,b,d,e),!0):!1};var gvjs_Iq={applyX:function(a,b,c){a=gvjs_wq(c).Aa("x");null!=a&&b.setAttribute("cx",a)},applyY:function(a,b,c){a=gvjs_wq(c).Aa("y");null!=a&&b.setAttribute("cy",a)},p7:function(a,b,c){a=gvjs_wq(c).Aa("r");null!=a&&b.setAttribute("r",a)}};gvjs_Iq.DK={r:gvjs_Iq.p7,x:gvjs_Iq.applyX,y:gvjs_Iq.applyY};
gvjs_Iq.draw=function(a,b,c,d){var e=gvjs_Rh();d=d||e.createElementNS(gvjs_Dp,gvjs_3o);gvjs_Iq.applyX(a,d,b);gvjs_Iq.applyY(a,d,b);gvjs_Iq.p7(a,d,b);gvjs_yq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Iq.Lf=function(a,b,c,d,e){if(!gvjs_Hq(a,e,c,b,d,gvjs_Iq.DK))throw'unknown property on circle "'+c+'".';};var gvjs_Jq={};function gvjs_Kq(a,b,c){a=gvjs_L(gvjs_wq(c),"x");b.setAttribute("cx",a)}function gvjs_Lq(a,b,c){a=gvjs_L(gvjs_wq(c),"y");b.setAttribute("cy",a)}function gvjs_Mq(a,b,c){a=gvjs_L(gvjs_wq(c),"rx");b.setAttribute("rx",a)}function gvjs_Nq(a,b,c){a=gvjs_L(gvjs_wq(c),"ry");b.setAttribute("ry",a)}var gvjs_Oq={x:gvjs_Kq,y:gvjs_Lq,rx:gvjs_Mq,ry:gvjs_Nq};gvjs_Jq.kCa=gvjs_Mq;gvjs_Jq.lCa=gvjs_Nq;gvjs_Jq.applyX=gvjs_Kq;gvjs_Jq.applyY=gvjs_Lq;
gvjs_Jq.draw=function(a,b,c,d){var e=gvjs_Rh();d=d||e.createElementNS(gvjs_Dp,gvjs_ip);gvjs_Kq(a,d,b);gvjs_Lq(a,d,b);gvjs_Mq(a,d,b);gvjs_Nq(a,d,b);gvjs_yq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Jq.DK=gvjs_Oq;gvjs_Jq.Lf=function(a,b,c,d,e){if(!gvjs_Hq(a,e,c,b,d,gvjs_Oq))throw gvjs_bq+c+'".';};var gvjs_Pq={q7:function(a,b,c){a=gvjs_L(gvjs_wq(c),"x1");b.setAttribute("x1",a)},s7:function(a,b,c){a=gvjs_L(gvjs_wq(c),"y1");b.setAttribute("y1",a)},r7:function(a,b,c){a=gvjs_L(gvjs_wq(c),"x2");b.setAttribute("x2",a)},t7:function(a,b,c){a=gvjs_L(gvjs_wq(c),"y2");b.setAttribute("y2",a)}};gvjs_Pq.DK={x1:gvjs_Pq.q7,x2:gvjs_Pq.r7,y1:gvjs_Pq.s7,y2:gvjs_Pq.t7};
gvjs_Pq.draw=function(a,b,c,d){var e=gvjs_Rh();d=d||e.createElementNS(gvjs_Dp,gvjs_e);gvjs_Pq.q7(a,d,b);gvjs_Pq.r7(a,d,b);gvjs_Pq.s7(a,d,b);gvjs_Pq.t7(a,d,b);gvjs_yq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d};gvjs_Pq.Lf=function(a,b,c,d,e){if(!gvjs_Hq(a,e,c,b,d,gvjs_Pq.DK))throw gvjs_bq+c+'".';};function gvjs_Qq(a){a%=360;return 0>360*a?a+360:a};function gvjs_Rq(a,b,c,d){var e=gvjs_Rh();e=d||e.createElementNS(gvjs_Dp,gvjs_Kp);d||e.setAttribute("d",gvjs_Sq(c));gvjs_yq(a,e,c,b);return e}
function gvjs_Sq(a){a=a.$u;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];if("GVIZARC"===e[0]){var f=e,g=Number(f[1]),h=Number(f[2]);e=Number(f[3]);var k=Number(f[4]),l=gvjs_Qq(Number(f[5])),m=gvjs_Qq(Number(f[6]));f=!!Number(f[7]);270===l&&0===m?e="A "+e+" "+k+gvjs_Po+(e+g)+" "+h:180===l&&270===m?e="A "+e+" "+k+gvjs_Po+g+" "+(h-k):0===l&&90===m?e="A "+e+" "+k+gvjs_Po+g+" "+(h+k):90===l&&180===m?e="A "+e+" "+k+gvjs_Po+(g-e)+" "+h:(g+=Math.cos(m/180*Math.PI)*e,h+=Math.sin(m/180*Math.PI)*k,l=f?m-l:
l-m,0>l&&(l+=360),e="A "+e+" "+k+" 0 "+Number(180<l)+" "+Number(f)+" "+g+" "+h)}else e=e.join(" ");b.push(e)}return b.join(" ")};function gvjs_Tq(a){gvjs_vq.call(this,a);this.eo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.$u=[]}gvjs_o(gvjs_Tq,gvjs_vq);gvjs_=gvjs_Tq.prototype;gvjs_.Rk=gvjs_n(32);gvjs_.Ou=gvjs_n(26);gvjs_.clear=function(){this.eo={x1:null,y1:null,x2:null,y2:null,width:0,height:0};this.$u=[]};gvjs_.move=function(a,b){this.$u.push(["M",a,b]);return this};gvjs_.line=function(a,b){this.$u.push(["L",a,b]);return this};
gvjs_.arc=function(a,b,c,d,e,f,g){e=gvjs_Qq(e);f=gvjs_Qq(f);this.$u.push(["GVIZARC",a,b,c,d,e,f,Number(g)]);return this};gvjs_.curve=function(a,b,c,d,e,f){this.$u.push(["C",a,b,c,d,e,f]);return this};gvjs_.close=function(){this.$u.push(["Z"]);return this};function gvjs_Uq(a){var b=gvjs_wq(a);a=b.Aa(gvjs_ap)||0;var c=b.Aa(gvjs_bp)||0,d=b.Aa(gvjs_cp)||0,e=b.Aa(gvjs_dp)||0,f=b.Aa(gvjs_5o)||0,g=b.Aa(gvjs_6o)||0,h=b.Aa(gvjs_7o)||0;b=b.Aa(gvjs_8o)||0;return!!(a||c||d||e||f||g||h||b)}
function gvjs_Vq(a){var b=gvjs_wq(a),c=gvjs_L(b,gvjs_9o,0),d=gvjs_L(b,gvjs_$o,0),e=gvjs_L(b,gvjs_ap,c),f=gvjs_L(b,gvjs_bp,d),g=gvjs_L(b,gvjs_cp,c),h=gvjs_L(b,gvjs_dp,d),k=gvjs_L(b,gvjs_5o,c),l=gvjs_L(b,gvjs_6o,d);c=gvjs_L(b,gvjs_7o,c);d=gvjs_L(b,gvjs_8o,d);var m=gvjs_L(b,gvjs_Yd),n=gvjs_L(b,gvjs_5c),p=gvjs_L(b,"x");b=gvjs_L(b,"y");p=0<=m?p:p+m;b=0<=n?b:b+n;m=Math.abs(m);n=Math.abs(n);if(e+g>m){var q=m/(e+g);e*=q;f*=q;g*=q;h*=q}k+c>m&&(q=m/(k+c),k*=q,l*=q,c*=q,d*=q);f+l>n&&(q=n/(f+l),e*=q,f*=q,k*=
q,l*=q);h+d>n&&(q=n/(h+d),g*=q,h*=q,c*=q,d*=q);return(new gvjs_Tq(a.md)).move(p+m-g,b).arc(p+m-g,b+h,g,h,270,0,!0).line(p+m,b+n-d).arc(p+m-c,b+n-d,c,d,0,90,!0).line(p+k,b+n).arc(p+k,b+n-l,k,l,90,180,!0).line(p,b+f).arc(p+e,b+f,e,f,180,270,!0).close()};var gvjs_Wq={draw:function(a,b,c,d){var e=b.style(gvjs_9o),f=b.style(gvjs_$o),g=gvjs_wq(b),h=gvjs_L(g,gvjs_Yd),k=gvjs_L(g,gvjs_5c),l=gvjs_L(g,"x");g=gvjs_L(g,"y");l=0<=h?l:l+h;g=0<=k?g:g+k;h=Math.abs(h);k=Math.abs(k);if(typeof e===gvjs_g&&typeof f===gvjs_g||!gvjs_Uq(b)){var m=gvjs_Rh();d=d||m.createElementNS(gvjs_Dp,gvjs_Pp);d.setAttribute("x",l);d.setAttribute("y",g);d.setAttribute(gvjs_Yd,h);d.setAttribute(gvjs_5c,k);null!=e&&typeof e===gvjs_g&&d.setAttribute("rx",e);null!=f&&typeof f===gvjs_g&&
d.setAttribute("ry",f);gvjs_yq(a,d,b,c)}else b=gvjs_Vq(b),d=gvjs_Rq(a,c,b,d);c&&d.parentNode!==c&&c.appendChild(d);return d},Lf:function(a,b,c,d,e){if(!gvjs_Hq(a,e,c,b,d))switch(c){case gvjs_9o:case gvjs_$o:case gvjs_ap:case gvjs_bp:case gvjs_cp:case gvjs_dp:case gvjs_5o:case gvjs_6o:case gvjs_7o:case gvjs_8o:var f=gvjs_Uq(b),g=e.tagName.toLowerCase();if(g===gvjs_Kp&&!f||g===gvjs_Pp&&f)return gvjs_Wq.draw(a,b,d);g===gvjs_Kp?(a=gvjs_Vq(b),a=gvjs_Sq(a),e.setAttribute("d",a)):c===gvjs_9o?e.setAttribute("rx",
gvjs_L(gvjs_wq(b),gvjs_9o)):c===gvjs_$o&&e.setAttribute("ry",gvjs_L(gvjs_wq(b),gvjs_$o));break;default:throw'unknown property on rect "'+c+'".';}}};var gvjs_Xq={};function gvjs_Yq(a,b,c){a=c.style(gvjs_up)||c.style(gvjs_wp)||c.style(gvjs_xp);b.style.fontFamily=typeof a===gvjs_l?a:""}function gvjs_Zq(a,b,c){a=c.style(gvjs_vp)||c.style(gvjs_yp);b.style.fontSize=typeof a===gvjs_g?a+gvjs_T:typeof a===gvjs_l?a:""}function gvjs__q(a,b,c){a=c.style("font.weight")||c.style("fontWeight");b.style.fontWeight=typeof a===gvjs_l||typeof a===gvjs_g?String(a):""}function gvjs_0q(a,b,c){!0===c.style(gvjs_Fp)?b.style.fontStyle=gvjs_Fp:b.style.fontStyle=""}
function gvjs_1q(a,b,c){!0===c.style(gvjs_aq)?b.style.textDecoration=gvjs_aq:b.style.textDecoration=""}var gvjs_2q={"font.family":gvjs_Yq,fontFamily:gvjs_Yq,fontName:gvjs_Yq,"font.size":gvjs_Zq,fontSize:gvjs_Zq,"font.weight":gvjs__q,fontWeight:gvjs__q,italic:gvjs_0q,underline:gvjs_1q};
function gvjs_3q(a,b,c,d,e,f,g,h){var k=gvjs_Rh();f=f||gvjs_m;e=!e||f&&e.tagName!==f?k.createElementNS(gvjs_Dp,f):e;e.textContent=c;c=gvjs_wq(d);e.setAttribute("x",null==g?gvjs_jq(c,"x"):g);e.setAttribute("y",null==h?gvjs_jq(c,"y"):h);e.setAttribute(gvjs_Kd,"cursor:default;-webkit-user-select:none;-moz-osx-font-smoothing:grayscale;");e.style.webkitFontSmoothing="antialiased";gvjs_yq(a,e,d,b);gvjs_0q(a,e,d);gvjs_1q(a,e,d);gvjs_Yq(a,e,d);gvjs_Zq(a,e,d);gvjs__q(a,e,d);return e}
function gvjs_4q(a,b,c,d){var e=b.style("lineSpacing")||b.style("line-spacing")||0,f=gvjs_wq(b),g=gvjs_J(f,gvjs_m,""),h=-1==gvjs_lq(g,void 0)&&gvjs_y;typeof g===gvjs_l&&(g=g.split("\n"));var k=gvjs_L(f,"y",0),l=!0;1===g.length&&(g=g[0],l=!1);a=gvjs_3q(a,c,l?"":g,b,d,null,gvjs_L(f,"x",0),k);c&&a.parentNode!==c&&c.appendChild(a);c=[];if(l)for(b=gvjs_Rh(),d=0,k=g.length;d<k;d++){var m=b.createElementNS(gvjs_Dp,"tspan");m.textContent=g[d];m.setAttribute(gvjs_Op,!0);m.setAttribute("x",gvjs_jq(f,"x"));
m.setAttribute("y",gvjs_jq(f,"y"));var n=a.getBBox().height;0<d&&(n+=e);m.setAttribute("dy",n+gvjs_T);a.appendChild(m);c.push(m)}h&&(a.setAttribute("dir",gvjs_Tp),a.setAttribute(gvjs_9p,gvjs_R));return{group:a,lines:l?c:[a]}}
function gvjs_5q(a,b,c,d){c=gvjs_4q(a,b,c,d);a=c.lines;c=c.group;d=Math.max(0,Math.min(1,b.style(gvjs_Cp)||0));if(isNaN(d)||!isFinite(d))d=0;var e=b.style(gvjs_dq);if(typeof e===gvjs_g){if(e=Math.max(0,Math.min(1,e)),isNaN(e)||!isFinite(e))e=0}else e=gvjs_Wo;var f=c.getBBox(),g=b.style("y")-f.y;var h="tspan"===a[a.length-1].tagName.toLowerCase()?a[a.length-1].getBoundingClientRect().top-c.getBoundingClientRect().top:a[a.length-1].getBBox().y-f.y;var k=b.style("y");if(null==k)return c;if(typeof e===
gvjs_g)k=k+g-f.height*e;else if(e===gvjs_Wo)k=k+g-h;else throw"Unrecognized valign value: "+e;c.setAttribute("y",k);e=0;for(f=a.length;e<f;e++)g=a[e],g.setAttribute("dx",-g.getComputedTextLength()*d+gvjs_T),g.setAttribute("y",k);a=b.style(gvjs_Rp);null!=a&&0!=a&&c.setAttribute(gvjs_$p,gvjs_Sp+a+" "+b.style("x")+" "+b.style("y")+")");return c}gvjs_Xq.gCa=gvjs_Yq;gvjs_Xq.hCa=gvjs_Zq;gvjs_Xq.iCa=gvjs__q;gvjs_Xq.jCa=gvjs_0q;gvjs_Xq.mCa=gvjs_1q;gvjs_Xq.BCa=gvjs_3q;gvjs_Xq.draw=gvjs_5q;gvjs_Xq.ICa=gvjs_4q;
gvjs_Xq.DK=gvjs_2q;gvjs_Xq.Lf=function(a,b,c,d,e){var f="x"===c||"y"===c;if(f||!gvjs_Hq(a,e,c,b,d,gvjs_2q))if(c===gvjs_m||c===gvjs_Cp||c===gvjs_dq||f){for(;e&&e.firstChild;)e.removeChild(e.firstChild);a=gvjs_5q(a,b,d,e);if(e!==a)throw"error redrawing text";}else throw'error redrawing text element with changed property "'+c+'".';};var gvjs_6q={draw:function(a,b,c,d){var e=gvjs_Rh();d=d||e.createElementNS(gvjs_Dp,"g");gvjs_yq(a,d,b,c);c&&d.parentNode!==c&&c.appendChild(d);return d},Lf:function(a,b,c,d){a=gvjs_6q.draw(a,b,c,d);d!==a&&b.getContext().fireEvent("add",[b,a,!1])}};var gvjs_kda={Circle:gvjs_Iq,Ellipse:gvjs_Jq,Line:gvjs_Pq,Path:{draw:function(a,b,c,d){a=gvjs_Rq(a,c,b,d);c&&a.parentNode!==c&&c.appendChild(a);return a},Lf:function(a,b,c,d,e){if(!gvjs_Hq(a,e,c,b,d))throw gvjs_bq+c+'".';}},Rect:gvjs_Wq,Text:gvjs_Xq,Group:gvjs_6q};/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT

*/
/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT
*/
function gvjs_7q(a){gvjs_F.call(this);this.e$=a}gvjs_o(gvjs_7q,gvjs_F);gvjs_7q.prototype.Is=gvjs_n(33);gvjs_7q.prototype.dispatchEvent=function(a,b){gvjs_I(this.e$,a,void 0===b?null:b)};gvjs_7q.prototype.M=function(){this.e$=null;gvjs_F.prototype.M.call(this)};function gvjs_8q(a,b,c,d,e){if(null==a||null==b)null==c&&(c=e),c=Math.max(0,d-c),null==a&&null==b?a=b=c/2:null==a?a=Math.max(0,c-b):b=Math.max(0,c-a);c=Math.max(0,Math.round(d-(a+b)));a=Math.round(a);d=Math.min(d,a+c);return{before:a,after:d,size:d-a}}
function gvjs_9q(a,b,c){var d=a/1.618,e=a-b*(1.618-1),f=b/1.618,g=b-a*(1.618-1);a=gvjs_8q(c.left,c.right,c.width,a,Math.round(d>e?d:(d+2*e)/3));b=gvjs_8q(c.top,c.bottom,c.height,b,Math.round(f>g?f:(f+2*g)/3));return{left:a.before,right:a.after,width:a.size,top:b.before,bottom:b.after,height:b.size}};
