var gvjs_GX="All weights in tree must be positive (at row ",gvjs_HX="explicit format",gvjs_IX="font.underline",gvjs_JX="implicit",gvjs_KX="specified";function gvjs_LX(){}gvjs_o(gvjs_LX,gvjs_zl);gvjs_LX.prototype.Pb=function(a){try{this.Ac(a)}catch(b){return!1}return!0};
gvjs_LX.prototype.Ac=function(a,b){gvjs_Al(a);b=null!=b?b:a.W(0)===gvjs_l?gvjs_JX:gvjs_ou;if(b===gvjs_JX){this.jb("implicit format",a,0,gvjs_l,"");var c=b=null,d=null,e=1,f=a.$();e<f&&gvjs_Dl(a,e,gvjs_g,"")&&(b=e++);e<f&&gvjs_El(a,e,[gvjs_g,gvjs_l],"")&&(c=e++);if(e<f)if(gvjs_Dl(a,e,gvjs_l,gvjs_Jd))d=e++;else throw Error("Found unexpected column at "+e+".");if(e<f)throw Error("Found "+(f-e)+" extra columns.");a={format:gvjs_JX,columns:{text:0,weight:b,color:c,style:d}}}else{this.jb(gvjs_HX,a,0,gvjs_g,
"");this.jb(gvjs_HX,a,1,gvjs_l,"");this.jb(gvjs_HX,a,2,gvjs_g,"");this.jb(gvjs_HX,a,3,gvjs_g,"");b=4;c=a.$();d=null;b<c&&gvjs_El(a,b,[gvjs_g,gvjs_l],"")&&(d=b++);e=null;c>b&&(this.jb(gvjs_HX,a,b,gvjs_l,gvjs_Jd),e=b);if(1<c-b)throw Error("Expected between 4 and 6 columns, got "+c);a={format:gvjs_ou,columns:{id:0,Hp:1,parent:2,weight:3,color:d,style:e}}}return a};
gvjs_LX.prototype.jb=function(a,b,c,d,e){Array.isArray(d)||(d=[d]);var f=d;e=null!=e?[e]:[];if(!(c<b.$()&&gvjs_Cl(b,c,f)&&gvjs_Bl(b,c,e)))throw Error(gvjs_es+a+": column #"+c+gvjs_ba+d+"'.");};
var gvjs_zka={tAa:gvjs_JX,uV:gvjs_ou},gvjs_Aka=[{input:gvjs_1,bg:[gvjs_mp]},{input:gvjs_Hp,bg:[gvjs_np]},{input:gvjs_op,bg:[gvjs_mp]},{input:gvjs_pp,bg:[gvjs_np]},{input:gvjs_3p,bg:[gvjs_0p]},{input:gvjs_4p,bg:[gvjs_1p]},{input:gvjs_5p,bg:[gvjs_2p]},{input:gvjs_wp,bg:[gvjs_tp]},{input:gvjs_up,bg:[gvjs_sp]},{input:gvjs_ot,bg:["font.bold"]},{input:gvjs_Dp,bg:["font.italic"]},{input:gvjs_9p,bg:[gvjs_IX]}];function gvjs_MX(a){return gvjs_7I(a,gvjs_Aka)}
function gvjs_NX(a,b){b.color=gvjs_J(a,gvjs_mp,b.color);b.opacity=gvjs_L(a,gvjs_np,b.opacity);b.Lb=gvjs_J(a,gvjs_0p,b.Lb);b.bb=gvjs_J(a,gvjs_sp,b.bb);b.fontSize=gvjs_L(a,gvjs_tp,b.fontSize);b.bold=gvjs_K(a,"font.bold",b.bold);b.Nc=gvjs_K(a,"font.italic",b.Nc);b.Ue=gvjs_K(a,gvjs_IX,b.Ue)}function gvjs_OX(a){a=a||{};this.Hp=a.word||"";this.label=a.label||this.Hp;this.weight=a.weight||0;this.properties=a.properties||{};this.R={};this.ue=[];this.Wu={};this.id=a.id||gvjs_pe(this)}gvjs_=gvjs_OX.prototype;
gvjs_.Ex=function(a){for(var b=0;b<this.ue.length;b++)this.ue[b].Ex(a);a.call(this)};gvjs_.addChild=function(a){this.Wu[a.Hp]||(this.ue.push(a),this.Wu[a.Hp]=a,a.parent=this)};gvjs_.CC=function(a){return this.Wu[a]};gvjs_.$v=function(){return!this.ue||0==this.ue.length};function gvjs_PX(a){return a.parent?gvjs_PX(a.parent):a}
gvjs_.Kx=function(a){if(this.$v())this.weight||(this.weight=1);else{for(var b=0,c=0;c<this.ue.length;c++)this.ue[c].Kx(a),b+=this.ue[c].weight;this.weight=b}if(a&&a.propertyCalculators)for(c=0;c<a.propertyCalculators.length;c++)a.propertyCalculators[c](this)};function gvjs_QX(a){this.iT=a&&a.iT||/\s*(.+?(?:[?!]+|$|\.(?=\s+[A-Z]|$)))\s*/;this.ZU=a&&a.ZU||/([!?,;:.&"-]+|\S*(?:[^!?,;":.\s&-]))/;gvjs_y&&"8.0"==gvjs_Dg&&(this.iT=/[!?.]/,this.ZU=/[ ,;]|['$][^[']]/);this.root=new gvjs_OX({});this.jN=a&&a.jN}
gvjs_QX.prototype.tB=function(a,b,c,d,e){a=gvjs_Bka(this,a);for(c=0;c<a.length;c++){var f=a[c],g=b,h=d,k=e;if(0!=f.length){f=gvjs_Cka(this,f);this.jN&&(f=f.reverse());for(var l=0;l<f.length;l++){var m=this.root,n=f,p=l,q=h,r=k,t=g||1;m.weight+=t;p=p||0;if(!(p>=n.length))for(var u=p;u<n.length;u++)p=m.Wu[n[u]],p||(p=new gvjs_OX({word:gvjs_kf(n[u]),weight:0,properties:{color:q||0,style:r}}),m.addChild(p)),p.weight+=t,m=p}}}};
function gvjs_Bka(a,b){a=b.split(a.iT);return a=a.filter(function(c){return 0!=c&&void 0!=c})}function gvjs_Cka(a,b){a=b.split(a.ZU);return a=a.filter(function(c){return 0!=c&&void 0!=c})}gvjs_q("gviz.wordtree.SuffixTree",gvjs_QX,void 0);var gvjs_Dka={FBa:gvjs_Kd,G6:gvjs_wd,gAa:"double"},gvjs_Eka={Sja:gvjs_Zd,IBa:"texttree"},gvjs_RX={wordtree:{word:"",type:gvjs_Kd,renderer:gvjs_Zd},colors:["#4184f3",gvjs_pr,"#f3b300"],colorAxis:{values:null,colors:null,minValue:null,maxValue:null},maxFontSize:36,fontName:gvjs_zw,backgroundColor:gvjs_Kx};function gvjs_SX(a,b){this.root=a;this.margin=10;this.ai=b.ai||!1;this.Rz=b.Rz||!1;this.outlineStyle="#333";this.sna="#a0a0a0";this.V0=b.maxSize||30;this.Tq=6;this.IJ=20;this.Nka=.75;this.fontFamily=b.bb;this.tY={};this.Cr={};this.colorType=b.colorType;this.RT=b.RT;this.NZ=b.NZ;this.labels=b.labels;this.backgroundColor=b.backgroundColor||gvjs_Kx;this.Mua=(new gvjs_hy).setColor(gvjs_nt).Mw(this.fontFamily).om(10);this.Fk=new gvjs_B(0,0,0,0);this.JY=!1}gvjs_=gvjs_SX.prototype;
gvjs_.dw=function(a,b,c,d,e,f,g){this.TQ(a,b,c,d,e,f,g?this.root.Wu[g[0]]:this.root)};
gvjs_.TQ=function(a,b,c,d,e,f,g){function h(p,q){p.R.EA=!1;p.R.Xx=[];p.R.gS=void 0;for(var r=0;r<p.ue.length;r++)q(p.ue[r],q)}this.Fk=new gvjs_B(c,b+d,c+e,b);this.root=g||this.root;this.JY=!1;this.root.Ex(function(){this.R=this.R||{}});var k={};if(f)for(var l in f)k[l]=f[l];this.root.Kx(k);h(this.root,h);this.colorType===gvjs_yp?(this.root.Ex(function(){this.min=this.properties.color||0;this.max=this.properties.color||0;for(var p=0;p<this.ue.length;p++)this.min=this.ue[p].min<this.min?this.ue[p].min:
this.min,this.max=this.ue[p].max>this.max?this.ue[p].max:this.max}),this.root.Ex(function(){if(!this.$v()){for(var p=0,q=0,r=0;r<this.ue.length;r++){var t=this.ue[r];q+=t.properties.color*t.weight;p+=t.weight}this.weight=p;this.properties.color=q/p}}),f=this.root.max,k=gvjs_4B(null,this.root.min),k=gvjs_4B(k,f),f=gvjs_WH(this.NZ,k),f=gvjs_s(function(p,q){return gvjs_TH(p,q.properties.color)},this,f)):f=this.colorType===gvjs_KX||"mono"===this.colorType?function(p){return p.properties.color}:function(){return gvjs_ca};
k=c+this.margin;c=c+e-2*this.margin;b=this.ai?b+d:b;d=this.root;e=0;for(l=gvjs_TX(this,c,k,this.root.weight);d.parent&&0<d.parent.label.length;){d=d.parent;var m=this.Dd(d,this.IJ),n=(new gvjs_hy).setColor(gvjs_nt).Mw(this.fontFamily).om(l);null!=d.properties.style&&gvjs_NX(d.properties.style,n);m=a(m,n).width+Math.ceil(l/3);e+=m}b+=(this.ai?-1:1)*e;b+=(this.ai?-1:1)*this.margin;g?gvjs_UX(this,g,b,k,c,a,f):gvjs_UX(this,this.root,b,k,c,a,f)};
function gvjs_TX(a,b,c,d){var e=5*Math.sqrt(b-c);e=Math.min(e,.8*(b-c));1==d&&(e=Math.min(e,2*a.V0/3));e=Math.round(e);e>a.V0&&(e=a.V0);return e}
function gvjs_UX(a,b,c,d,e,f,g){b.R.pza=d;b.R.oza=e;a.colorType==gvjs_yp&&b.ue.sort(function(q,r){return void 0===q.properties.color&&void 0===r.properties.color?0:void 0===q.properties.color?-1:void 0===r.properties.color?1:r.properties.color-q.properties.color});var h=gvjs_TX(a,e,d,b.weight);if(e-d<a.Tq)return b.R.EA=!0,!1;b.R.EA=!1;var k=a.Rz&&b==a.root,l=a.Dd(b,a.IJ);h=(new gvjs_hy).setColor(gvjs_nt).Mw(a.fontFamily).om(h||1);b.R.style=h;k=k?0:f(l,h).width;h=f(l,h).height;b.R.a9?(b.R.width&&(k=
b.R.width),b.R.height&&(h=b.R.height)):b.R.style.color=g(b);null!=b.properties.style&&gvjs_NX(b.properties.style,b.R.style);b.R.x=a.ai?c-k:c;b.R.width=k;b.R.y=(d+e)/2-h/2;b.R.height=h;h=d;l=1==b.ue.length?Math.ceil(b.R.style.fontSize/3):Math.max(60,Math.round(.2*k));c=a.ai?b.R.x-l:c+k+l;if(!a.ai&&c>a.Fk.right||a.ai&&c<a.Fk.left)a.JY=!0;a.Tq&&1<b.ue.length&&(e-=a.Tq);k=[];for(var m=l=0;m<b.ue.length;m++){var n=b.ue[m],p=h+n.weight/b.weight*(e-d);gvjs_UX(a,n,c,h,p,f,g)?h=p:(l+=n.weight,n.R.EA=!0,k.push(n))}a.Tq&&
1<k.length?(m=new gvjs_OX({word:a.ai?k.length+" more...":"... "+k.length+" more"}),m.R={},m.R.Xx=k,m.parent=b,d=l/b.weight*(e-d)*.8,d=d>a.Tq?d:a.Tq+.1,d=d<3*a.Tq?d:3*a.Tq,gvjs_UX(a,m,c,e-d,e,f,g),b.R.gS=m,m.R.height=d,h=5*Math.sqrt(d),h=Math.min(h,.8*d),h=Math.round(h),m.R.style=gvjs_gy((new gvjs_hy(a.Mua)).om(h).setColor("#aaaaaa"),!0),null!=m.properties.style&&gvjs_NX(m.properties.style,m.R.style)):a.Tq&&1==k.length&&(k[0].R.EA=!1,gvjs_UX(a,k[0],c,h,h+a.Tq,f,g));return!0}
gvjs_.Dd=function(a,b){return b?gvjs_Xy(a.label,b):a.label};
gvjs_.draw=function(a,b){a.qc(b);this.element=b.j();this.ht=null;this.tY={};this.Cr={};var c=new gvjs_3;c.Te(this.backgroundColor);a.yb(this.Fk.left,this.Fk.top,this.Fk.La(),this.Fk.getHeight(),c,b);c=this.root;for(var d=c.R.style.fontSize,e=Math.ceil(d/3),f=c.R.x+(this.ai?this.root.R.width+e:0),g=c.R.y,h=c.R.style.color;c.parent&&0<c.parent.label.length;){c=c.parent;var k=this.Dd(c,this.IJ),l=(new gvjs_hy).setColor(h).Mw(this.fontFamily).om(d);null!=c.properties.style&&gvjs_NX(c.properties.style,
l);var m=a.me(k,l);k=m.width;this.ai||(f-=k+e);c.R.style=l;c.R.x=f;c.R.y=g;c.R.height=m.height;c.R.width=m.width;l=a.ce(this.Dd(c,this.IJ),c.R.x,c.R.y,k,gvjs_2,gvjs_2,c.R.style,b);this.ai&&(f+=k+e);l.id=c.id;this.tY[c.id]=l;this.Cr[c.id]=c}this.iC(this.root,a,b);this.JY&&(d=this.ai,e=this.Fk.La()/12,c=new gvjs_3,gvjs_9x(c,{Vf:this.backgroundColor,sf:this.backgroundColor,tn:0,un:1,x1:d?gvjs_Po:gvjs_Oo,x2:d?gvjs_Oo:gvjs_Po,y1:gvjs_Oo,y2:gvjs_Oo,sp:!1,Sn:!0}),a.yb(d?0:this.Fk.right-e,this.Fk.top,e,this.Fk.getHeight(),
c,b))};gvjs_.iC=function(a,b,c){if(!a.R.EA){if(a.R.a9)a.R.a9(a,b);else if(!this.Rz||a!=this.root){a.R.strokeWidth=0;var d=b.ce(this.Dd(a,this.IJ),a.R.x,a.R.y,a.R.width,gvjs_2,gvjs_2,a.R.style,c);d.id=a.id;this.tY[a.id]=d;this.Cr[a.id]=a}for(d=0;d<a.ue.length;d++){var e=a.ue[d];e.R.EA||(gvjs_VX(this,e,a,b,c),this.iC(e,b,c))}a.R.gS&&(gvjs_VX(this,a.R.gS,a,b,c),this.iC(a.R.gS,b,c))}};
function gvjs_VX(a,b,c,d,e){if(!b.R.EA&&1<c.ue.length){var f=a.ai?c.R.x-a.margin:c.R.x+c.R.width+a.margin,g=c.R.y+c.R.height/2-c.R.height/25,h=a.ai?b.R.x+b.R.width+a.margin:b.R.x-a.margin,k=(f+h)/2,l=b.R.y+b.R.height/2,m=new gvjs_OA;m.move(f,g);var n=l+b.R.height/30;c=g+c.R.height/10;m.Jp(k,g,k,l,h,l);m.va(h,n);h=(g-l)/60*(a.ai?-1:1);m.Jp(k+h,n,k+h,c,f,c);m.va(f,g);f=new gvjs_3;null==a.colorType||a.colorType===gvjs_f||"mono"===a.colorType?f.Te(a.sna):f.Te(b.R.style.color);d.Ia(m,f,e)}}
gvjs_.L9=function(a,b){var c=new gvjs_OA;a=a.R;var d=a.y+a.height;c.move(a.x,d);c.va(a.x+a.width,d);a=new gvjs_3;a.rd(this.outlineStyle);b.Ia(c,a,this.ht)};
gvjs_.By=function(a,b,c,d,e){var f=a.tagName.toLowerCase(),g;if(f===gvjs_m||f===gvjs_Nw||"g"===f||f===gvjs_zp){for(;a&&!a.id;)a=gvjs_qh(a);if(g=this.Cr[a.id])return g}else if(f==gvjs_Np&&a.namespaceURI==gvjs_wx){f=a;if(f.parentNode!=this.element&&f.parentNode.parentNode!=this.element)return null;b-=this.element.clientLeft;c-=this.element.clientTop;e=e||0;d=d||this.root;if(b>=d.R.x-e&&b<d.R.x+d.R.width+e&&c>=d.R.y-e&&c<=d.R.y+d.R.height+e)return d;for(f=0;f<d.ue.length;f++)if(g=d.ue[f],c>=g.R.pza-
e&&c<g.R.oza+e&&(g=this.By(a,b,c,g,e)))return g}return null};function gvjs_WX(a){gvjs_SX.call(this,null,a);var b=gvjs_x(a);b.jN=!0;this.BJ=new gvjs_QX(b);this.NS=new gvjs_QX(a);this.options=a;this.m8={color:gvjs_nt,bb:this.fontFamily,fontSize:40,bold:!0,Nc:!1,Ue:!1}}gvjs_o(gvjs_WX,gvjs_SX);gvjs_=gvjs_WX.prototype;gvjs_.tB=function(a,b,c,d,e){this.BJ.tB(a,b,c,d,e);this.NS.tB(a,b,c,d,e)};gvjs_.Ex=function(a){this.BJ.root.Ex(a);this.NS.root.Ex(a)};gvjs_.Kx=function(a){this.BJ.root.Kx(a);this.NS.root.Kx(a)};
gvjs_.TQ=function(a,b,c,d,e,f,g){this.dw(a,b,c,d,e,f,[(g||this.BJ.root).Hp])};
gvjs_.dw=function(a,b,c,d,e,f,g){this.Fk=new gvjs_B(c,b+d,c+e,b);f=f||{};var h=[];g&&(h=Array.isArray(g)?g:[g]);var k=this.BJ.root;this.MW="";for(var l=h.length-1;0<=l;l--)k=k.CC(h[l]);var m=this.NS.root;for(l=0;l<h.length;l++)m=m.CC(h[l]);if(!k&&!m)throw Error("Word "+g+" not present in word tree.");m=m||new gvjs_OX;k=k||new gvjs_OX;this.MW=h.join(" ");h={};if(f)for(var n in f)h[n]=f[n];k.Kx(h);m.Kx(h);n=gvjs_x(this.options);n.Rz=!0;n.ai=!0;g=gvjs_x(this.options);g.Rz=!0;this.Gz=new gvjs_SX(k,n);
this.vE=new gvjs_SX(m,g);n=(5+(e-10))/2;l=a(this.MW,this.m8);g=d-(l.width+5);this.pla=g/2+2.5;this.qla=(e-l.height)/2-8;this.ola=l.width;this.Gz.dw(a,b,c,g/2,e,h);this.vE.dw(a,b+g/2,c,g/2,e,h);b=Math.max(k.weight,m.weight);c=n-5;k=c*k.weight/b;m=c*m.weight/b;this.Gz.dw(a,0,n-k,g/2,2*k,f);this.vE.dw(a,this.Fk.La()-g/2,n-m,g/2,2*m,f);this.ya=new gvjs_A(d,e)};
gvjs_.draw=function(a,b){a.qc(b);this.ht=null;var c=a.Sa(),d=a.Sa();a.appendChild(b,c);a.appendChild(b,d);a.ce(this.MW,this.pla,this.qla,this.ola,gvjs_2,gvjs_2,this.m8,b);this.Gz.draw(a,c);this.vE.draw(a,d);for(var e in this.Gz.Cr)this.Cr[e]=this.Gz.Cr[e];for(e in this.vE.Cr)this.Cr[e]=this.vE.Cr[e]};gvjs_.By=function(a,b,c,d,e){return this.Gz.By(a,b,c,null,e)||this.vE.By(a,b,c,null,e)};function gvjs_XX(a,b){this.root=a;this.O9=b}gvjs_=gvjs_XX.prototype;gvjs_.dw=function(){};gvjs_.TQ=function(){};gvjs_.draw=function(){gvjs_hh(this.O9);this.iC(this.root,this.O9)};gvjs_.iC=function(a,b){a.Hp&&b.appendChild(gvjs_4("LI",{},document.createTextNode(String(a.Hp+" ("+a.weight+")"))));var c=gvjs_4("UL");b.appendChild(c);for(var d in a.Wu)this.iC(a.Wu[d],c)};gvjs_.L9=function(a){a.R.element.style[gvjs_yu]=gvjs_ot};gvjs_.By=function(){return null};function gvjs_YX(a,b,c,d,e,f,g){gvjs_F.call(this);this.F=a;this.ek=this.wm=null;this.ga=d;this.Pa=e;this.If=b;this.xj=c;this.Wga=g;this.A3=f;a=this.F.Lm(this.ga,this.Pa);if(null==a)throw"Error creating canvas element.";this.te=a;this.Um=this.F.Sa()}gvjs_o(gvjs_YX,gvjs_F);gvjs_YX.prototype.M=function(){this.F.clear();delete this.F;gvjs_F.prototype.M.call(this)};gvjs_YX.prototype.update=function(a){a?gvjs_ZX(this,a):gvjs_ZX(this,this.node)};
gvjs_YX.prototype.et=function(a){!(a=this.wm.By(a.target,a.clientX,a.clientY,this.ek))||a.R.Xx&&0<a.R.Xx.length||(a==this.ek?this.ek&&this.ek.parent&&(this.update(this.ek.parent),this.A3(gvjs_k,{word:this.ek.Hp,weight:this.ek.weight,color:this.ek.properties.color})):(this.update(a),this.A3(gvjs_k,{})))};
gvjs_YX.prototype.WP=function(a){a=this.wm.By(a.target,a.clientX,a.clientY,this.ek);if(!a||a.R.Xx&&0<a.R.Xx.length){if(a=this.wm,a.ht)for(a=a.ht.j();a.firstChild;)a.removeChild(a.firstChild)}else{var b=this.wm,c=this.F,d=this.Um;if(b.ht)for(d=b.ht.j();d.firstChild;)d.removeChild(d.firstChild);else b.ht=c.Sa(),c.appendChild(d,b.ht);d=gvjs_fy((new gvjs_hy).setColor(gvjs_nt).Mw(b.fontFamily).om(13),!0);var e=gvjs_fy(new gvjs_hy(d),!1),f=[gvjs_dG(a.Hp,e)];a.R.Xx&&0<a.R.Xx.length||(f.push(gvjs_dG(a.weight+
"",d,b.labels[0],e)),b.colorType!=gvjs_yp&&b.colorType!=gvjs_KX||f.push(gvjs_dG(a.properties.color+"",d,b.labels[1],e)));d=gvjs_gG({entries:f},gvjs_s(c.me,c),!0,new gvjs_z(a.R.x,a.R.y+a.R.height*b.Nka),b.Fk,new gvjs_z(a.R.x+a.R.width/2,a.R.y+a.R.height/2));gvjs_FG(d,c,b.ht);this.wm.L9(a,this.F)}};function gvjs_ZX(a,b){typeof b===gvjs_l&&(b=gvjs_PX(a.ek).Wu[b]);a.ek=b;var c=gvjs_s(a.F.me,a.F);a.wm.TQ(c,a.If,a.xj,a.ga,a.Pa,null,b);a.wm.draw(a.F,a.Um)}gvjs_q("gviz.wordtree.TreeEvents",gvjs_YX,void 0);function gvjs__X(a){gvjs_Nn.call(this,a);gvjs_C(a,"lineHeight",gvjs_Xv);this.p0=this.tree=this.j9=this.yy=null;this.fca=gvjs_Kd}gvjs_o(gvjs__X,gvjs_Nn);gvjs_=gvjs__X.prototype;
gvjs_.Rd=function(a,b,c){c=new gvjs_yj([c,gvjs_RX]);var d=this.La(c,900),e=this.getHeight(c,600);if(this.ab)this.ab.update(new gvjs_A(d,e),a);else{var f=gvjs_K(c,gvjs_Au);this.ab=new gvjs__B(this.container,new gvjs_A(d,e),a,f)}f=c.cb("wordtree.format",gvjs_zka);var g=(new gvjs_LX).Ac(b,f);if(null!=g.columns.color)if(f=b.W(g.columns.color),f===gvjs_l){gvjs_4x(this.Hg,"The string color column format is deprecated, please use style role instead.",!1);var h=gvjs_KX}else f===gvjs_g&&(h=gvjs_yp);else h=
gvjs_J(c,"colors.0")!==gvjs_RX.colors[0]?"mono":gvjs_f;var k=h!==gvjs_yp?gvjs_Dj(c,gvjs_Gj,[],gvjs_Zt,void 0,void 0)[0]:null;f=null!=g.columns.color&&b.Ga(g.columns.color)||gvjs_4r;var l=[null!=g.columns.weight&&b.Ga(g.columns.weight)||"Weight",f];f=gvjs_J(c,"wordtree.renderer",gvjs_Zd,gvjs_Eka);var m=gvjs_J(c,"wordtree.type",gvjs_Kd,gvjs_Dka),n=gvjs_L(c,"maxFontSize",36),p=gvjs_J(c,gvjs_vp);h={NZ:h===gvjs_yp?c:null,format:g,maxSize:n,RT:k,colorType:h,labels:l,Rz:!1,bb:p,ai:m==gvjs_wd,iT:c.fa("wordtree.sentenceSeparator"),
ZU:c.fa("wordtree.wordSeparator"),backgroundColor:gvjs_ky(c,gvjs_dt,gvjs_Kx)};k=gvjs_pe(b);if(!(l=k!=this.j9||m!=this.fca||!this.p0)){a:{l=this.p0;for(q in h)if(!(q in l)||h[q]!==l[q]){var q=!1;break a}for(var r in l)if(!(r in h)){q=!1;break a}q=!0}l=!q}if(l)if(this.j9=k,this.p0=h,this.fca=m,g.format==gvjs_ou){q=h.format;r={};g=null!=q.columns.color;m=null!=q.columns.style;for(k=0;k<b.ca();++k){l=b.getValue(k,q.columns.id);n=b.getValue(k,q.columns.Hp);p=b.getValue(k,q.columns.weight);if(0>=p)throw Error(gvjs_GX+
k+").");var t=g?b.getValue(k,q.columns.color):"mono"===h.colorType?h.RT:gvjs_nt;var u=m?b.getStringValue(k,q.columns.style):null;u=null!=u?new gvjs_yj([gvjs_8I(u,gvjs_MX)]):null;n=new gvjs_OX({label:n,word:n,weight:p,properties:{color:t,style:u}});if(r[l])throw Error("Non-unique ID: id "+l+" found again at row "+k+".");r[l]=n}for(g=0;g<b.ca();++g)m=b.getValue(g,q.columns.parent),0<=m&&(m=r[m],k=r[b.getValue(g,q.columns.id)],m.addChild(k),k.parent=m);this.tree=r[0]}else this.tree=this.xW(b,m,h),this.tree.root&&
(this.tree=this.tree.root);"texttree"==f?(new gvjs_XX(this.tree.root?this.tree.root:this.tree,this.container)).draw():this.ab.rl(gvjs_s(this.Cxa,this,d,e,gvjs_re(gvjs_I,this),c.fa("wordtree.word"),this.tree,h),a)};
gvjs_.Cxa=function(a,b,c,d,e,f){var g=this.ab.Oa();gvjs_E(this.yy);a=this.yy=new gvjs_YX(g,0,0,a,b,c,f);e instanceof gvjs_SX?a.wm=e:(a.Wga.Rz=!1,a.wm=new gvjs_SX(e,a.Wga));e=gvjs_s(a.F.me,a.F);a.wm.dw(e,a.If,a.xj,a.ga,a.Pa,null,[d]);a.F.appendChild(a.te,a.Um);a.wm.draw(a.F,a.Um);a.ek=a.wm.root||a.wm.Gz.root;d=new gvjs_3;d.mf(0);d.Te(gvjs_f);gvjs_7x(d,0);d.rd(gvjs_f);e=a.F.Sa();a.F.appendChild(a.te,e);a.F.yb(0,0,a.ga,a.Pa,d,e);d=a.te.j();a.F.ic(d,gvjs_St,gvjs_s(a.et,a));a.F.ic(d,gvjs_jd,gvjs_s(a.WP,
a));a.F.ic(d,gvjs_ld,gvjs_s(a.WP,a));a.A3(gvjs_i,{})};
gvjs_.xW=function(a,b,c){b==gvjs_Kd||b==gvjs_wd?(c.jN=b==gvjs_wd,b=new gvjs_QX(c)):b=new gvjs_WX(c);for(var d=c.format,e=null!=d.columns.weight,f=null!=d.columns.color,g=null!=d.columns.style,h=0;h<a.ca();++h){var k=e?a.getValue(h,d.columns.weight):1;if(0>=k)throw Error(gvjs_GX+h+").");var l=a.getValue(h,c.format.columns.text);var m=f?a.getValue(h,d.columns.color):"mono"===c.colorType?c.RT:gvjs_nt;var n=g?new gvjs_yj([gvjs_8I(a.getStringValue(h,d.columns.style),gvjs_MX)]):null;b.tB(l,k,!0,m,n)}return b};
gvjs_.getSelection=function(){var a=this.yy;return{word:a.ek.Hp,weight:a.ek.weight,color:a.ek.properties.color}};gvjs_.setSelection=function(a){gvjs_ZX(this.yy,a)};gvjs_.M=function(){gvjs_E(this.yy);delete this.yy;gvjs_E(this.ab);delete this.ab;gvjs_Nn.prototype.M.call(this)};gvjs_.He=function(){};gvjs_q(gvjs_0c,gvjs__X,void 0);gvjs__X.prototype.draw=gvjs__X.prototype.draw;gvjs__X.prototype.clearChart=gvjs__X.prototype.Jb;gvjs__X.prototype.getSelection=gvjs__X.prototype.getSelection;gvjs__X.prototype.setSelection=gvjs__X.prototype.setSelection;
