var gvjs_gQ="#990000",gvjs_hQ="annotationText",gvjs_iQ="certainty";gvjs_gL.prototype.Jm=gvjs_V(70,function(a,b){if(this.Xg===gvjs_dw)return this.av(a,b);throw Error(gvjs_3r);});gvjs_hL.prototype.Jm=gvjs_V(69,function(a,b){return this.av(a,b)});function gvjs_jQ(a){var b=new gvjs_ME;b.sa=function(){return a};return b}function gvjs_kQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_9s,gvjs_S)}gvjs_o(gvjs_kQ,gvjs_gL);function gvjs_lQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_2w,gvjs_S)}gvjs_o(gvjs_lQ,gvjs_gL);
function gvjs_mQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_f,gvjs_S,"sparkline")}gvjs_o(gvjs_mQ,gvjs_gL);function gvjs_nQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_e,gvjs_S)}gvjs_o(gvjs_nQ,gvjs_gL);function gvjs_oQ(a){gvjs_gL.call(this,a);this.cc(gvjs_Ed)}gvjs_o(gvjs_oQ,gvjs_gL);gvjs_oQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_pQ(a){gvjs_gL.call(this,a);this.cc(gvjs_wt)}gvjs_o(gvjs_pQ,gvjs_gL);function gvjs_qQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_jt,gvjs_U)}
gvjs_o(gvjs_qQ,gvjs_gL);gvjs_qQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_rQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_Dt,gvjs_S)}gvjs_o(gvjs_rQ,gvjs_gL);function gvjs_sQ(a){gvjs_gL.call(this,a);this.cc(gvjs_d,gvjs_jt,gvjs_S)}gvjs_o(gvjs_sQ,gvjs_gL);gvjs_sQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_tQ(a){gvjs_gL.call(this,a);this.cc(gvjs_2u,gvjs_jt,gvjs_S)}gvjs_o(gvjs_tQ,gvjs_gL);gvjs_q(gvjs_gc,gvjs_gL,void 0);gvjs_gL.prototype.draw=gvjs_gL.prototype.draw;
gvjs_gL.prototype.clearChart=gvjs_gL.prototype.Jb;gvjs_gL.prototype.getImageURI=gvjs_gL.prototype.ah;gvjs_gL.prototype.getSelection=gvjs_gL.prototype.getSelection;gvjs_gL.prototype.setSelection=gvjs_gL.prototype.setSelection;gvjs_gL.prototype.dump=gvjs_gL.prototype.dump;gvjs_gL.prototype.getChartLayoutInterface=gvjs_gL.prototype.Ql;gvjs_gL.prototype.getContainer=gvjs_gL.prototype.getContainer;gvjs_gL.prototype.setAction=gvjs_gL.prototype.xh;gvjs_gL.prototype.getAction=gvjs_gL.prototype.ng;
gvjs_gL.prototype.removeAction=gvjs_gL.prototype.th;gvjs_q(gvjs_5b,gvjs_kQ,void 0);gvjs_kQ.prototype.draw=gvjs_kQ.prototype.draw;gvjs_kQ.prototype.clearChart=gvjs_kQ.prototype.Jb;gvjs_kQ.prototype.getImageURI=gvjs_kQ.prototype.ah;gvjs_kQ.prototype.getSelection=gvjs_kQ.prototype.getSelection;gvjs_kQ.prototype.setSelection=gvjs_kQ.prototype.setSelection;gvjs_kQ.prototype.setAction=gvjs_kQ.prototype.xh;gvjs_kQ.prototype.getAction=gvjs_kQ.prototype.ng;gvjs_kQ.prototype.removeAction=gvjs_kQ.prototype.th;
gvjs_q(gvjs_6b,gvjs_qQ,void 0);gvjs_qQ.prototype.computeDiff=gvjs_qQ.prototype.Jm;gvjs_qQ.prototype.draw=gvjs_qQ.prototype.draw;gvjs_qQ.prototype.clearChart=gvjs_qQ.prototype.Jb;gvjs_qQ.prototype.getImageURI=gvjs_qQ.prototype.ah;gvjs_qQ.prototype.getSelection=gvjs_qQ.prototype.getSelection;gvjs_qQ.prototype.setSelection=gvjs_qQ.prototype.setSelection;gvjs_qQ.prototype.setAction=gvjs_qQ.prototype.xh;gvjs_qQ.prototype.getAction=gvjs_qQ.prototype.ng;gvjs_qQ.prototype.removeAction=gvjs_qQ.prototype.th;
gvjs_q(gvjs_7b,gvjs_pQ,void 0);gvjs_pQ.prototype.draw=gvjs_pQ.prototype.draw;gvjs_pQ.prototype.clearChart=gvjs_pQ.prototype.Jb;gvjs_pQ.prototype.getImageURI=gvjs_pQ.prototype.ah;gvjs_pQ.prototype.getSelection=gvjs_pQ.prototype.getSelection;gvjs_pQ.prototype.setSelection=gvjs_pQ.prototype.setSelection;gvjs_pQ.prototype.setAction=gvjs_pQ.prototype.xh;gvjs_pQ.prototype.getAction=gvjs_pQ.prototype.ng;gvjs_pQ.prototype.removeAction=gvjs_pQ.prototype.th;gvjs_q(gvjs_9b,gvjs_rQ,void 0);
gvjs_rQ.prototype.draw=gvjs_rQ.prototype.draw;gvjs_rQ.prototype.clearChart=gvjs_rQ.prototype.Jb;gvjs_rQ.prototype.getImageURI=gvjs_rQ.prototype.ah;gvjs_rQ.prototype.getSelection=gvjs_rQ.prototype.getSelection;gvjs_rQ.prototype.setSelection=gvjs_rQ.prototype.setSelection;gvjs_rQ.prototype.setAction=gvjs_rQ.prototype.xh;gvjs_rQ.prototype.getAction=gvjs_rQ.prototype.ng;gvjs_rQ.prototype.removeAction=gvjs_rQ.prototype.th;gvjs_q(gvjs_sc,gvjs_tQ,void 0);gvjs_tQ.prototype.draw=gvjs_tQ.prototype.draw;
gvjs_tQ.prototype.clearChart=gvjs_tQ.prototype.Jb;gvjs_tQ.prototype.getImageURI=gvjs_tQ.prototype.ah;gvjs_tQ.prototype.getSelection=gvjs_tQ.prototype.getSelection;gvjs_tQ.prototype.setSelection=gvjs_tQ.prototype.setSelection;gvjs_tQ.prototype.setAction=gvjs_tQ.prototype.xh;gvjs_tQ.prototype.getAction=gvjs_tQ.prototype.ng;gvjs_tQ.prototype.removeAction=gvjs_tQ.prototype.th;gvjs_q(gvjs_dc,gvjs_sQ,void 0);gvjs_sQ.prototype.computeDiff=gvjs_sQ.prototype.Jm;gvjs_sQ.prototype.draw=gvjs_sQ.prototype.draw;
gvjs_sQ.prototype.clearChart=gvjs_sQ.prototype.Jb;gvjs_sQ.prototype.getImageURI=gvjs_sQ.prototype.ah;gvjs_sQ.prototype.getSelection=gvjs_sQ.prototype.getSelection;gvjs_sQ.prototype.setSelection=gvjs_sQ.prototype.setSelection;gvjs_sQ.prototype.setAction=gvjs_sQ.prototype.xh;gvjs_sQ.prototype.getAction=gvjs_sQ.prototype.ng;gvjs_sQ.prototype.removeAction=gvjs_sQ.prototype.th;gvjs_q(gvjs_fc,gvjs_pL,void 0);gvjs_pL.prototype.draw=gvjs_pL.prototype.draw;gvjs_pL.prototype.clearChart=gvjs_pL.prototype.Jb;
gvjs_pL.prototype.getImageURI=gvjs_pL.prototype.ah;gvjs_pL.prototype.getSelection=gvjs_pL.prototype.getSelection;gvjs_pL.prototype.setSelection=gvjs_pL.prototype.setSelection;gvjs_pL.prototype.setAction=gvjs_pL.prototype.xh;gvjs_pL.prototype.getAction=gvjs_pL.prototype.ng;gvjs_pL.prototype.removeAction=gvjs_pL.prototype.th;gvjs_q(gvjs_Ac,gvjs_nQ,void 0);gvjs_nQ.prototype.draw=gvjs_nQ.prototype.draw;gvjs_nQ.prototype.clearChart=gvjs_nQ.prototype.Jb;gvjs_nQ.prototype.getImageURI=gvjs_nQ.prototype.ah;
gvjs_nQ.prototype.getSelection=gvjs_nQ.prototype.getSelection;gvjs_nQ.prototype.setSelection=gvjs_nQ.prototype.setSelection;gvjs_nQ.prototype.setAction=gvjs_nQ.prototype.xh;gvjs_nQ.prototype.getAction=gvjs_nQ.prototype.ng;gvjs_nQ.prototype.removeAction=gvjs_nQ.prototype.th;gvjs_q(gvjs_Kc,gvjs_hL,void 0);gvjs_hL.prototype.computeDiff=gvjs_hL.prototype.Jm;gvjs_hL.prototype.draw=gvjs_hL.prototype.draw;gvjs_hL.prototype.clearChart=gvjs_hL.prototype.Jb;gvjs_hL.prototype.getImageURI=gvjs_hL.prototype.ah;
gvjs_hL.prototype.getSelection=gvjs_hL.prototype.getSelection;gvjs_hL.prototype.setSelection=gvjs_hL.prototype.setSelection;gvjs_hL.prototype.setAction=gvjs_hL.prototype.xh;gvjs_hL.prototype.getAction=gvjs_hL.prototype.ng;gvjs_hL.prototype.removeAction=gvjs_hL.prototype.th;gvjs_q(gvjs_Oc,gvjs_oQ,void 0);gvjs_oQ.prototype.computeDiff=gvjs_oQ.prototype.Jm;gvjs_oQ.prototype.draw=gvjs_oQ.prototype.draw;gvjs_oQ.prototype.clearChart=gvjs_oQ.prototype.Jb;gvjs_oQ.prototype.getImageURI=gvjs_oQ.prototype.ah;
gvjs_oQ.prototype.getSelection=gvjs_oQ.prototype.getSelection;gvjs_oQ.prototype.setSelection=gvjs_oQ.prototype.setSelection;gvjs_oQ.prototype.setAction=gvjs_oQ.prototype.xh;gvjs_oQ.prototype.getAction=gvjs_oQ.prototype.ng;gvjs_oQ.prototype.removeAction=gvjs_oQ.prototype.th;gvjs_q(gvjs_Qc,gvjs_mQ,void 0);gvjs_mQ.prototype.draw=gvjs_mQ.prototype.draw;gvjs_mQ.prototype.clearChart=gvjs_mQ.prototype.Jb;gvjs_mQ.prototype.getImageURI=gvjs_mQ.prototype.ah;gvjs_mQ.prototype.getSelection=gvjs_mQ.prototype.getSelection;
gvjs_mQ.prototype.setSelection=gvjs_mQ.prototype.setSelection;gvjs_mQ.prototype.setAction=gvjs_mQ.prototype.xh;gvjs_mQ.prototype.getAction=gvjs_mQ.prototype.ng;gvjs_mQ.prototype.removeAction=gvjs_mQ.prototype.th;gvjs_q(gvjs_Rc,gvjs_lQ,void 0);gvjs_lQ.prototype.draw=gvjs_lQ.prototype.draw;gvjs_lQ.prototype.clearChart=gvjs_lQ.prototype.Jb;gvjs_lQ.prototype.getImageURI=gvjs_lQ.prototype.ah;gvjs_lQ.prototype.getSelection=gvjs_lQ.prototype.getSelection;gvjs_lQ.prototype.setSelection=gvjs_lQ.prototype.setSelection;
gvjs_lQ.prototype.setAction=gvjs_lQ.prototype.xh;gvjs_lQ.prototype.getAction=gvjs_lQ.prototype.ng;gvjs_lQ.prototype.removeAction=gvjs_lQ.prototype.th;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_uQ(a,b,c,d){gvjs_oC.call(this,a,b,c,null,d)}gvjs_t(gvjs_uQ,gvjs_oC);gvjs_uQ.prototype.rg=function(){do gvjs_uQ.G.next.call(this);while(-1==this.tj);return this.node};gvjs_uQ.prototype.next=gvjs_uQ.prototype.rg;gvjs_fh(gvjs_b);function gvjs_vQ(a){return(new gvjs_vm).cd().sanitize(a)};
