/*


 Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
gvjs_XL.prototype.MB=gvjs_V(77,function(a,b,c,d){for(var e=a.call(d,this),f=[],g=this.getChildren(),h=0;h<g.length;h++){var k=g[h].MB(a,b,c,d);f.push(k)}a=b.call(d,e,f);c&&c.call(d,this,a);return a});gvjs__L.prototype.MB=gvjs_V(76,function(a,b,c,d){for(var e=this.ep,f=0;f<e.length;f++)e[f].MB(a,b,c,d)});gvjs_gB.prototype.FT=gvjs_V(40,function(a){var b=this.j();b&&gvjs_cg(b,a)});function gvjs_xW(a,b){return gvjs_yh(b,function(c){return"SVG"==c.nodeName&&!0},!0,void 0)}
function gvjs_yW(a,b,c){c=a.MY.splice(c||0)[0];(c=a.Am=a.Am||c)?c.Jba?a.Fi=a.Lx||a.Ws:void 0!=c.hh&&a.Ws<c.hh?(a.Fi=c.hh,a.Am=null):a.Fi=a.Ws:a.Fi=b}function gvjs__ja(a,b){var c=void 0;return new (c||(c=Promise))(function(d,e){function f(k){try{h(b.next(k))}catch(l){e(l)}}function g(k){try{h(b["throw"](k))}catch(l){e(l)}}function h(k){k.done?d(k.value):(new c(function(l){l(k.value)})).then(f,g)}h((b=b.apply(a,void 0)).next())})}function gvjs_zW(a){gvjs_u(a,function(){})}
function gvjs_AW(a,b){gvjs_zW(b);return 0==b.length?null===a?0:a:gvjs_Ee(b,function(c,d){return c+d},0)}function gvjs_0ja(a,b){gvjs_zW(b);if(0==b.length)return a;b=gvjs_De(b,function(c){return null!=c});return 0==b.length?null:gvjs_AW(a,b)/b.length}var gvjs_BW=!0,gvjs_CW={set Ep(a){a?console.warn("DEPRECATED! RxJS was set to use deprecated synchronous error handling behavior by code at: \n"+Error().stack):gvjs_BW&&console.log("RxJS: Back to a better error behavior. Thank you. <3");gvjs_BW=a},get Ep(){return gvjs_BW}};var gvjs_DW=typeof Symbol===gvjs_d&&Symbol.observable||"@@observable";function gvjs_EW(a){setTimeout(function(){throw a;},0)};var gvjs_FW={closed:!0,next:function(){},error:function(a){if(gvjs_CW.Ep)throw a;gvjs_EW(a)},complete:function(){}};var gvjs_GW=function(){function a(b){this.message=b?b.length+" errors occurred during unsubscription:\n"+b.map(function(c,d){return d+1+") "+c.toString()}).join("\n  "):"";this.name="UnsubscriptionError";this.errors=b;return this}a.prototype=Object.create(Error.prototype);return a}();var gvjs_1ja=Array.isArray||function(a){return a&&typeof a.length===gvjs_g};function gvjs_HW(a){this.closed=!1;this.oB=this.xu=null;a&&(this.JV=a)}
gvjs_HW.prototype.unsubscribe=function(){if(!this.closed){var a=this.xu,b=this.JV,c=this.oB;this.closed=!0;this.oB=this.xu=null;if(a instanceof gvjs_HW)a.remove(this);else if(null!==a)for(var d=0;d<a.length;++d)a[d].remove(this);if(typeof b===gvjs_d)try{b.call(this)}catch(h){var e=h instanceof gvjs_GW?gvjs_IW(h.errors):[h]}if(gvjs_1ja(c)){d=-1;for(var f=c.length;++d<f;){var g=c[d];if(null!==g&&typeof g===gvjs_h)try{g.unsubscribe()}catch(h){e=e||[],h instanceof gvjs_GW?e=e.concat(gvjs_IW(h.errors)):
e.push(h)}}}if(e)throw new gvjs_GW(e);}};gvjs_HW.prototype.add=function(a){gvjs_2ja(this,a)};
function gvjs_2ja(a,b){var c=b;if(b){switch(typeof b){case gvjs_d:c=new gvjs_HW(b);case gvjs_h:if(c===a||c.closed||typeof c.unsubscribe!==gvjs_d)return;if(a.closed){c.unsubscribe();return}c instanceof gvjs_HW||(b=c,c=new gvjs_HW,c.oB=[b]);break;default:throw Error("unrecognized teardown "+b+" added to Subscription.");}var d=c.xu;if(null===d)c.xu=a;else if(d instanceof gvjs_HW){if(d===a)return;c.xu=[d,a]}else if(-1===d.indexOf(a))d.push(a);else return;b=a.oB;null===b?a.oB=[c]:b.push(c)}}
gvjs_HW.prototype.remove=function(a){var b=this.oB;b&&(a=b.indexOf(a),-1!==a&&b.splice(a,1))};var gvjs_JW=new gvjs_HW;gvjs_JW.closed=!0;gvjs_HW.EMPTY=gvjs_JW;function gvjs_IW(a){return a.reduce(function(b,c){return b.concat(c instanceof gvjs_GW?c.errors:c)},[])};var gvjs_KW=typeof Symbol===gvjs_d?Symbol("rxSubscriber"):"@@rxSubscriber_"+Math.random();function gvjs_LW(a,b,c){gvjs_HW.call(this);this.hU=null;this.Ef=this.Nn=this.gU=!1;switch(arguments.length){case 0:this.destination=gvjs_FW;break;case 1:if(!a){this.destination=gvjs_FW;break}if(typeof a===gvjs_h){a instanceof gvjs_LW?(this.Nn=a.Nn,this.destination=a,a.add(this)):(this.Nn=!0,this.destination=new gvjs_MW(this,a));break}default:this.Nn=!0,this.destination=new gvjs_MW(this,a,b,c)}}gvjs_o(gvjs_LW,gvjs_HW);gvjs_LW.EMPTY=gvjs_HW.EMPTY;gvjs_LW.prototype[gvjs_KW]=function(){return this};
gvjs_LW.create=function(a,b,c){a=new gvjs_LW(a,b,c);a.Nn=!1;return a};gvjs_=gvjs_LW.prototype;gvjs_.next=function(a){this.Ef||this.Xn(a)};gvjs_.error=function(a){this.Ef||(this.Ef=!0,this.nB(a))};gvjs_.complete=function(){this.Ef||(this.Ef=!0,this.xx())};gvjs_.unsubscribe=function(){this.closed||(this.Ef=!0,gvjs_HW.prototype.unsubscribe.call(this))};gvjs_.Xn=function(a){this.destination.next(a)};gvjs_.nB=function(a){this.destination.error(a);this.unsubscribe()};
gvjs_.xx=function(){this.destination.complete();this.unsubscribe()};gvjs_.$Ba=function(){var a=this.xu;this.xu=null;this.unsubscribe();this.Ef=this.closed=!1;this.xu=a;return this};
function gvjs_MW(a,b,c,d){gvjs_LW.call(this);this.bG=a;var e=this;if(typeof b===gvjs_d)var f=b;else b&&(f=b.next,c=b.error,d=b.complete,b!==gvjs_FW&&(e=Object.create(b),b&&typeof b.add===gvjs_d&&typeof b.unsubscribe===gvjs_d&&b.add(this.unsubscribe.bind(this)),e.unsubscribe=this.unsubscribe.bind(this)));this.QM=e;this.Xn=f;this.nB=c;this.xx=d}gvjs_o(gvjs_MW,gvjs_LW);gvjs_MW.EMPTY=gvjs_LW.EMPTY;gvjs_MW.create=gvjs_LW.create;gvjs_=gvjs_MW.prototype;
gvjs_.next=function(a){if(!this.Ef&&this.Xn){var b=this.bG;gvjs_CW.Ep&&b.Nn?this.GV(b,this.Xn,a)&&this.unsubscribe():this.HV(this.Xn,a)}};gvjs_.error=function(a){if(!this.Ef){var b=this.bG,c=gvjs_CW.Ep;if(this.nB)c&&b.Nn?this.GV(b,this.nB,a):this.HV(this.nB,a),this.unsubscribe();else if(b.Nn)c?(b.hU=a,b.gU=!0):gvjs_EW(a),this.unsubscribe();else{this.unsubscribe();if(c)throw a;gvjs_EW(a)}}};
gvjs_.complete=function(){var a=this;if(!this.Ef){var b=this.bG;if(this.xx){var c=function(){return a.xx.call(a.QM)};gvjs_CW.Ep&&b.Nn?this.GV(b,c):this.HV(c)}this.unsubscribe()}};gvjs_.HV=function(a,b){try{a.call(this.QM,b)}catch(c){this.unsubscribe();if(gvjs_CW.Ep)throw c;gvjs_EW(c)}};gvjs_.GV=function(a,b,c){if(!gvjs_CW.Ep)throw Error("bad call");try{b.call(this.QM,c)}catch(d){return gvjs_CW.Ep?(a.hU=d,a.gU=!0):gvjs_EW(d),!0}return!1};gvjs_.JV=function(){var a=this.bG;this.bG=this.QM=null;a.unsubscribe()};function gvjs_NW(a){return a};function gvjs_3ja(a){return 0===a.length?gvjs_NW:1===a.length?a[0]:function(b){return a.reduce(function(c,d){return d(c)},b)}};function gvjs_OW(a){this.ZBa=!1;a&&(this.cG=a)}gvjs_=gvjs_OW.prototype;gvjs_.EJ=function(a){var b=new gvjs_OW;b.source=this;b.operator=a;return b};gvjs_.subscribe=function(a,b,c){var d=this.operator;a:{if(a){if(a instanceof gvjs_LW)break a;if(a[gvjs_KW]){a=a[gvjs_KW]();break a}}a=a||b||c?new gvjs_LW(a,b,c):new gvjs_LW(gvjs_FW)}d?a.add(d.call(a,this.source)):a.add(this.source||gvjs_CW.Ep&&!a.Nn?this.cG(a):this.IV(a));if(gvjs_CW.Ep&&a.Nn&&(a.Nn=!1,a.gU))throw a.hU;return a};
gvjs_.IV=function(a){try{return this.cG(a)}catch(e){gvjs_CW.Ep&&(a.gU=!0,a.hU=e);var b;a:{for(b=a;b;){var c=b.destination,d=b.Ef;if(b.closed||d){b=!1;break a}b=c&&c instanceof gvjs_LW?c:null}b=!0}b?a.error(e):console.warn(e)}};gvjs_.forEach=function(a,b){var c=this;b=gvjs_4ja(b);return new b(function(d,e){var f=c.subscribe(function(g){try{a(g)}catch(h){e(h),f&&f.unsubscribe()}},e,d)})};gvjs_.cG=function(a){var b=this.source;return b&&b.subscribe(a)};gvjs_OW.prototype[gvjs_DW]=function(){return this};
gvjs_OW.prototype.p2=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return 0===b.length?this:gvjs_3ja(b)(this)};gvjs_OW.create=function(a){return new gvjs_OW(a)};function gvjs_4ja(a){a||(a=Promise);if(!a)throw Error("no Promise impl found");return a};function gvjs_PW(a,b){gvjs_HW.call(this);this.subject=a;this.Fxa=b;this.closed=!1}gvjs_o(gvjs_PW,gvjs_HW);gvjs_PW.EMPTY=gvjs_HW.EMPTY;gvjs_PW.prototype.unsubscribe=function(){if(!this.closed){this.closed=!0;var a=this.subject,b=a.xw;this.subject=null;!b||0===b.length||a.Ef||a.closed||(a=b.indexOf(this.Fxa),-1!==a&&b.splice(a,1))}};var gvjs_QW=function(){function a(){this.message="object unsubscribed";this.name="ObjectUnsubscribedError";return this}a.prototype=Object.create(Error.prototype);return a}();function gvjs_RW(a){gvjs_LW.call(this,a);this.destination=a}gvjs_o(gvjs_RW,gvjs_LW);gvjs_RW.EMPTY=gvjs_LW.EMPTY;gvjs_RW.create=gvjs_LW.create;function gvjs_SW(){gvjs_OW.call(this);this.xw=[];this.Vaa=this.Ef=this.closed=!1;this.Aga=null}gvjs_o(gvjs_SW,gvjs_OW);gvjs_SW.prototype[gvjs_KW]=function(){return new gvjs_RW(this)};gvjs_=gvjs_SW.prototype;gvjs_.EJ=function(a){var b=new gvjs_TW(this,this);b.operator=a;return b};
gvjs_.next=function(a){if(this.closed)throw new gvjs_QW;if(!this.Ef){var b=this.xw,c=b.length;b=b.slice();for(var d=0;d<c;d++)b[d].next(a)}};gvjs_.error=function(a){if(this.closed)throw new gvjs_QW;this.Vaa=!0;this.Aga=a;this.Ef=!0;var b=this.xw,c=b.length;b=b.slice();for(var d=0;d<c;d++)b[d].error(a);this.xw.length=0};gvjs_.complete=function(){if(this.closed)throw new gvjs_QW;this.Ef=!0;var a=this.xw,b=a.length;a=a.slice();for(var c=0;c<b;c++)a[c].complete();this.xw.length=0};
gvjs_.unsubscribe=function(){this.closed=this.Ef=!0;this.xw=null};gvjs_.IV=function(a){if(this.closed)throw new gvjs_QW;return gvjs_OW.prototype.IV.call(this,a)};gvjs_.cG=function(a){if(this.closed)throw new gvjs_QW;if(this.Vaa)return a.error(this.Aga),gvjs_HW.EMPTY;if(this.Ef)return a.complete(),gvjs_HW.EMPTY;this.xw.push(a);return new gvjs_PW(this,a)};gvjs_SW.create=function(a,b){return new gvjs_TW(a,b)};function gvjs_TW(a,b){gvjs_SW.call(this);this.destination=a;this.source=b}gvjs_o(gvjs_TW,gvjs_SW);
gvjs_TW.create=gvjs_SW.create;gvjs_TW.prototype.next=function(a){var b=this.destination;b&&b.next&&b.next(a)};gvjs_TW.prototype.error=function(a){var b=this.destination;b&&b.error&&this.destination.error(a)};gvjs_TW.prototype.complete=function(){var a=this.destination;a&&a.complete&&this.destination.complete()};gvjs_TW.prototype.cG=function(a){return this.source?this.source.subscribe(a):gvjs_HW.EMPTY};function gvjs_5ja(a,b){return new gvjs_OW(function(c){var d=new gvjs_HW,e=0;d.add(b.jr(function(){e===a.length?c.complete():(c.next(a[e++]),c.closed||d.add(this.jr()))}));return d})};function gvjs_UW(a){return function(b){for(var c=0,d=a.length;c<d&&!b.closed;c++)b.next(a[c]);b.complete()}};function gvjs_VW(a,b){b=void 0===b?gvjs_VW.now:b;this.Jja=a;this.now=b}gvjs_VW.prototype.jr=function(a,b,c){b=void 0===b?0:b;return(new this.Jja(this,a)).jr(c,b)};gvjs_VW.now=function(){return Date.now()};(function(){function a(){this.message="no elements in sequence";this.name="EmptyError";return this}a.prototype=Object.create(Error.prototype);return a})();function gvjs_6ja(a){return function(b){if(typeof a!==gvjs_d)throw new TypeError("argument is not a function. Are you looking for `mapTo()`?");return b.EJ(new gvjs_WW(a))}}function gvjs_WW(a){this.project=a;this.mu=void 0}gvjs_WW.prototype.call=function(a,b){return b.subscribe(new gvjs_XW(a,this.project,this.mu))};function gvjs_XW(a,b,c){gvjs_LW.call(this,a);this.project=b;this.count=0;this.mu=c||this}gvjs_o(gvjs_XW,gvjs_LW);gvjs_XW.EMPTY=gvjs_LW.EMPTY;gvjs_XW.create=gvjs_LW.create;
gvjs_XW.prototype.Xn=function(a){try{var b=this.project.call(this.mu,a,this.count++)}catch(c){this.destination.error(c);return}this.destination.next(b)};function gvjs_YW(){gvjs_LW.apply(this,arguments)}gvjs_o(gvjs_YW,gvjs_LW);gvjs_YW.EMPTY=gvjs_LW.EMPTY;gvjs_YW.create=gvjs_LW.create;gvjs_YW.prototype.xda=function(a){this.destination.next(a)};gvjs_YW.prototype.wda=function(){this.destination.complete()};function gvjs_ZW(a){gvjs_LW.call(this);this.parent=a;this.index=0}gvjs_o(gvjs_ZW,gvjs_LW);gvjs_ZW.EMPTY=gvjs_LW.EMPTY;gvjs_ZW.create=gvjs_LW.create;gvjs_ZW.prototype.Xn=function(a){this.parent.xda(a,this.index++)};gvjs_ZW.prototype.nB=function(a){this.parent.destination.error(a);this.unsubscribe()};gvjs_ZW.prototype.xx=function(){this.parent.wda(this);this.unsubscribe()};var gvjs__W=typeof Symbol===gvjs_d&&Symbol.iterator?Symbol.iterator:"@@iterator";function gvjs_7ja(a){return function(b){gvjs_8ja(a,b).catch(function(c){return b.error(c)})}}
function gvjs_8ja(a,b){var c,d,e,f;return gvjs__ja(this,function h(){var k,l;return gvjs_Ay(h,function(m){switch(m.Fi){case 1:m.Lx=2;m.Ws=3;if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var n=a[Symbol.asyncIterator];c=n?n.call(a):typeof __values===gvjs_d?__values(a):a[Symbol.iterator]();case 5:return gvjs_wy(m,c.next(),8);case 8:if(d=m.p6,d.done){m.hh(3);break}k=d.value;b.next(k);m.hh(5);break;case 3:m.MY=[m.Am];m.Lx=0;m.Ws=0;m.Lx=0;m.Ws=9;if(!d||d.done||!(f=
c.return)){m.hh(9);break}return gvjs_wy(m,f.call(c),9);case 9:m.MY[1]=m.Am;m.Lx=0;m.Ws=0;if(e)throw e.error;gvjs_yW(m,10,1);break;case 10:gvjs_yW(m,4);break;case 2:m.Lx=0;n=m.Am.g$;m.Am=null;l=n;e={error:l};m.hh(3);break;case 4:b.complete(),m.Fi=0}})})};function gvjs_9ja(a){return function(b){var c=a[gvjs__W]();do{var d=void 0;try{d=c.next()}catch(e){b.error(e);return}if(d.done){b.complete();break}b.next(d.value);if(b.closed)break}while(1);typeof c.return===gvjs_d&&b.add(function(){c.return&&c.return()});return b}};function gvjs_$ja(a){return function(b){var c=a[gvjs_DW]();if(typeof c.subscribe!==gvjs_d)throw new TypeError("Provided object does not correctly implement Symbol.observable");return c.subscribe(b)}};function gvjs_aka(a){return function(b){a.then(function(c){b.closed||(b.next(c),b.complete())},function(c){return b.error(c)}).then(null,gvjs_EW);return b}};function gvjs_0W(a){if(a&&typeof a[gvjs_DW]===gvjs_d)return gvjs_$ja(a);if(a&&typeof a.length===gvjs_g&&typeof a!==gvjs_d)return gvjs_UW(a);if(a&&typeof a.subscribe!==gvjs_d&&typeof a.then===gvjs_d)return gvjs_aka(a);if(a&&typeof a[gvjs__W]===gvjs_d)return gvjs_9ja(a);if(Symbol&&Symbol.asyncIterator&&a&&typeof a[Symbol.asyncIterator]===gvjs_d)return gvjs_7ja(a);throw new TypeError("You provided "+(null!==a&&typeof a===gvjs_h?"an invalid object":"'"+a+"'")+" where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.");
};function gvjs_bka(a){return a instanceof gvjs_OW?a:new gvjs_OW(gvjs_0W(a))};function gvjs_1W(a,b){var c=void 0===c?Infinity:c;if(typeof b===gvjs_d)return function(d){return d.p2(gvjs_1W(function(e,f){return gvjs_bka(a(e,f)).p2(gvjs_6ja(function(g,h){return b(e,g,f,h)}))},c))};typeof b===gvjs_g&&(c=b);return function(d){return d.EJ(new gvjs_2W(a,c))}}function gvjs_2W(a,b){b=void 0===b?Infinity:b;this.project=a;this.mX=b}gvjs_2W.prototype.call=function(a,b){return b.subscribe(new gvjs_3W(a,this.project,this.mX))};
function gvjs_3W(a,b,c){c=void 0===c?Infinity:c;gvjs_YW.call(this,a);this.project=b;this.mX=c;this.Uaa=!1;this.buffer=[];this.index=this.active=0}gvjs_o(gvjs_3W,gvjs_YW);gvjs_3W.EMPTY=gvjs_YW.EMPTY;gvjs_3W.create=gvjs_YW.create;gvjs_=gvjs_3W.prototype;gvjs_.Xn=function(a){this.active<this.mX?this.dka(a):this.buffer.push(a)};gvjs_.dka=function(a){var b=this.index++;try{var c=this.project(a,b)}catch(d){this.destination.error(d);return}this.active++;this.Yja(c,a,b)};
gvjs_.Yja=function(a,b,c){b=new gvjs_ZW(this,b,c);this.destination.add(b);b=void 0===b?new gvjs_ZW(this,void 0,void 0):b;b.closed||(a instanceof gvjs_OW?a.subscribe(b):gvjs_0W(a)(b))};gvjs_.xx=function(){this.Uaa=!0;0===this.active&&0===this.buffer.length&&this.destination.complete();this.unsubscribe()};gvjs_.xda=function(a){this.destination.next(a)};gvjs_.wda=function(a){var b=this.buffer;this.remove(a);this.active--;0<b.length?this.Xn(b.shift()):0===this.active&&this.Uaa&&this.destination.complete()};function gvjs_4W(){gvjs_HW.call(this)}gvjs_o(gvjs_4W,gvjs_HW);gvjs_4W.EMPTY=gvjs_HW.EMPTY;gvjs_4W.prototype.jr=function(){return this};function gvjs_5W(a,b){gvjs_HW.call(this);this.nA=a;this.Cha=b;this.pending=!1}gvjs_o(gvjs_5W,gvjs_4W);gvjs_5W.EMPTY=gvjs_4W.EMPTY;gvjs_5W.prototype.jr=function(a,b){b=void 0===b?0:b;if(this.closed)return this;this.state=a;var c=this.id;a=this.nA;null!=c&&(this.id=gvjs_6W(this,c,b));this.pending=!0;this.delay=b;(c=this.id)||(b=void 0===b?0:b,c=setInterval(a.flush.bind(a,this),b));this.id=c;return this};
function gvjs_6W(a,b,c){c=void 0===c?0:c;if(null!==c&&a.delay===c&&!1===a.pending)return b;clearInterval(b)}gvjs_5W.prototype.execute=function(a,b){if(this.closed)return Error("executing a cancelled action");this.pending=!1;if(a=this.Xja(a,b))return a;!1===this.pending&&null!=this.id&&(this.id=gvjs_6W(this,this.id,null))};gvjs_5W.prototype.Xja=function(a){var b=!1,c=void 0;try{this.Cha(a)}catch(d){b=!0,c=!!d&&d||Error(d)}if(b)return this.unsubscribe(),c};
gvjs_5W.prototype.JV=function(){var a=this.id,b=this.nA.actions,c=b.indexOf(this);this.state=this.Cha=null;this.pending=!1;this.nA=null;-1!==c&&b.splice(c,1);null!=a&&(this.id=gvjs_6W(this,a,null));this.delay=null};function gvjs_7W(a,b){b=void 0===b?gvjs_VW.now:b;gvjs_VW.call(this,a,function(){return gvjs_7W.FH&&gvjs_7W.FH!==c?gvjs_7W.FH.now():b()});var c=this;this.actions=[];this.active=!1}gvjs_o(gvjs_7W,gvjs_VW);gvjs_7W.now=gvjs_VW.now;gvjs_7W.prototype.jr=function(a,b,c){b=void 0===b?0:b;return gvjs_7W.FH&&gvjs_7W.FH!==this?gvjs_7W.FH.jr(a,b,c):gvjs_VW.prototype.jr.call(this,a,b,c)};
gvjs_7W.prototype.flush=function(a){var b=this.actions;if(this.active)b.push(a);else{var c;this.active=!0;do if(c=a.execute(a.state,a.delay))break;while(a=b.shift());this.active=!1;if(c){for(;a=b.shift();)a.unsubscribe();throw c;}}};var gvjs_cka=new gvjs_7W(gvjs_5W);function gvjs_dka(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=Infinity;c=void 0;var e=b[b.length-1];e&&typeof e.jr===gvjs_d?(c=b.pop(),1<b.length&&typeof b[b.length-1]===gvjs_g&&(d=b.pop())):typeof e===gvjs_g&&(d=b.pop());!c&&1===b.length&&b[0]instanceof gvjs_OW?b=b[0]:(d=void 0===d?Infinity:d,b=gvjs_1W(gvjs_NW,d)(c?gvjs_5ja(b,c):new gvjs_OW(gvjs_UW(b))));return b};function gvjs_8W(a,b){return function(c){return c.EJ(new gvjs_9W(a,b))}}function gvjs_9W(a,b){this.z2=a;this.mu=b}gvjs_9W.prototype.call=function(a,b){return b.subscribe(new gvjs_$W(a,this.z2,this.mu))};function gvjs_$W(a,b,c){gvjs_LW.call(this,a);this.z2=b;this.mu=c;this.count=0}gvjs_o(gvjs_$W,gvjs_LW);gvjs_$W.EMPTY=gvjs_LW.EMPTY;gvjs_$W.create=gvjs_LW.create;gvjs_$W.prototype.Xn=function(a){try{var b=this.z2.call(this.mu,a,this.count++)}catch(c){this.destination.error(c);return}b&&this.destination.next(a)};function gvjs_eka(a){function b(){return!b.hva.apply(b.mu,arguments)}b.hva=a;b.mu=void 0;return b};function gvjs_fka(a,b){return[gvjs_8W(b,void 0)(new gvjs_OW(gvjs_0W(a))),gvjs_8W(gvjs_eka(b))(new gvjs_OW(gvjs_0W(a)))]};(function(){function a(){this.message="argument out of range";this.name="ArgumentOutOfRangeError";return this}a.prototype=Object.create(Error.prototype);return a})();(function(){function a(b){this.message=b;this.name="NotFoundError";return this}a.prototype=Object.create(Error.prototype);return a})();(function(){function a(b){this.message=b;this.name="SequenceError";return this}a.prototype=Object.create(Error.prototype);return a})();(function(){function a(){this.message="Timeout has occurred";this.name="TimeoutError";return this}a.prototype=Object.create(Error.prototype);return a})();function gvjs_gka(){var a=void 0===a?gvjs_cka:a;return function(b){return b.EJ(new gvjs_aX(a))}}function gvjs_aX(a){this.pY=250;this.nA=a}gvjs_aX.prototype.call=function(a,b){return b.subscribe(new gvjs_bX(a,this.pY,this.nA))};function gvjs_bX(a,b,c){gvjs_LW.call(this,a);this.pY=b;this.nA=c;this.r0=this.QX=null;this.Oh=!1}gvjs_o(gvjs_bX,gvjs_LW);gvjs_bX.EMPTY=gvjs_LW.EMPTY;gvjs_bX.create=gvjs_LW.create;
gvjs_bX.prototype.Xn=function(a){gvjs_cX(this);this.r0=a;this.Oh=!0;this.add(this.QX=this.nA.jr(gvjs_hka,this.pY,this))};gvjs_bX.prototype.xx=function(){gvjs_dX(this);this.destination.complete()};function gvjs_dX(a){gvjs_cX(a);if(a.Oh){var b=a.r0;a.r0=null;a.Oh=!1;a.destination.next(b)}}function gvjs_cX(a){var b=a.QX;null!==b&&(a.remove(b),b.unsubscribe(),a.QX=null)}function gvjs_hka(a){gvjs_dX(a)};var gvjs_eX=gvjs_8d(["altKey","ctrlKey","metaKey","shiftKey"]),gvjs_ika=gvjs_eX.next().value,gvjs_jka=gvjs_eX.next().value,gvjs_kka=gvjs_eX.next().value,gvjs_lka=gvjs_eX.next().value,gvjs_mka=["drilldown",gvjs_0u,"rollup",gvjs_vx],gvjs_fX=[gvjs_ika,gvjs_jka,gvjs_kka,gvjs_lka],gvjs_gX=[gvjs_Tt,gvjs_0t,gvjs_au,gvjs_kd,gvjs_ld];
function gvjs_hX(){var a=this;this.XJ={highlight:gvjs_iX([gvjs_ld]),unhighlight:gvjs_iX([gvjs_kd]),rollup:gvjs_iX([gvjs_0t]),drilldown:gvjs_iX([gvjs_Tt])};this.Dba={highlight:function(){},unhighlight:function(){},rollup:function(){},drilldown:function(){}};this.jda=new gvjs_SW;var b=gvjs_8d(gvjs_fka(this.jda,function(d){return[gvjs_Tt,gvjs_au].includes(d.type)})),c=b.next().value;b=b.next().value;c=c.p2(gvjs_gka());gvjs_dka(c,b).subscribe(function(d){for(var e=gvjs_8d(gvjs_mka),f=e.next();!f.done;f=
e.next()){f=f.value;a:{var g=d;var h=a.XJ[f];if(h.enabled&&h.mouse===g.type){for(var k=gvjs_8d(gvjs_fX),l=k.next();!l.done;l=k.next())if(l=l.value,h.keys[l]!==!!g[l]){g=!1;break a}g=!0}else g=!1}if(g)a.Dba[f](d)}})}function gvjs_nka(a,b){for(var c=gvjs_8d(Object.keys(a.XJ)),d=c.next();!d.done;d=c.next()){d=d.value;var e=gvjs_iX(b[d]);e&&(a.XJ[d]=e)}}
gvjs_hX.prototype.F0=function(a,b,c){for(var d=this,e=gvjs_8d(gvjs_gX),f=e.next();!f.done;f=e.next())a.ic(b,f.value,function(g){d.jda.next(g)});this.Dba=c};
function gvjs_iX(a){if(!a)return null;var b={enabled:!1,mouse:"",keys:{}};if(0===a.length)return b;var c=[].concat(gvjs_9d(a)),d=c.shift()||"";if(!gvjs_gX.includes(d)||!c.every(function(e){return gvjs_fX.includes(e)}))return null;b.enabled=!0;b.mouse=d;d=gvjs_8d(gvjs_fX);for(c=d.next();!c.done;c=d.next())b.keys[c.value]=!1;a=gvjs_8d(a);for(c=a.next();!c.done;c=a.next())b.keys[c.value]=!0;return b};function gvjs_jX(a){gvjs_Nn.call(this,a);this.el=new gvjs_7n;this.$fa=this.Es=this.tree=this.canvas=this.renderer=null;this.title="";this.KR=this.ja=this.Kga=null;this.Vfa=this.rL=!1;this.kfa=null;this.Yfa=!0;this.Pga=null;this.p5="";this.ID=this.maxDepth=1;this.iba=.5;this.Qca=0;this.qha=!1;this.header=0;this.V7=this.borderColor="";this.IB=this.Qp=null;this.y$=this.x$="";this.fontSize=0;this.bQ=this.lR=this.rR=this.zR=this.bM=this.o_=this.iR=this.qR=this.uR=this.MU=this.fontFamily="";this.WK=!1;
this.lba=60/(1+Math.sqrt(5));this.g1=0;this.a1=.5;this.S0=1;this.C5=this.r_=null;this.d1=1;this.$0=.75;this.R0=.5;this.P0=this.c1=this.B5=this.p_=null;this.GD=-1*Number.MAX_VALUE;this.LD=Number.MAX_VALUE;this.sb=this.options=this.Ta=null;this.height=this.width=0;this.zz=this.m0=null;this.W7=this.Q9=this.hba=!0;this.j3=this.Tx=this.Hh=this.Ux=null;this.WL=new gvjs_hX}gvjs_o(gvjs_jX,gvjs_Nn);gvjs_=gvjs_jX.prototype;
gvjs_.M=function(){gvjs_E(this.Es);delete this.Es;null!==this.renderer&&(this.renderer.clear(),delete this.renderer);gvjs_E(this.tree);delete this.tree;gvjs_E(this.sb);delete this.sb;gvjs_Nn.prototype.M.call(this)};gvjs_.He=function(){};gvjs_.getSelection=function(){return this.el.getSelection()};gvjs_.setSelection=function(a){if(Array.isArray(a)&&0!==a.length){var b=a[0].row;if(a=this.tree.uw[b]||null)this.el.pj=new Set,this.el.Kp(b)}else this.el.pj=new Set,a=this.tree.ep[0];a&&a.draw()};
gvjs_.Moa=function(a){if(null==a)return null;a=this.tree.uw[null==a.row?-1:a.row]||null;return null!==a?{value:a.color,color:gvjs_kX(a,!1,!1)}:null};gvjs_.Rd=function(a,b,c){this.options=new gvjs_yj([c]);this.width=this.La(this.options);this.height=this.getHeight(this.options);c=new gvjs_A(this.width,this.height);if(null===this.sb){var d=gvjs_K(this.options,gvjs_Bu);this.sb=new gvjs_0B(this.container,c,a,d)}else this.sb.update(c,a);this.Ta=b;this.sb.rl(this.mna.bind(this),a)};
gvjs_.mna=function(){var a=this.sb.Oa();this.renderer=a;a.getContainer().oncontextmenu=function(){return!1};gvjs_E(this.Es);this.Es=null;gvjs_E(this.tree);this.tree=null;gvjs_oka(this,this.options);gvjs_pka(this,this.Ta);this.LD=Number.MAX_VALUE;this.GD=-1*Number.MAX_VALUE;this.tree=this.xW(this.Es);null!==this.c1&&(this.LD=this.c1);null!==this.P0&&(this.GD=this.P0);if(a=this.tree.ep[0])a.normalize(this.LD,this.GD),null!==this.Tx&&(this.Tx=null);this.setSelection([]);gvjs_I(this,gvjs_i,{})};
gvjs_.caa=function(){var a=this.$fa,b=a.getParent();if(!b)return!1;null!==a.tooltip&&a.tooltip.detach();this.setSelection([{row:b.row}]);return!0};gvjs_.Toa=function(){return this.Qca};
function gvjs_oka(a,b){function c(f,g){return""===f||f===gvjs_f?gvjs_sj(gvjs__z(gvjs_tj(gvjs_oj(g).hex),.35)):f}a.title=gvjs_J(b,gvjs_cx);a.c1=b.Aa("minColorValue");a.P0=b.Aa("maxColorValue");a.WK=gvjs_K(b,"rotatingHue",!1);a.WK&&(a.lba=gvjs_L(b,"hueStep",60/(1+Math.sqrt(5))),a.g1=gvjs_L(b,"minSaturation",0),a.a1=gvjs_L(b,"midSaturation",.5),a.S0=gvjs_L(b,"maxSaturation",1),a.r_=b.Aa("headerSaturation"),a.C5=b.Aa("noSaturation"),a.d1=gvjs_L(b,"minLightness",1),a.$0=gvjs_L(b,"midLightness",.75),a.R0=
gvjs_L(b,"maxLightness",.5),a.p_=b.Aa("headerLightness"),a.B5=b.Aa("noLightness"));a.rL=gvjs_K(b,"showScale",!1);a.Vfa=gvjs_K(b,"scale.showText",!1);a.maxDepth=gvjs_Mj(b,gvjs_Hv,1);a.ID=gvjs_Mj(b,"maxPostDepth",0);a.qha=gvjs_K(b,"useWeightedAverageForAggregation",!1);a.iba=gvjs_Mj(b,"hintOpacity",.5);1>a.maxDepth&&(a.maxDepth=1);0>a.ID&&(a.ID=0);a.hba=gvjs_K(b,"highlightOnMouseOver",!1);a.Q9=gvjs_K(b,"enableHighlight",!1);a.W7=gvjs_K(b,"borderOnMouseOver",!0);a.Yfa=gvjs_K(b,gvjs_Sw,!0);a.p5=gvjs_J(b,
"tooltipClass");var d=b.fa("generateTooltip",null);d&&(a.K$=d);a.borderColor=gvjs_ly(b,"borderColor",gvjs_ea);a.V7=gvjs_ly(b,"borderMouseOverColor",gvjs_ea);d=[5,4,3];var e=[.2,.4,.6];a.Qp=b.fa("borderMouseOverSizes",d);a.IB=b.fa("borderMouseOverOpacities",e);a.Qp.length!==a.IB.length&&(alert("The arrays' lengths for border mouse over sizes and opacities are not equal. We will use default borders."),a.Qp=d,a.IB=e);for(d=0;d<a.Qp.length;d++)a.Qp[d]=Number(a.Qp[d]),a.IB[d]=Number(a.IB[d]);a.fontSize=
gvjs_Mj(b,gvjs_wp,12);a.fontFamily=gvjs_J(b,gvjs_up,gvjs__r);a.x$=gvjs_ly(b,gvjs_Au,gvjs_jr);a.y$=gvjs_ly(b,"fontMouseOverColor",gvjs_ca);0<=a.fontFamily.indexOf("/")&&(alert("Bad font family! We will use Arial"),a.fontFamily=gvjs__r);a.ja=gvjs_oy(b,gvjs_9w,{color:a.x$,bb:a.fontFamily,fontSize:a.fontSize});d=gvjs_x(a.ja);d.color=a.y$;a.KR=gvjs_oy(b,"mouseOverTextStyle",d);d=gvjs_x(a.ja);d.bold=!0;a.Kga=gvjs_oy(b,gvjs_fx,d);a.kfa=gvjs_oy(b,"scale.textStyle",gvjs_x(a.ja));d=gvjs_Hz({background:gvjs_av,
color:"infotext",padding:gvjs_Mr,border:gvjs_Nr,"font-size":a.ja.fontSize+"px; ","font-family":a.ja.bb});d=gvjs_J(b,"tooltipStyleString",d);a.Pga=gvjs_Gz(d);a.MU=gvjs_ly(b,"noColor",gvjs_ca);a.uR=gvjs_ly(b,gvjs_Mv,"#dc3912");a.qR=gvjs_ly(b,gvjs_Jv,"#efe6dc");a.iR=gvjs_ly(b,gvjs_Gv,gvjs_ir);a.o_=gvjs_ly(b,gvjs_Wu,gvjs_wr);a.bM=gvjs_ly(b,"noHighlightColor","");a.zR=gvjs_ly(b,"minHighlightColor","");a.rR=gvjs_ly(b,"midHighlightColor","");a.lR=gvjs_ly(b,"maxHighlightColor","");a.bQ=gvjs_ly(b,"headerHighlightColor",
"");a.bM=c(a.bM,a.MU);a.zR=c(a.zR,a.uR);a.lR=c(a.lR,a.iR);a.rR=c(a.rR,a.qR);a.bQ=c(a.bQ,a.o_);a.header=gvjs_Mj(b,gvjs_Xu,22);a.j3=b.cb("residualNode");gvjs_nka(a.WL,b.pb("eventsConfig",{}))}function gvjs_pka(a,b){if(2===b.$()){b=new gvjs_N(b);var c={};b.Hn([0,1,(c.type=gvjs_g,c.calc=function(){return 1},c)])}gvjs_E(a.Es);a.Es=new gvjs_0L(b);if(1<a.Es.ep.length)throw Error("Found "+a.Es.ep.length+" root nodes. Only a single root node is allowed.");}
gvjs_.xW=function(a){var b=this;a=this.WK?new gvjs_1L(a,function(c){return new gvjs_lX(b,c)},void 0,0,this.lba):new gvjs_1L(a,function(c){return new gvjs_lX(b,c)});this.Qca=a.getHeight();a.MB(function(c){var d=c.Cea;d=typeof d===gvjs_g&&0<=d?d:0;return{primary:d,secondary:0<d?c.secondary:null,use_weighted_avg:c.treemap.qha}},function(c,d){if(0===d.length)return c;for(var e=[],f=[],g=0;g<d.length;g++)e.push(d[g].primary),f.push(d[g].secondary);e=gvjs_AW(c.primary,e);if(c.use_weighted_avg)for(f=c=0;f<
d.length;f++){if(g=d[f].primary,0!==g){var h=d[f].secondary;h=null===h?0:h;c+=g/e*h}}else c=gvjs_0ja(c.secondary,f);return{primary:e,secondary:c}},function(c,d){c.area=d.primary;c.color=0<c.area?d.secondary:null});a.VL(function(c){null!==c.color&&(c.color<b.LD&&(b.LD=c.color),c.color>b.GD&&(b.GD=c.color))});return a};
gvjs_.OH=function(a){var b=this.Ux;gvjs_mX(this);this.Hh=this.renderer.Sa();this.renderer.appendChild(this.canvas,this.Hh);var c=b.top+7,d=b.height-7,e=this.uR,f=this.qR,g=this.iR;this.WK&&null!=a&&(e=gvjs_sj(gvjs_Xz(a,this.g1,this.d1)),f=gvjs_sj(gvjs_Xz(a,this.a1,this.$0)),g=gvjs_sj(gvjs_Xz(a,this.S0,this.R0)));a=b.width/2;e=new gvjs_3({gradient:{x1:b.left,y1:0,x2:b.left+a+1,y2:0,Vf:e,sf:f}});f=new gvjs_3({gradient:{x1:b.left+a,y1:0,x2:b.left+b.width,y2:0,Vf:f,sf:g}});this.renderer.yb(b.left,c,b.width,
d,new gvjs_3({stroke:gvjs_qr,strokeWidth:2}),this.Hh);this.renderer.yb(b.left,c,a+1,d,e,this.Hh);this.renderer.yb(b.left+a,c,b.width-a,d,f,this.Hh);if(!this.Vfa)return 0;c=gvjs_x(this.kfa);d=this.renderer.ce(this.LD.toString(),b.left,b.top+b.height+3,0,gvjs_0,gvjs_2,c,this.Hh);f=d.offsetHeight;d=this.renderer.ce(this.GD.toString(),b.left+b.width,b.top+b.height+3,0,gvjs_R,gvjs_2,c,this.Hh);return f=Math.max(f,d.offsetHeight)};
function gvjs_mX(a){if(null!==a.Hh){var b=a.Hh.j();b.parentNode.removeChild(b);a.Hh=null}}function gvjs_nX(a){null!==a.Tx&&(a.Tx.parentNode.removeChild(a.Tx),a.Tx=null)}
function gvjs_lX(a,b){gvjs_XL.call(this,b.getId(),b.getName());this.treemap=a;this.hue=this.color=this.uf=this.Kc=this.KI=this.KO=this.Ks=this.jC=null;this.area=0;this.opacity=1;this.highlight=this.Cw=!1;this.D1=this.gba="";this.collapsed=!1;this.WL=new gvjs_hX;this.row=b.getId();this.lI=gvjs_ZL(b);this.tooltip=new gvjs_gB(null,null,a.renderer?gvjs_3g(a.renderer.getContainer()):null);this.Cea=b.getValue(2);this.secondary=4<=b.mb().$()?b.getValue(3):this.Cea;this.WL.XJ=a.WL.XJ}gvjs_o(gvjs_lX,gvjs_XL);
gvjs_=gvjs_lX.prototype;gvjs_.M=function(){delete this.uf;null!==this.tooltip&&(gvjs_E(this.tooltip),delete this.tooltip);gvjs_XL.prototype.M.call(this)};
gvjs_.normalize=function(a,b){if(null!==this.color){var c=b-a;0!==c?(this.color=gvjs_0g(this.color,a,b),this.color-=a,this.color/=c):this.color=.5}c=0;for(var d=this.ze();c<d;c++)this.getChildren()[c].normalize(a,b);this.treemap.Yfa&&(b=this.treemap,c=this.row,d=this.lI,a=this.tooltip,null!==c&&null!=b.K$?(b=b.K$(c,this.area,this.color),a.FT(gvjs_LA(b))):""===b.p5?a.FT(gvjs_5f(gvjs_Ob,{style:gvjs_Hf(b.Pga)},gvjs_2f(d))):(a.className=b.p5,a.du(d)))};
function gvjs_kX(a,b,c){var d=null;if(null===a.hue)if(c){var e=gvjs_tj(gvjs_oj(a.treemap.lR).hex);var f=gvjs_tj(gvjs_oj(a.treemap.zR).hex);var g=gvjs_tj(gvjs_oj(a.treemap.rR).hex);d=gvjs_tj(gvjs_oj(a.treemap.bQ).hex);var h=gvjs_tj(gvjs_oj(a.treemap.bM).hex)}else e=gvjs_tj(gvjs_oj(a.treemap.iR).hex),f=gvjs_tj(gvjs_oj(a.treemap.uR).hex),g=gvjs_tj(gvjs_oj(a.treemap.qR).hex),d=gvjs_tj(gvjs_oj(a.treemap.o_).hex),h=gvjs_tj(gvjs_oj(a.treemap.MU).hex);else e=gvjs_Xz(a.hue,a.treemap.S0,a.treemap.R0),f=gvjs_Xz(a.hue,
a.treemap.g1,a.treemap.d1),g=gvjs_Xz(a.hue,a.treemap.a1,a.treemap.$0),c&&(e=gvjs__z(e,.35),f=gvjs__z(f,.35),g=gvjs__z(g,.35)),null!==a.treemap.r_&&null!==a.treemap.p_&&(d=gvjs_Xz(a.hue,a.treemap.r_,a.treemap.p_),c&&(d=gvjs__z(d,.35))),null!==a.treemap.C5&&null!==a.treemap.B5?(h=gvjs_Xz(a.hue,a.treemap.C5,a.treemap.B5),c&&(h=gvjs__z(h,.35))):h=c?gvjs_tj(gvjs_oj(a.treemap.bM).hex):gvjs_tj(gvjs_oj(a.treemap.MU).hex);return gvjs_sj(b&&null!==d?d:null===a.color?h:.5>a.color?gvjs_vj(g,f,2*a.color):gvjs_vj(e,
g,2*(a.color-.5)))}function gvjs_oX(a){delete a.uf;a.uf=null;for(var b=0,c=a.ze();b<c;b++)gvjs_oX(a.getChildren()[b])}function gvjs_pX(a,b){null!==a.jC&&(a.jC.parentNode.removeChild(a.jC),a.jC=null);if(a.Ks){b=gvjs_x(b);b.bold=b.bold||a.Ks.header;var c=gvjs_AG(a.treemap.renderer.me.bind(a.treemap.renderer),a.Ks.text,b,a.Ks.width,1),d="";0<c.lines.length&&(d=c.lines[0]);a.jC=a.treemap.renderer.ce(d,a.Ks.Sxa+a.Ks.width/2,a.Ks.Txa,a.Ks.width,gvjs_0,gvjs_0,b,a.Kc);a.jC.setAttribute(gvjs_iw,gvjs_f)}}
function gvjs_qX(a,b){if(null!==a.treemap.zz){var c=a.treemap.m0,d=gvjs_Oh();(b=gvjs_xW(0,b.relatedTarget))&&d.wP(b)&&gvjs_pX(c,a.treemap.ja);a.treemap.zz.H&&(c=a.treemap.zz.j(),c.parentNode.removeChild(c));a.treemap.zz=null;a.treemap.m0=null}}
gvjs_.draw=function(){var a=Math.max.apply(Math,this.treemap.Qp),b=this.treemap.width-2*a,c=this.treemap.height,d=this.treemap.header;gvjs_oX(this);var e=0;this.treemap.renderer.clear();this.treemap.canvas=this.treemap.renderer.Lm(b,c);var f=Math.pow(2*(b+c),1/3),g=(1+Math.sqrt(5))/2*f,h=b/3;""!==this.treemap.title&&(this.treemap.renderer.ce(this.treemap.title,a,g/2,b-h,gvjs_2,gvjs_0,this.treemap.Kga,this.treemap.canvas),e=g);this.treemap.rL&&(e=(g-f)/2,this.treemap.Ux=new gvjs_5(b-h-a,e,h,gvjs_0g(g-
2*e,0,g)),h=this.treemap.OH(),e=g+h,this.treemap.WK&&gvjs_mX(this.treemap));this.uf=new gvjs_5(a,d+e,b-2*a,c-d-e-a);gvjs_rX(this,d,0);this.Cw=!1;this.Rd(d,0);this.treemap.$fa=this;this.treemap.renderer.ic(this.treemap.canvas,gvjs_kd,this.Eta.bind(this))};
function gvjs_sX(a,b,c,d,e,f,g){a.gba=gvjs_kX(a,g,!0);a.D1=gvjs_kX(a,g,!1);if(0>=e||0>=d||a.Cw&&g)return null;null===a.Kc&&(a.Kc=a.treemap.renderer.Sa(),a.treemap.renderer.appendChild(a.treemap.canvas,a.Kc));var h=new gvjs_3({fill:a.D1,fillOpacity:a.opacity});a.Cw||h.rd(a.treemap.borderColor,1);h=a.treemap.renderer.yb(b,c,d,e,h,a.Kc);a.Cw||(a.Ks={text:f,Sxa:b,Txa:c+e/2,width:d,height:e,header:g},gvjs_pX(a,a.treemap.ja));return h}
function gvjs_tX(a){a.KO=gvjs_sX(a,a.uf.left,a.uf.top,a.uf.width,a.uf.height,a.lI,!1)}function gvjs_uX(a,b){a.KI=gvjs_sX(a,a.uf.left,a.uf.top-b,a.uf.width,b,a.lI,!0)}
gvjs_.Rd=function(a,b){this.opacity=1;this.highlight=!1;var c=this.ze();this.KI=this.KO=this.Kc=null;if(0===c)gvjs_tX(this);else if(b>=this.treemap.maxDepth||this.collapsed){0!==a&&this.uf.height>=a&&!this.collapsed&&b<this.treemap.maxDepth&&gvjs_uX(this,a);if(!this.collapsed&&b<this.treemap.maxDepth+this.treemap.ID){for(var d=0;d<c;d++){var e=this.getChildren()[d];e.highlight=this.highlight;e.Cw=!0;e.Rd(a,b+1)}this.opacity=(this.treemap.maxDepth+this.treemap.ID-b)/this.treemap.ID*this.treemap.iba}gvjs_tX(this)}else{for(d=
0;d<c;d++)e=this.getChildren()[d],e.Cw=!1,e.highlight=this.highlight,e.Rd(a,b+1);0!==a&&gvjs_uX(this,a)}this.F0()};gvjs_.xxa=function(a,b){if(null!==a.treemap.j3){var c=a.treemap.j3;if(b.getName()===c)return-1;if(a.getName()===c)return 1}return b.area===a.area?a.row-b.row:b.area-a.area};
function gvjs_rX(a,b,c){c>=a.treemap.maxDepth-1&&(b=0);a.collapsed=!1;var d=gvjs_Le(a.getChildren());d.sort(a.xxa);gvjs_vX(a,d,gvjs_x(a.uf),0,d.length,a.area);a=0;for(var e=d.length;a<e;a++)d[a].ze()&&(d[a].uf.height>2*b?(d[a].uf.top+=b,d[a].uf.height-=b,gvjs_rX(d[a],b,c+1)):d[a].collapsed=!0)}
function gvjs_vX(a,b,c,d,e,f){if(!(0>=e))if(1===e)b[d].uf=new gvjs_5(Number(c.left),Number(c.top),0===f?0:Number(c.width),0===f?0:Number(c.height));else{var g=b[d].area,h,k=1;for(h=d+1;h<d+e&&2*(g+b[h].area)<f;h++)g+=b[h].area,k++;h=f-g;e-=k;var l=c.left,m=c.top,n=c.width;c=c.height;if(0>=g+h)var p=f=0;else n>=c?(f=Math.ceil(g*n/f),p=0):(f=Math.ceil(g*c/f),p=1);0===p?(gvjs_vX(a,b,new gvjs_5(l,m,f,c),d,k,g),gvjs_vX(a,b,new gvjs_5(l+f,m,n-f,c),d+k,e,h)):(gvjs_vX(a,b,new gvjs_5(l,m,n,f),d,k,g),gvjs_vX(a,
b,new gvjs_5(l,m+f,n,c-f),d+k,e,h))}}function gvjs_wX(a){if(a.treemap.hba||a.treemap.Q9){var b=a.D1;a.highlight&&(b=a.gba);b=new gvjs_3({fill:b,fillOpacity:a.opacity});a.Cw||b.rd(a.treemap.borderColor,1);null!==a.KO&&a.treemap.renderer.rj(a.KO,b);null!==a.KI&&a.treemap.renderer.rj(a.KI,b);b=0;for(var c=a.ze();b<c;b++){var d=a.getChildren()[b];d.highlight=a.highlight;gvjs_wX(d)}}}
gvjs_.ona=function(){this.treemap.setSelection([{row:this.row}]);gvjs_I(this.treemap,gvjs_k,null);gvjs_I(this.treemap,"drilldown",{row:this.row})};gvjs_.Vva=function(){this.treemap.caa()&&(gvjs_I(this.treemap,"rollup",{row:this.row}),gvjs_I(this.treemap,gvjs_k,null))};
gvjs_.vra=function(a){this.highlight=!0;gvjs_wX(this);if(this.treemap.W7){gvjs_qX(this,a);a=0;null!==this.KI&&(a=this.treemap.header);this.treemap.zz=this.treemap.renderer.Sa();this.treemap.renderer.appendChild(this.treemap.canvas,this.treemap.zz);for(var b=this.treemap.Qp.length,c=0;c<b;c++){var d=this.treemap.Qp[c];this.treemap.renderer.yb(this.uf.left-d/2,this.uf.top-a-d/2,this.uf.width+d,this.uf.height+a+d,new gvjs_3({stroke:this.treemap.V7,strokeWidth:this.treemap.Qp[c],strokeOpacity:this.treemap.IB[c]}),
this.treemap.zz)}this.treemap.m0=this;gvjs_pX(this,this.treemap.KR)}this.treemap.KR&&gvjs_pX(this,this.treemap.KR);this.treemap.rL&&(null!==this.hue&&(typeof this.secondary===gvjs_g?this.treemap.OH(this.hue):gvjs_mX(this.treemap)),b=0,null!==this.color&&(b=this.color),typeof this.secondary===gvjs_g?(a=this.treemap,b=gvjs_0g(b,0,1),b*=a.Ux.width,b+=a.Ux.left,gvjs_nX(a),b=gvjs_RA([{x:b-5,y:a.Ux.top},{x:b,y:a.Ux.top+5},{x:b+5,y:a.Ux.top}]),a.Tx=a.renderer.Ia(b,new gvjs_3({fill:"#777777"}),a.canvas)):
gvjs_nX(this.treemap));gvjs_I(this.treemap,gvjs_0u,{row:this.row})};gvjs_.aha=function(){gvjs_nX(this.treemap);null!==this.hue&&gvjs_mX(this.treemap);this.highlight=!1;gvjs_wX(this);this.treemap.ja&&gvjs_pX(this,this.treemap.ja);gvjs_I(this.treemap,gvjs_vx,{row:this.row})};gvjs_.Eta=function(a){gvjs_xW(gvjs_Oh(),a.relatedTarget)&&gvjs_qX(this,a);gvjs_I(this.treemap,gvjs_3v,{row:this.row});this.aha(a)};
gvjs_.F0=function(){var a=this;null!==this.tooltip&&this.tooltip.detach();if(null!==this.Kc&&!this.Cw){var b=this.Kc.j();null!==this.tooltip&&""!==this.tooltip.tP()&&this.tooltip.CB(b);this.$v()?gvjs_C(b,"cursor",gvjs_bu):gvjs_C(b,"cursor",gvjs_hw);this.treemap.renderer.ic(b,gvjs_ld,function(){gvjs_I(a.treemap,gvjs_4v,{row:a.row})});this.treemap.renderer.ic(b,gvjs_kd,function(){gvjs_I(a.treemap,gvjs_3v,{row:a.row})});this.WL.F0(this.treemap.renderer,b,{highlight:this.vra.bind(this),unhighlight:this.aha.bind(this),
rollup:this.Vva.bind(this),drilldown:this.ona.bind(this)})}};gvjs_q(gvjs_Yc,gvjs_jX,void 0);gvjs_jX.prototype.draw=gvjs_jX.prototype.draw;gvjs_jX.prototype.getSelection=gvjs_jX.prototype.getSelection;gvjs_jX.prototype.setSelection=gvjs_jX.prototype.setSelection;gvjs_jX.prototype.goUpAndDraw=gvjs_jX.prototype.caa;gvjs_jX.prototype.getMaxPossibleDepth=gvjs_jX.prototype.Toa;gvjs_jX.prototype.clearChart=gvjs_jX.prototype.Jb;gvjs_jX.prototype.getElementColor=gvjs_jX.prototype.Moa;
